/**
 * 兼容性层 - 别名注册表
 * 
 * 映射旧工具名到新工具名及其默认参数
 * 依据: docs/MCP_TOOL_COMPRESSION_MAPPING.md
 */

export interface ToolAlias {
    newTool: string;
    description?: string;
    injectedParams?: Record<string, unknown>;
}

export const LEGACY_ALIASES: Record<string, ToolAlias> = {
    // DISCOVERY
    'available_categories': { newTool: 'available_categories' },
    'available_tools': { newTool: 'available_tools' },
    'search_tools': { newTool: 'search_tools' },

    // SKILLS
    'list_skills': { newTool: 'list_skills' },
    'search_skills': { newTool: 'search_skills' },
    'run_skill': { newTool: 'run_skill' },

    // MARKET_DATA
    'get_asset_info': { newTool: 'get_asset_info' },
    'get_batch_quotes': { newTool: 'get_batch_quotes' },
    'get_kline': { newTool: 'get_kline_data' },
    'get_latest_quotes': { newTool: 'get_batch_quotes', injectedParams: { force_refresh: true } },
    'get_multi_period_data': { newTool: 'get_multi_period_data' },
    'get_option_chain': { newTool: 'options_manager', injectedParams: { action: 'chain' } },
    'get_orderbook': { newTool: 'get_orderbook' },
    'get_realtime_quote': { newTool: 'get_realtime_quote' },
    'get_realtime_subscription_status': { newTool: 'data_sync_manager', injectedParams: { action: 'subscription_status' } },
    'get_sync_status': { newTool: 'data_sync_manager', injectedParams: { action: 'sync_status' } },
    'get_trades': { newTool: 'get_trades' },
    'get_vector_sync_status': { newTool: 'data_sync_manager', injectedParams: { action: 'vector_sync_status' } },
    'macro_to_sector': { newTool: 'macro_manager', injectedParams: { action: 'macro_to_sector' } },
    'sector_prosperity': { newTool: 'sector_manager', injectedParams: { action: 'prosperity' } },
    'subscribe_realtime_quotes': { newTool: 'subscribe_realtime_quotes' },
    'sync_batch_financials': { newTool: 'data_sync_manager', injectedParams: { action: 'sync_financials', batch: true } },
    'sync_batch_kline': { newTool: 'data_sync_manager', injectedParams: { action: 'sync_kline', batch: true } },
    'sync_macro_data': { newTool: 'data_sync_manager', injectedParams: { action: 'sync_macro' } },
    'sync_market_sentiment': { newTool: 'data_sync_manager', injectedParams: { action: 'sync_sentiment' } },
    'sync_pattern_vectors': { newTool: 'data_sync_manager', injectedParams: { action: 'sync_vectors' } },
    'sync_stock_dividends': { newTool: 'data_sync_manager', injectedParams: { action: 'sync_dividends' } },
    'sync_stock_info': { newTool: 'data_sync_manager', injectedParams: { action: 'sync_stock_info' } },
    'sync_stock_kline': { newTool: 'data_sync_manager', injectedParams: { action: 'sync_kline' } },
    'sync_stock_quotes': { newTool: 'data_sync_manager', injectedParams: { action: 'sync_quotes' } },
    'unsubscribe_realtime_quotes': { newTool: 'unsubscribe_realtime_quotes' },
    'update_stock_sector': { newTool: 'data_sync_manager', injectedParams: { action: 'update_stock_sector' } },

    // TECHNICAL_ANALYSIS
    'analyze_cross_period_signals': { newTool: 'technical_analysis_manager', injectedParams: { action: 'cross_period' } },
    'analyze_implied_volatility': { newTool: 'options_manager', injectedParams: { action: 'implied_vol' } },
    'calculate_dmi': { newTool: 'technical_analysis_manager', injectedParams: { action: 'dmi' } },
    'calculate_factor': { newTool: 'quant_manager', injectedParams: { action: 'calculate_factor' } },
    'calculate_greeks': { newTool: 'options_manager', injectedParams: { action: 'greeks' } },
    'calculate_indicators': { newTool: 'calculate_technical_indicators' },
    'calculate_option_price': { newTool: 'options_manager', injectedParams: { action: 'price' } },
    'detect_patterns': { newTool: 'check_candlestick_patterns' },
    'detect_patterns_extended': { newTool: 'technical_analysis_manager', injectedParams: { action: 'extended_patterns' } },
    'generate_trading_signal': { newTool: 'generate_trading_signal' },
    'get_momentum_analysis': { newTool: 'technical_analysis_manager', injectedParams: { action: 'momentum_analysis' } },
    'get_pattern_list': { newTool: 'technical_analysis_manager', injectedParams: { action: 'pattern_list' } },
    'get_support_resistance': { newTool: 'get_support_resistance' },
    'get_trend_analysis': { newTool: 'technical_analysis_manager', injectedParams: { action: 'trend_analysis' } },
    'get_volatility_analysis': { newTool: 'technical_analysis_manager', injectedParams: { action: 'volatility_analysis' } },
    'get_volume_profile': { newTool: 'technical_analysis_manager', injectedParams: { action: 'volume_profile' } },
    'trend_strength': { newTool: 'technical_analysis_manager', injectedParams: { action: 'trend_strength' } },
    'williams_combo': { newTool: 'technical_analysis_manager', injectedParams: { action: 'williams' } },

    // FUNDAMENTAL_ANALYSIS
    'calculate_health_score': { newTool: 'get_valuation_metrics' }, // Mapping to closest available
    'calculate_sotp_valuation': { newTool: 'fundamental_analysis_manager', injectedParams: { action: 'sotp_valuation' } },
    'compare_valuations': { newTool: 'fundamental_analysis_manager', injectedParams: { action: 'compare_valuations' } },
    'ddm_valuation': { newTool: 'fundamental_analysis_manager', injectedParams: { action: 'ddm_valuation' } },
    'generate_stock_report': { newTool: 'comprehensive_manager', injectedParams: { action: 'stock_report' } },
    'get_dcf_valuation': { newTool: 'fundamental_analysis_manager', injectedParams: { action: 'dcf_valuation' } },
    'get_financials': { newTool: 'get_historical_financials' },
    'get_valuation_metrics': { newTool: 'get_valuation_metrics' },
    'margin_of_safety': { newTool: 'fundamental_analysis_manager', injectedParams: { action: 'margin_of_safety' } },
    'moat_proxy': { newTool: 'fundamental_analysis_manager', injectedParams: { action: 'moat_proxy' } },
    'relative_valuation': { newTool: 'fundamental_analysis_manager', injectedParams: { action: 'relative_valuation' } },

    // ALERTS
    'create_price_alert': { newTool: 'alerts_manager', injectedParams: { action: 'create', type: 'price' } },
    'get_price_alerts': { newTool: 'alerts_manager', injectedParams: { action: 'get', type: 'price' } },
    'delete_price_alert': { newTool: 'alerts_manager', injectedParams: { action: 'delete', type: 'price' } },
    'check_price_alerts': { newTool: 'alerts_manager', injectedParams: { action: 'check', type: 'price' } },
    'create_indicator_alert': { newTool: 'alerts_manager', injectedParams: { action: 'create', type: 'indicator' } },
    'get_indicator_alerts': { newTool: 'alerts_manager', injectedParams: { action: 'get', type: 'indicator' } },
    'delete_indicator_alert': { newTool: 'alerts_manager', injectedParams: { action: 'delete', type: 'indicator' } },
    'check_indicator_alerts': { newTool: 'alerts_manager', injectedParams: { action: 'check', type: 'indicator' } },
    'create_limit_alert': { newTool: 'alerts_manager', injectedParams: { action: 'create', type: 'limit' } },
    'get_limit_alerts': { newTool: 'alerts_manager', injectedParams: { action: 'get', type: 'limit' } },
    'delete_limit_alert': { newTool: 'alerts_manager', injectedParams: { action: 'delete', type: 'limit' } },
    'check_limit_alerts': { newTool: 'alerts_manager', injectedParams: { action: 'check', type: 'limit' } },
    'create_fund_flow_alert': { newTool: 'alerts_manager', injectedParams: { action: 'create', type: 'fund_flow' } },
    'get_fund_flow_alerts': { newTool: 'alerts_manager', injectedParams: { action: 'get', type: 'fund_flow' } },
    'delete_fund_flow_alert': { newTool: 'alerts_manager', injectedParams: { action: 'delete', type: 'fund_flow' } },
    'check_fund_flow_alerts': { newTool: 'alerts_manager', injectedParams: { action: 'check', type: 'fund_flow' } },
    'create_combo_alert': { newTool: 'alerts_manager', injectedParams: { action: 'create', type: 'combo' } },
    'get_combo_alerts': { newTool: 'alerts_manager', injectedParams: { action: 'get', type: 'combo' } },
    'delete_combo_alert': { newTool: 'alerts_manager', injectedParams: { action: 'delete', type: 'combo' } },
    'check_combo_alerts': { newTool: 'alerts_manager', injectedParams: { action: 'check', type: 'combo' } },
    'get_combo_presets': { newTool: 'alerts_manager', injectedParams: { action: 'presets', type: 'combo' } },

    // SENTIMENT
    'analyze_social_sentiment': { newTool: 'sentiment_manager', injectedParams: { action: 'analyze', type: 'social' } },
    'detect_events': { newTool: 'sentiment_manager', injectedParams: { action: 'analyze', type: 'events' } },
    'get_fear_greed_index': { newTool: 'calculate_fear_greed_index' },
    'get_market_sentiment': { newTool: 'sentiment_manager', injectedParams: { action: 'analyze', type: 'market' } },
    'get_news_sentiment': { newTool: 'sentiment_manager', injectedParams: { action: 'analyze', type: 'news' } },
    'get_stock_news': { newTool: 'sentiment_manager', injectedParams: { action: 'news_list' } },
    'get_stock_sentiment': { newTool: 'analyze_stock_sentiment' },
    'institutional_sentiment': { newTool: 'sentiment_manager', injectedParams: { action: 'analyze', type: 'institutional' } },
    'market_sentiment_index': { newTool: 'sentiment_manager', injectedParams: { action: 'analyze', type: 'market_index' } },
    'sentiment_divergence': { newTool: 'sentiment_manager', injectedParams: { action: 'analyze', type: 'divergence' } },
    'track_sentiment_momentum': { newTool: 'sentiment_manager', injectedParams: { action: 'analyze', type: 'momentum' } },

    // MARKET_INSIGHT
    'analyze_auction_stock': { newTool: 'market_insight_manager', injectedParams: { action: 'auction_analysis' } },
    'analyze_chain_impact': { newTool: 'industry_chain_manager', injectedParams: { action: 'impact' } },
    'analyze_insider_activity': { newTool: 'market_insight_manager', injectedParams: { action: 'insider_activity' } },
    'detect_opportunities': { newTool: 'market_insight_manager', injectedParams: { action: 'opportunities' } },
    'detect_risks': { newTool: 'market_insight_manager', injectedParams: { action: 'risks' } },
    'get_auction_ranking': { newTool: 'market_insight_manager', injectedParams: { action: 'auction_ranking' } },
    'get_chain_structure': { newTool: 'industry_chain_manager', injectedParams: { action: 'structure' } },
    'get_daily_limit_up_basic': { newTool: 'limit_up_manager', injectedParams: { action: 'daily_basic' } },
    'get_dragon_tiger': { newTool: 'market_insight_manager', injectedParams: { action: 'dragon_tiger' } },
    'get_economic_calendar': { newTool: 'event_manager', injectedParams: { action: 'calendar', type: 'economic' } },
    'get_industry_chains': { newTool: 'industry_chain_manager', injectedParams: { action: 'get_chains' } },
    'get_institutional_holders': { newTool: 'market_insight_manager', injectedParams: { action: 'institutional_holders' } },
    'get_limit_up_statistics_basic': { newTool: 'limit_up_manager', injectedParams: { action: 'statistics_basic' } },
    'get_macro_indicator': { newTool: 'macro_manager', injectedParams: { action: 'indicator' } },
    'get_stock_chain_position': { newTool: 'industry_chain_manager', injectedParams: { action: 'position' } },
    'predict_continuation_basic': { newTool: 'limit_up_manager', injectedParams: { action: 'prediction_basic' } },
    'search_chain_keyword': { newTool: 'industry_chain_manager', injectedParams: { action: 'search' } },
    'search_macro_indicators': { newTool: 'macro_manager', injectedParams: { action: 'search' } },

    // TRADING_DATA
    'get_abnormal_block_trade': { newTool: 'trading_data_manager', injectedParams: { action: 'abnormal_block_trade' } },
    'get_daily_block_trade': { newTool: 'trading_data_manager', injectedParams: { action: 'daily_block_trade' } },
    'get_margin_ranking': { newTool: 'trading_data_manager', injectedParams: { action: 'margin_ranking' } },
    'get_market_margin': { newTool: 'trading_data_manager', injectedParams: { action: 'market_margin' } },
    'get_north_fund_flow': { newTool: 'get_north_fund' }, // 修正：指向正确的 AKShare MCP 工具
    'get_north_fund_holding': { newTool: 'trading_data_manager', injectedParams: { action: 'north_fund_holding' } },
    'get_north_fund_top': { newTool: 'trading_data_manager', injectedParams: { action: 'north_fund_top' } },
    'get_stock_block_trade': { newTool: 'trading_data_manager', injectedParams: { action: 'stock_block_trade' } },
    'get_stock_margin': { newTool: 'trading_data_manager', injectedParams: { action: 'stock_margin' } },
    'get_realtime_quotes': { newTool: 'get_batch_quotes' }, // 添加：向后兼容别名

    // SECTOR_ROTATION
    'analyze_sector_rotation': { newTool: 'sector_manager', injectedParams: { action: 'rotation' } },
    'get_sector_fund_flow': { newTool: 'sector_manager', injectedParams: { action: 'fund_flow' } },
    'get_sector_realtime': { newTool: 'sector_manager', injectedParams: { action: 'realtime' } },
    'get_sector_stocks': { newTool: 'sector_manager', injectedParams: { action: 'stocks' } },
    'industry_prosperity': { newTool: 'sector_manager', injectedParams: { action: 'prosperity' } },

    // LIMIT_UP
    'analyze_limit_up_reason': { newTool: 'limit_up_manager', injectedParams: { action: 'reason' } },
    'get_daily_limit_up': { newTool: 'limit_up_manager', injectedParams: { action: 'daily' } },
    'get_hot_concepts': { newTool: 'limit_up_manager', injectedParams: { action: 'concepts' } },
    'get_limit_up_statistics': { newTool: 'limit_up_manager', injectedParams: { action: 'statistics' } },
    'predict_continuation': { newTool: 'limit_up_manager', injectedParams: { action: 'prediction' } },

    // PORTFOLIO
    'add_position': { newTool: 'portfolio_manager', injectedParams: { action: 'positions_add' } },
    'add_trade_record': { newTool: 'portfolio_manager', injectedParams: { action: 'trade_record_add' } },
    'analyze_pnl_trend': { newTool: 'performance_manager', injectedParams: { action: 'pnl_trend' } },
    'analyze_trading_attribution': { newTool: 'portfolio_manager', injectedParams: { action: 'attribution', type: 'trading' } },
    'brinson_attribution': { newTool: 'portfolio_manager', injectedParams: { action: 'attribution', type: 'brinson' } },
    'cancel_live_order': { newTool: 'live_trading_manager', injectedParams: { action: 'cancel' } },
    'check_compliance': { newTool: 'compliance_manager', injectedParams: { action: 'check' } },
    'create_paper_account': { newTool: 'paper_trading_manager', injectedParams: { action: 'create_account' } },
    'estimate_impact_cost': { newTool: 'execution_manager', injectedParams: { action: 'impact_cost' } },
    'estimate_market_impact': { newTool: 'execution_manager', injectedParams: { action: 'market_impact' } },
    'evaluate_execution_quality': { newTool: 'execution_manager', injectedParams: { action: 'evaluate_quality' } },
    'factor_attribution': { newTool: 'portfolio_manager', injectedParams: { action: 'attribution', type: 'factor' } },
    'generate_execution_schedule': { newTool: 'execution_manager', injectedParams: { action: 'execution_schedule' } },
    'generate_portfolio_report': { newTool: 'comprehensive_manager', injectedParams: { action: 'portfolio_report' } },
    'get_live_account': { newTool: 'live_trading_manager', injectedParams: { action: 'account' } },
    'get_live_orders': { newTool: 'live_trading_manager', injectedParams: { action: 'orders' } },
    'get_live_positions': { newTool: 'live_trading_manager', injectedParams: { action: 'positions' } },
    'get_paper_account': { newTool: 'paper_trading_manager', injectedParams: { action: 'get_account' } },
    'get_pnl_history': { newTool: 'performance_manager', injectedParams: { action: 'pnl_history' } },
    'get_portfolio_risk': { newTool: 'risk_manager', injectedParams: { action: 'portfolio_risk' } },
    'get_portfolio_summary': { newTool: 'get_portfolio_summary' },
    'get_positions': { newTool: 'get_positions' },
    'get_trade_records': { newTool: 'portfolio_manager', injectedParams: { action: 'trade_record_get' } },
    'initialize_portfolio': { newTool: 'portfolio_manager', injectedParams: { action: 'initialize' } },
    'optimize_equal_weight': { newTool: 'portfolio_manager', injectedParams: { action: 'optimize', type: 'equal_weight' } },
    'optimize_mean_variance': { newTool: 'portfolio_manager', injectedParams: { action: 'optimize', type: 'mean_variance' } },
    'optimize_portfolio': { newTool: 'portfolio_manager', injectedParams: { action: 'optimize', type: 'general' } },
    'optimize_risk_parity': { newTool: 'portfolio_manager', injectedParams: { action: 'optimize', type: 'risk_parity' } },
    'paper_buy': { newTool: 'paper_trading_manager', injectedParams: { action: 'buy' } },
    'paper_sell': { newTool: 'paper_trading_manager', injectedParams: { action: 'sell' } },
    'place_live_order': { newTool: 'live_trading_manager', injectedParams: { action: 'place' } },
    'recommend_execution_strategy': { newTool: 'execution_manager', injectedParams: { action: 'recommend_strategy' } },
    'record_daily_pnl': { newTool: 'performance_manager', injectedParams: { action: 'daily_pnl_record' } },
    'remove_position': { newTool: 'portfolio_manager', injectedParams: { action: 'positions_remove' } },

    // BACKTEST
    'analyze_factor_performance': { newTool: 'quant_manager', injectedParams: { action: 'factor_performance' } },
    'backtest_custom_strategy': { newTool: 'backtest_manager', injectedParams: { action: 'custom_strategy' } },
    'backtest_event_strategy': { newTool: 'backtest_manager', injectedParams: { action: 'event_strategy' } },
    'backtest_factor': { newTool: 'quant_manager', injectedParams: { action: 'factor_backtest' } },
    'calculate_carhart_factors': { newTool: 'quant_manager', injectedParams: { action: 'carhart_factors' } },
    'calculate_factor_ic': { newTool: 'quant_manager', injectedParams: { action: 'factor_ic' } },
    'calculate_risk': { newTool: 'risk_manager', injectedParams: { action: 'calculate_risk' } },
    'create_multi_factor_model': { newTool: 'quant_manager', injectedParams: { action: 'multi_factor_model' } },
    'get_backtest_detail': { newTool: 'backtest_manager', injectedParams: { action: 'detail' } },
    'get_backtest_results': { newTool: 'get_backtest_results' },
    'get_backtest_strategies': { newTool: 'backtest_manager', injectedParams: { action: 'strategies' } },
    'get_backtest_templates': { newTool: 'backtest_manager', injectedParams: { action: 'templates' } },
    'get_china_a_factors': { newTool: 'quant_manager', injectedParams: { action: 'china_a_factors' } },
    'get_factor_library': { newTool: 'quant_manager', injectedParams: { action: 'factor_library' } },
    'get_ml_model_status': { newTool: 'quant_manager', injectedParams: { action: 'ml_model_status' } },
    'get_strategy_templates': { newTool: 'backtest_manager', injectedParams: { action: 'strategy_templates' } },
    'optimize_factor_weights': { newTool: 'quant_manager', injectedParams: { action: 'optimize_factor_weights' } },
    'optimize_portfolio_quant': { newTool: 'quant_manager', injectedParams: { action: 'optimize_portfolio_quant' } },
    'predict_ml_factor_score': { newTool: 'quant_manager', injectedParams: { action: 'predict' } },
    'render_backtest_chart': { newTool: 'backtest_manager', injectedParams: { action: 'render_chart' } },
    'run_custom_backtest': { newTool: 'backtest_manager', injectedParams: { action: 'custom_script' } },
    'run_simple_backtest': { newTool: 'run_simple_backtest' },
    'run_validated_backtest': { newTool: 'backtest_manager', injectedParams: { action: 'validated' } },
    'run_walk_forward_backtest': { newTool: 'backtest_manager', injectedParams: { action: 'walk_forward' } },
    'train_ml_factor_model': { newTool: 'quant_manager', injectedParams: { action: 'train' } },
    'validate_strategy': { newTool: 'backtest_manager', injectedParams: { action: 'validate' } },

    // SCREENER
    'get_chain_stocks': { newTool: 'industry_chain_manager', injectedParams: { action: 'chain_stocks' } },
    'get_query_suggestions': { newTool: 'screener_manager', injectedParams: { action: 'query_suggestions' } },
    'get_screening_strategies': { newTool: 'screener_manager', injectedParams: { action: 'strategies' } },
    'scan_bearish_patterns': { newTool: 'screener_manager', injectedParams: { action: 'scan_bearish' } },
    'scan_bullish_patterns': { newTool: 'screener_manager', injectedParams: { action: 'scan_bullish' } },
    'screen_by_pattern': { newTool: 'screener_manager', injectedParams: { action: 'pattern' } },
    'screen_by_period_resonance': { newTool: 'screener_manager', injectedParams: { action: 'period_resonance' } },
    'screen_stocks': { newTool: 'parse_selection_query' }, // Map to NLP query for now or search
    'screen_stocks_advanced': { newTool: 'screener_manager', injectedParams: { action: 'advanced' } },
    'screen_technical_resonance': { newTool: 'screener_manager', injectedParams: { action: 'technical_resonance' } },
    'search_by_query_enhanced': { newTool: 'screener_manager', injectedParams: { action: 'search_query' } },

    // RESEARCH
    'analyze_carhart_four_factor': { newTool: 'quant_manager', injectedParams: { action: 'carhart_four_factor' } },
    'analyze_report': { newTool: 'research_manager', injectedParams: { action: 'analyze' } },
    'compare_reports': { newTool: 'research_manager', injectedParams: { action: 'compare' } },
    'extract_report_opinions': { newTool: 'research_manager', injectedParams: { action: 'extract' } },
    'generate_hot_topic_report': { newTool: 'research_manager', injectedParams: { action: 'hot_topic' } },
    'get_recent_research': { newTool: 'research_manager', injectedParams: { action: 'recent' } },
    'get_research_summary': { newTool: 'research_manager', injectedParams: { action: 'summary' } },
    'get_stock_research': { newTool: 'research_manager', injectedParams: { action: 'by_stock' } },
    'search_research': { newTool: 'research_manager', injectedParams: { action: 'search' } },
    'summarize_industry_reports': { newTool: 'research_manager', injectedParams: { action: 'industry' } },
    'summarize_research_report': { newTool: 'research_manager', injectedParams: { action: 'summarize' } },

    // RISK_MONITOR
    'analyze_portfolio_risk': { newTool: 'risk_manager', injectedParams: { action: 'portfolio_risk' } },
    'analyze_scenarios': { newTool: 'risk_manager', injectedParams: { action: 'scenario' } },
    'calculate_cvar': { newTool: 'risk_manager', injectedParams: { action: 'cvar' } },
    'get_risk_alerts': { newTool: 'risk_manager', injectedParams: { action: 'alerts' } },
    'get_var': { newTool: 'risk_manager', injectedParams: { action: 'var' } },
    'monitor_drawdown': { newTool: 'risk_manager', injectedParams: { action: 'drawdown' } },
    'risk_budget': { newTool: 'risk_manager', injectedParams: { action: 'risk_budget' } },
    'stress_test': { newTool: 'risk_manager', injectedParams: { action: 'stress_test' } },

    // INSIGHT
    'analyze_data_sensitivity': { newTool: 'insight_manager', injectedParams: { action: 'data_sensitivity' } },
    'analyze_event_impact': { newTool: 'event_manager', injectedParams: { action: 'analyze_impact' } },
    'analyze_macro_impact': { newTool: 'macro_manager', injectedParams: { action: 'impact' } },
    'analyze_news_impact': { newTool: 'sentiment_manager', injectedParams: { action: 'news_impact' } },
    'analyze_option_strategy': { newTool: 'options_manager', injectedParams: { action: 'strategy' } },
    'analyze_paper_performance': { newTool: 'paper_trading_manager', injectedParams: { action: 'analyze' } },
    'analyze_trades': { newTool: 'insight_manager', injectedParams: { action: 'analyze_trades' } },
    'check_data_quality': { newTool: 'data_sync_manager', injectedParams: { action: 'quality_check' } },
    'check_data_source_health': { newTool: 'data_sync_manager', injectedParams: { action: 'source_health' } },
    'detect_anomalies': { newTool: 'insight_manager', injectedParams: { action: 'detect_anomalies' } },
    'detect_cross_data_signals': { newTool: 'insight_manager', injectedParams: { action: 'cross_signals' } },
    'evaluate_trade': { newTool: 'insight_manager', injectedParams: { action: 'evaluate_trade' } },
    'generate_daily_insight': { newTool: 'insight_manager', injectedParams: { action: 'daily_insight' } },
    'generate_smart_insight': { newTool: 'insight_manager', injectedParams: { action: 'smart_insight' } },
    'get_anomaly_types': { newTool: 'insight_manager', injectedParams: { action: 'anomaly_types' } },
    'get_event_calendar': { newTool: 'event_manager', injectedParams: { action: 'calendar', type: 'market' } },
    'get_industry_trends': { newTool: 'sector_manager', injectedParams: { action: 'industry_trends' } },
    'get_market_overview': { newTool: 'insight_manager', injectedParams: { action: 'market_overview' } },
    'get_realtime_anomalies': { newTool: 'insight_manager', injectedParams: { action: 'realtime_anomalies' } },
    'get_stock_anomalies': { newTool: 'insight_manager', injectedParams: { action: 'stock_anomalies' } },
    'get_strategy_suggestions': { newTool: 'decision_manager', injectedParams: { action: 'strategy_suggestions' } },
    'get_trading_opportunities': { newTool: 'insight_manager', injectedParams: { action: 'trading_opportunities' } },
    'scan_market_anomalies': { newTool: 'insight_manager', injectedParams: { action: 'scan_market_anomalies' } },
    'scan_market_anomalies_batch': { newTool: 'insight_manager', injectedParams: { action: 'scan_market_anomalies_batch' } },
    'search_stock_news_realtime': { newTool: 'insight_manager', injectedParams: { action: 'news_search' } },
    'smart_monitor_stocks': { newTool: 'insight_manager', injectedParams: { action: 'smart_monitor' } },
    'track_policy_changes': { newTool: 'macro_manager', injectedParams: { action: 'policy' } },

    // DECISION
    'analyze_ai_accuracy': { newTool: 'decision_manager', injectedParams: { action: 'ai_accuracy' } },
    'clear_behavior_history': { newTool: 'user_manager', injectedParams: { action: 'behavior_clear' } },
    'compare_buy_options': { newTool: 'decision_manager', injectedParams: { action: 'compare_options' } },
    'compare_with_benchmark': { newTool: 'performance_manager', injectedParams: { action: 'benchmark_compare' } },
    'create_user_profile': { newTool: 'user_manager', injectedParams: { action: 'create_profile' } },
    'get_behavior_history': { newTool: 'user_manager', injectedParams: { action: 'behavior_history' } },
    'get_behavior_summary': { newTool: 'user_manager', injectedParams: { action: 'behavior_summary' } },
    'get_decision_context': { newTool: 'decision_manager', injectedParams: { action: 'context' } },
    'get_decision_history': { newTool: 'decision_manager', injectedParams: { action: 'history' } },
    'get_investment_preferences': { newTool: 'user_manager', injectedParams: { action: 'get_preferences' } },
    'get_performance_metrics': { newTool: 'performance_manager', injectedParams: { action: 'performance_metrics' } },
    'get_position_advice': { newTool: 'decision_manager', injectedParams: { action: 'position_advice' } },
    'get_risk_questions': { newTool: 'user_manager', injectedParams: { action: 'risk_questions' } },
    'get_timing_analysis': { newTool: 'performance_manager', injectedParams: { action: 'timing_analysis' } },
    'get_trading_statistics': { newTool: 'performance_manager', injectedParams: { action: 'trading_statistics' } },
    'get_user_profile': { newTool: 'user_manager', injectedParams: { action: 'get_profile' } },
    'query_strategy_assistant': { newTool: 'decision_manager', injectedParams: { action: 'strategy_assistant' } },
    'record_decision': { newTool: 'decision_manager', injectedParams: { action: 'record' } },
    'set_alert_preferences': { newTool: 'user_manager', injectedParams: { action: 'set_alert_preferences' } },
    'set_investment_preferences': { newTool: 'user_manager', injectedParams: { action: 'set_preferences' } },
    'should_i_buy': { newTool: 'should_i_buy' },
    'should_i_sell': { newTool: 'should_i_sell' },
    'submit_risk_assessment': { newTool: 'user_manager', injectedParams: { action: 'submit_risk_assessment' } },
    'track_behavior_event': { newTool: 'user_manager', injectedParams: { action: 'track_behavior' } },
    'update_user_profile': { newTool: 'user_manager', injectedParams: { action: 'update_profile' } },

    // VECTOR_SEARCH
    'find_pattern_matches': { newTool: 'vector_search_manager', injectedParams: { action: 'pattern_matches' } },
    'get_rag_context': { newTool: 'vector_search_manager', injectedParams: { action: 'rag_context' } },
    'search_by_query': { newTool: 'search_stocks' },
    'search_knowledge_base': { newTool: 'vector_search_manager', injectedParams: { action: 'knowledge_base' } },
    'search_market_events': { newTool: 'vector_search_manager', injectedParams: { action: 'market_events' } },
    'search_similar_by_kline': { newTool: 'vector_search_manager', injectedParams: { action: 'kline_similarity' } },
    'search_similar_stocks': { newTool: 'vector_search_manager', injectedParams: { action: 'similar_stocks' } },

    // COMPREHENSIVE
    'comprehensive_stock_analysis': { newTool: 'comprehensive_manager', injectedParams: { action: 'stock_analysis' } },
    'generate_analysis_report': { newTool: 'comprehensive_manager', injectedParams: { action: 'analysis_report' } },
    'get_market_report': { newTool: 'comprehensive_manager', injectedParams: { action: 'market_report' } },
    'perform_deep_analysis': { newTool: 'comprehensive_manager', injectedParams: { action: 'deep_analysis' } },
    'perform_deep_research': { newTool: 'comprehensive_manager', injectedParams: { action: 'deep_research' } },

    // WATCHLIST
    'add_to_watchlist': { newTool: 'watchlist_manager', injectedParams: { action: 'add' } },
    'get_watchlist': { newTool: 'watchlist_manager', injectedParams: { action: 'get' } },
    'get_watchlist_groups': { newTool: 'watchlist_manager', injectedParams: { action: 'groups' } },
    'remove_from_watchlist': { newTool: 'watchlist_manager', injectedParams: { action: 'remove' } },
};
