#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Complete Strategy Factory runtime:
# - Strategy Factory generates and submits prediction contracts.
# - Factor Mining Factory keeps factor/catalog context available.
# - Incubation Factory computes prediction outcomes, score summaries, and
#   matrices after market data is available.
# - Market Event Ingest refreshes official notice-first normalized anchors.
#
# Safety defaults keep live trading writes off while enabling production quality controls.
# Operators can still override these from the shell before invoking this script.
export PYTHONIOENCODING="${PYTHONIOENCODING:-utf-8}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"

export FACTOR_MINING_FACTORY_ENABLED="${FACTOR_MINING_FACTORY_ENABLED:-1}"
export STRATEGY_FACTORY_FACTOR_CATALOG_ENABLED="${STRATEGY_FACTORY_FACTOR_CATALOG_ENABLED:-1}"
export INCUBATION_FACTORY_OWNS_PAPER_TRADING="${INCUBATION_FACTORY_OWNS_PAPER_TRADING:-true}"
export INCUBATION_FACTORY_PAPER_INTAKE_ENABLED="${INCUBATION_FACTORY_PAPER_INTAKE_ENABLED:-1}"
export INCUBATION_FACTORY_PAPER_INTAKE_BATCH_LIMIT="${INCUBATION_FACTORY_PAPER_INTAKE_BATCH_LIMIT:-300}"
export STRATEGY_FACTORY_FACTOR_IC_GENERIC_INTAKE_ENABLED="${STRATEGY_FACTORY_FACTOR_IC_GENERIC_INTAKE_ENABLED:-1}"
export STRATEGY_FACTORY_EVENT_RUNTIME_MODE="${STRATEGY_FACTORY_EVENT_RUNTIME_MODE:-refresh}"

export STRATEGY_FACTORY_EXECUTION_MODE="stock_first_observe_primary"
export STRATEGY_FACTORY_OBSERVE_FIRST_ENABLED="1"
export STRATEGY_FACTORY_WIDE_INTAKE_OBSERVE_ENABLED="1"
export STRATEGY_FACTORY_INLINE_EXECUTION_ENABLED="${STRATEGY_FACTORY_INLINE_EXECUTION_ENABLED:-1}"
export STRATEGY_FACTORY_ALLOW_PARALLEL_FULL_CYCLES="${STRATEGY_FACTORY_ALLOW_PARALLEL_FULL_CYCLES:-1}"
export STRATEGY_FACTORY_MAX_CONCURRENT_DISPATCHES="${STRATEGY_FACTORY_MAX_CONCURRENT_DISPATCHES:-5}"
export STRATEGY_FACTORY_DISPATCH_SHARD_SIZE="${STRATEGY_FACTORY_DISPATCH_SHARD_SIZE:-1}"
export STRATEGY_FACTORY_DISPATCH_DEFAULT_UNIVERSE_ENABLED="${STRATEGY_FACTORY_DISPATCH_DEFAULT_UNIVERSE_ENABLED:-1}"
export STRATEGY_FACTORY_DISPATCH_DEFAULT_UNIVERSE_LIMIT="${STRATEGY_FACTORY_DISPATCH_DEFAULT_UNIVERSE_LIMIT:-${STRATEGY_FACTORY_MAX_CONCURRENT_DISPATCHES}}"

export STRATEGY_TRADE_PREDICTION_PROMOTION_GATE_ENABLED="${STRATEGY_TRADE_PREDICTION_PROMOTION_GATE_ENABLED:-1}"
export STRATEGY_TRADE_PREDICTION_BUDGET_FEEDBACK_ENABLED="${STRATEGY_TRADE_PREDICTION_BUDGET_FEEDBACK_ENABLED:-1}"
export STRATEGY_TRADE_PREDICTION_FACTOR_DECAY_ENABLED="${STRATEGY_TRADE_PREDICTION_FACTOR_DECAY_ENABLED:-1}"
export STRATEGY_FACTORY_MIN_VALIDATION_GRADE="${STRATEGY_FACTORY_MIN_VALIDATION_GRADE:-S}"

export LIVE_TRADING_ENABLED="${LIVE_TRADING_ENABLED:-0}"
export LIVE_TRADING_ALLOW_WRITE="${LIVE_TRADING_ALLOW_WRITE:-0}"
export BROKER_ALLOW_WRITE="${BROKER_ALLOW_WRITE:-0}"
export LIVE_TRADING_READ_ONLY="${LIVE_TRADING_READ_ONLY:-1}"
export BROKER_READ_ONLY="${BROKER_READ_ONLY:-1}"

if [[ -n "${AIASK_FACTORY_PYTHON:-}" ]]; then
  PYTHON_CMD=("${AIASK_FACTORY_PYTHON}")
elif [[ -x "/f/Python311/python.exe" ]]; then
  PYTHON_CMD=("/f/Python311/python.exe")
elif command -v python >/dev/null 2>&1; then
  PYTHON_CMD=("$(command -v python)")
elif command -v py >/dev/null 2>&1; then
  PYTHON_CMD=("py" "-3")
else
  echo "Python not found. Set AIASK_FACTORY_PYTHON or install Python." >&2
  exit 127
fi

cd "$ROOT"
echo "Starting complete AIASK Strategy Factory runtime..."
echo "  - strategy_factory: enabled"
echo "  - factor_mining_factory: enabled"
echo "  - incubation_factory: enabled"
echo "  - market_event_ingest: enabled unless --no-event-ingest or MARKET_EVENT_INGEST_ENABLED=0"
echo "  - incubation paper intake: enabled=${INCUBATION_FACTORY_PAPER_INTAKE_ENABLED}, batch_limit=${INCUBATION_FACTORY_PAPER_INTAKE_BATCH_LIMIT}"
echo "  - evidence-first: factor_ic_generic=${STRATEGY_FACTORY_FACTOR_IC_GENERIC_INTAKE_ENABLED}, event_runtime=${STRATEGY_FACTORY_EVENT_RUNTIME_MODE}"
echo "  - strategy mode: execution=${STRATEGY_FACTORY_EXECUTION_MODE}, observe_first=${STRATEGY_FACTORY_OBSERVE_FIRST_ENABLED}, wide_intake=${STRATEGY_FACTORY_WIDE_INTAKE_OBSERVE_ENABLED}"
echo "  - strategy dispatch: inline=${STRATEGY_FACTORY_INLINE_EXECUTION_ENABLED}, parallel_full_cycles=${STRATEGY_FACTORY_ALLOW_PARALLEL_FULL_CYCLES}, concurrency=${STRATEGY_FACTORY_MAX_CONCURRENT_DISPATCHES}, shard_size=${STRATEGY_FACTORY_DISPATCH_SHARD_SIZE}, default_universe=${STRATEGY_FACTORY_DISPATCH_DEFAULT_UNIVERSE_ENABLED}, default_universe_limit=${STRATEGY_FACTORY_DISPATCH_DEFAULT_UNIVERSE_LIMIT}"
echo "  - trade prediction hard controls: promotion=${STRATEGY_TRADE_PREDICTION_PROMOTION_GATE_ENABLED}, budget=${STRATEGY_TRADE_PREDICTION_BUDGET_FEEDBACK_ENABLED}, factor_decay=${STRATEGY_TRADE_PREDICTION_FACTOR_DECAY_ENABLED}"
echo "  - live trading writes: LIVE_TRADING_ENABLED=${LIVE_TRADING_ENABLED}, LIVE_TRADING_ALLOW_WRITE=${LIVE_TRADING_ALLOW_WRITE}, BROKER_ALLOW_WRITE=${BROKER_ALLOW_WRITE}"

STRATEGY_DISPATCH_ARGS=(
  --strategy-dispatch-run
  --strategy-parallel-full-cycles
  --strategy-dispatch-concurrency "${STRATEGY_FACTORY_MAX_CONCURRENT_DISPATCHES}"
  --strategy-dispatch-shard-size "${STRATEGY_FACTORY_DISPATCH_SHARD_SIZE}"
  --strategy-execution-mode "${STRATEGY_FACTORY_EXECUTION_MODE}"
)

if [[ "${STRATEGY_FACTORY_DISPATCH_DEFAULT_UNIVERSE_ENABLED}" == "1" ]]; then
  STRATEGY_DISPATCH_ARGS+=(
    --strategy-dispatch-default-universe
    --strategy-dispatch-default-universe-limit "${STRATEGY_FACTORY_DISPATCH_DEFAULT_UNIVERSE_LIMIT}"
  )
fi

exec "${PYTHON_CMD[@]}" "$ROOT/scripts/factories/run_three_factories.py" \
  "${STRATEGY_DISPATCH_ARGS[@]}" \
  "$@"
