import type { CopilotSurfaceModule, CopilotSurfaceRoute, CopilotTaskFlow } from './copilot-types';

export const COPILOT_PUBLIC_PAGE_KEYS = new Set(['login', 'register']);

export const COPILOT_SURFACE_MODULES: Array<{ module: CopilotSurfaceModule; title: string }> = [
  { module: 'market', title: '看盘' },
  { module: 'research', title: '研究' },
  { module: 'strategy', title: '策略' },
  { module: 'trade', title: '交易与复盘' },
  { module: 'ai', title: 'AI' },
  { module: 'workspace', title: '工作区' },
  { module: 'settings', title: '设置' },
  { module: 'admin', title: '管理后台' },
  { module: 'system', title: '系统' },
];

export const COPILOT_SURFACE_ROUTES: CopilotSurfaceRoute[] = [
  {
    pageKey: 'home',
    path: '/',
    module: 'market',
    title: '首页总览',
    summary: '系统总览、市场脉搏、风险提醒、自选状态和核心任务入口。',
    primaryGoal: '帮助用户从全局状态进入今天最值得处理的投研任务。',
    coreEntities: ['market_status', 'watchlist', 'risk_alert', 'workspace'],
    dataSources: ['dashboard', 'market', 'risk', 'watchlist'],
    capabilities: ['查看市场概览', '进入行情/研究/策略/交易链路', '打开工作区任务'],
    commonQuestions: ['今天先看什么', '系统有哪些模块', '下一步从哪里开始'],
    relatedPageKeys: ['market', 'watchlist', 'assistant', 'search'],
    aliases: ['首页', '总览', 'dashboard'],
  },
  {
    pageKey: 'market',
    path: '/market',
    module: 'market',
    title: '行情看板',
    summary: '围绕股票、指数、板块、分钟线、盘口、涨停和搜索结果组织实时看盘。',
    primaryGoal: '先锁定标的或市场范围，再决定进入个股、研究、技术、资金流或交易验证。',
    requiredInputs: ['stockCode?'],
    coreEntities: ['stock', 'index', 'block', 'quote', 'kline', 'order_book'],
    dataSources: ['market/quote', 'market/kline', 'market/order-book', 'market/blocks', 'market/index'],
    capabilities: ['查看实时行情', '切换行情 tab', '保存常用视图', '进入后续研究页'],
    commonQuestions: ['当前行情怎么看', '下一步该补哪些信息', '打开这只股票'],
    relatedPageKeys: ['stock', 'research', 'fundamental', 'technical', 'fund-flow', 'sentiment', 'paper-trading'],
    aliases: ['行情', '看盘', '市场', '实时行情', '行情看板'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'stock',
    path: '/stock',
    module: 'market',
    title: '个股详情',
    summary: '单只股票实时内容页，聚合报价、K线、盘口、资金流、基本面、估值、资讯和行动卡。',
    primaryGoal: '把单只股票从行情状态推进到可验证的研究和交易判断。',
    requiredInputs: ['stockCode'],
    coreEntities: ['stock', 'quote', 'kline', 'order_book', 'fund_flow', 'fundamental', 'valuation', 'news'],
    dataSources: ['market/quote', 'market/kline', 'fund-flow/stock', 'fundamental/overview', 'valuation/overview', 'research/stock-news'],
    capabilities: ['查看个股实时内容', '切换个股详情 tab', '进入研究/技术/资金流/模拟交易'],
    commonQuestions: ['这只股票现在是什么状态', '还缺哪些验证', '去基本面或模拟交易'],
    relatedPageKeys: ['market', 'fundamental', 'technical', 'fund-flow', 'sentiment', 'research', 'valuation', 'paper-trading'],
    aliases: ['个股', '股票详情', '详情页', '实时内容页', '实时行情页'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'watchlist',
    path: '/watchlist',
    module: 'market',
    title: '自选股',
    summary: '管理长期观察池、分组、标的搜索和后续跳转。',
    primaryGoal: '把一次性浏览转成可持续跟踪的观察清单。',
    requiredInputs: ['stockCode?'],
    coreEntities: ['watchlist', 'stock', 'group'],
    dataSources: ['watchlist', 'market/search'],
    capabilities: ['添加自选', '管理分组', '跳转行情/研究/交易'],
    commonQuestions: ['怎么加入自选', '自选股下一步看什么'],
    relatedPageKeys: ['market', 'stock', 'research', 'alerts'],
    aliases: ['自选', '观察池', 'watchlist'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'research',
    path: '/research',
    module: 'research',
    title: '研报公告',
    summary: '聚合研报、公告、资讯和个股新闻，补充行情背后的原因。',
    primaryGoal: '从行情现象进入信息验证，识别利好、利空、事件和研究线索。',
    requiredInputs: ['stockCode?'],
    coreEntities: ['stock', 'news', 'announcement', 'research_report'],
    dataSources: ['research/reports', 'research/announcements', 'research/stock-news'],
    capabilities: ['查看研报公告', '搜索资讯', '进入基本面/估值/情绪验证'],
    commonQuestions: ['这只股票有什么新闻', '研报公告怎么看', '下一步验证什么'],
    relatedPageKeys: ['fundamental', 'valuation', 'sentiment', 'stock', 'assistant'],
    aliases: ['研究', '研报', '公告', '资讯'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'fundamental',
    path: '/fundamental',
    module: 'research',
    title: '基本面',
    summary: '查看财务指标、估值、F10、财务快照和历史财务趋势。',
    primaryGoal: '验证股票基本面质量和估值位置。',
    requiredInputs: ['stockCode'],
    coreEntities: ['stock', 'financials', 'valuation', 'f10'],
    dataSources: ['fundamental/overview', 'fundamental/history', 'fundamental/f10'],
    capabilities: ['查看基本面概览', '切换财务资料', '导出数据', '进入估值/技术/交易'],
    commonQuestions: ['基本面强弱如何', '估值贵不贵', '去模拟交易页'],
    relatedPageKeys: ['valuation', 'technical', 'research', 'paper-trading', 'assistant'],
    aliases: ['基本面', '财务', 'F10', '基本信息'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'technical',
    path: '/technical',
    module: 'research',
    title: '技术分析',
    summary: '技术指标、形态识别、K线结构和交易信号验证。',
    primaryGoal: '用指标和形态确认交易结构与风险位置。',
    requiredInputs: ['stockCode'],
    coreEntities: ['stock', 'indicator', 'pattern', 'kline'],
    dataSources: ['technical/indicators', 'technical/patterns', 'market/kline'],
    capabilities: ['运行技术指标', '识别形态', '进入资金流/模拟交易'],
    commonQuestions: ['技术面怎么看', '有没有买卖信号', '下一步去哪里'],
    relatedPageKeys: ['fund-flow', 'sentiment', 'paper-trading', 'stock'],
    aliases: ['技术', '技术面', '指标', '形态', 'K线'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'fund-flow',
    path: '/fund-flow',
    module: 'research',
    title: '资金流向',
    summary: '查看个股、行业、概念和市场资金流入流出。',
    primaryGoal: '确认资金是否支持当前行情和交易判断。',
    requiredInputs: ['stockCode?'],
    coreEntities: ['stock', 'fund_flow', 'sector'],
    dataSources: ['fund-flow/stock', 'fund-flow/market', 'fund-flow/sector'],
    capabilities: ['查看资金流', '切换资金维度', '进入情绪/交易验证'],
    commonQuestions: ['资金流是否配合', '主力净流入如何'],
    relatedPageKeys: ['technical', 'sentiment', 'paper-trading', 'stock'],
    aliases: ['资金', '资金流', '主力资金'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'sentiment',
    path: '/sentiment',
    module: 'research',
    title: '情绪分析',
    summary: '查看市场和个股情绪、热度与辅助判断指标。',
    primaryGoal: '识别情绪热度和拥挤风险，避免只看价格。',
    requiredInputs: ['stockCode?'],
    coreEntities: ['stock', 'sentiment', 'hotspot'],
    dataSources: ['sentiment/stock', 'sentiment/market'],
    capabilities: ['查看情绪分数', '进入研究或交易复核'],
    commonQuestions: ['市场情绪怎么样', '这只股票热度如何'],
    relatedPageKeys: ['research', 'fund-flow', 'paper-trading'],
    aliases: ['情绪', '热度', '舆情'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'valuation',
    path: '/valuation',
    module: 'research',
    title: '估值分析',
    summary: '查看估值概览、估值区间、预测和相对估值信息。',
    primaryGoal: '判断估值位置是否支持继续研究或交易。',
    requiredInputs: ['stockCode'],
    coreEntities: ['stock', 'valuation', 'forecast'],
    dataSources: ['valuation/overview', 'fundamental/overview'],
    capabilities: ['查看估值', '进入基本面/模拟交易'],
    commonQuestions: ['估值贵不贵', '估值和基本面是否匹配'],
    relatedPageKeys: ['fundamental', 'research', 'paper-trading'],
    aliases: ['估值', 'PE', 'PB', '市盈率'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'macro',
    path: '/macro',
    module: 'research',
    title: '宏观数据',
    summary: '查看宏观指标和市场环境，用于自上而下判断。',
    primaryGoal: '补充宏观环境和周期背景。',
    coreEntities: ['macro_indicator', 'cycle'],
    dataSources: ['macro'],
    capabilities: ['查看宏观指标', '进入策略或研究页'],
    commonQuestions: ['宏观环境如何', '周期位置怎么看'],
    relatedPageKeys: ['strategy-market', 'research'],
    aliases: ['宏观', '经济数据'],
  },
  {
    pageKey: 'options',
    path: '/options',
    module: 'research',
    title: '期权分析',
    summary: '查看期权链、波动率和期权辅助指标。',
    primaryGoal: '用衍生品视角辅助判断风险和市场预期。',
    requiredInputs: ['stockCode?'],
    coreEntities: ['option', 'volatility', 'underlying'],
    dataSources: ['options'],
    capabilities: ['查看期权链', '分析波动率'],
    commonQuestions: ['期权市场怎么看', '波动率有什么信号'],
    relatedPageKeys: ['risk', 'technical'],
    aliases: ['期权', '波动率'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'strategy-market',
    path: '/strategy-market',
    module: 'strategy',
    title: '策略超市',
    summary: '筛选、收藏、复制、评估和进入策略详情、个人策略与工厂运行态。',
    primaryGoal: '从标的判断扩展到方法判断，选择可验证的策略。',
    coreEntities: ['strategy', 'personal_strategy', 'favorite', 'factory_run'],
    dataSources: ['strategy-market', 'strategy-capability'],
    capabilities: ['筛选策略', '收藏策略', '复制个人策略', '进入策略详情'],
    commonQuestions: ['有哪些策略适合当前标的', '怎么验证策略', '进入我的策略'],
    relatedPageKeys: ['backtest', 'factor-analysis', 'paper-trading', 'portfolio'],
    aliases: ['策略超市', '策略市场', '市场策略', '我的策略', '收藏策略'],
  },
  {
    pageKey: 'strategy-detail',
    path: '/strategy-market/[id]',
    module: 'strategy',
    title: '策略详情',
    summary: '查看单个策略详情、个人策略草稿、权限和可写入动作。',
    primaryGoal: '理解策略参数、风险和是否允许 AI 生成或保存更新。',
    requiredInputs: ['strategyId'],
    coreEntities: ['strategy', 'personal_strategy', 'mutation_guard'],
    dataSources: ['strategy-market/detail'],
    capabilities: ['查看策略详情', '生成更新建议', '保存个人策略更新'],
    commonQuestions: ['这个策略如何优化', '是否能保存修改'],
    relatedPageKeys: ['strategy-market', 'backtest', 'paper-trading'],
    aliases: ['策略详情', '个人策略', '策略草稿'],
  },
  {
    pageKey: 'strategy-market-diagnostics',
    path: '/strategy-market/diagnostics',
    module: 'strategy',
    title: '策略诊断',
    summary: '策略超市诊断、能力检查和异常定位页面。',
    primaryGoal: '排查策略市场能力和数据状态。',
    coreEntities: ['strategy', 'diagnostics'],
    dataSources: ['strategy diagnostics'],
    capabilities: ['查看诊断结果', '进入策略超市'],
    commonQuestions: ['策略市场哪里异常', '能力检查结果如何'],
    relatedPageKeys: ['strategy-market', 'admin-tools'],
    aliases: ['策略诊断', '策略能力诊断'],
  },
  {
    pageKey: 'strategy',
    path: '/strategy',
    module: 'strategy',
    title: '策略工作台',
    summary: '策略配置、运行、组合候选和策略任务工作台。',
    primaryGoal: '围绕策略参数和执行结果组织工作。',
    coreEntities: ['strategy', 'parameter', 'run_result'],
    dataSources: ['strategy'],
    capabilities: ['运行策略', '查看结果', '进入回测'],
    commonQuestions: ['策略参数怎么配', '策略结果如何'],
    relatedPageKeys: ['strategy-market', 'backtest', 'portfolio'],
    aliases: ['策略工作台', '策略'],
  },
  {
    pageKey: 'backtest',
    path: '/backtest',
    module: 'strategy',
    title: '回测分析',
    summary: '设置回测参数、运行回测、比较结果和失败原因。',
    primaryGoal: '用历史验证策略或标的交易假设。',
    requiredInputs: ['stockCode?', 'strategyId?'],
    coreEntities: ['backtest', 'strategy', 'stock', 'metrics'],
    dataSources: ['backtest'],
    capabilities: ['运行回测', '查看回测指标', '进入组合或交易'],
    commonQuestions: ['回测表现如何', '策略是否值得模拟交易'],
    relatedPageKeys: ['strategy-market', 'factor-analysis', 'paper-trading', 'portfolio'],
    aliases: ['回测', '历史验证'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'factor-analysis',
    path: '/factor-analysis',
    module: 'strategy',
    title: '因子分析',
    summary: '因子检验、IC、分组回测和因子研究结果。',
    primaryGoal: '验证因子有效性并服务策略构建。',
    coreEntities: ['factor', 'ic', 'group_backtest'],
    dataSources: ['factor-analysis'],
    capabilities: ['运行因子分析', '查看因子表现'],
    commonQuestions: ['因子是否有效', '因子下一步怎么用'],
    relatedPageKeys: ['factor', 'backtest', 'strategy-market'],
    aliases: ['因子分析', '因子回测'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'factor',
    path: '/factor',
    module: 'strategy',
    title: '因子研究',
    summary: '因子计算、候选因子和因子研究工作台。',
    primaryGoal: '生成和管理因子研究素材。',
    coreEntities: ['factor', 'factor_candidate'],
    dataSources: ['factor'],
    capabilities: ['计算因子', '查看候选因子', '进入因子分析'],
    commonQuestions: ['有哪些候选因子', '如何验证这个因子'],
    relatedPageKeys: ['factor-analysis', 'strategy-market'],
    aliases: ['因子', '因子研究'],
  },
  {
    pageKey: 'screener',
    path: '/screener',
    module: 'strategy',
    title: '条件选股',
    summary: '按自然语言或条件筛选股票，生成候选池。',
    primaryGoal: '从条件出发筛出股票，再进入个股研究或策略验证。',
    coreEntities: ['stock', 'screen_result', 'condition'],
    dataSources: ['screener', 'search'],
    capabilities: ['运行选股', '打开候选股票', '注入 Copilot 追问'],
    commonQuestions: ['筛到哪些股票', '打开首选股票', '下一步验证什么'],
    relatedPageKeys: ['stock', 'fundamental', 'technical', 'search'],
    aliases: ['选股', '条件选股', '筛选股票'],
  },
  {
    pageKey: 'paper-trading',
    path: '/paper-trading',
    module: 'trade',
    title: '模拟交易',
    summary: '模拟账户、下单预览、委托、撤单和交易结果。',
    primaryGoal: '把研究判断转成可控的模拟交易动作。',
    requiredInputs: ['stockCode?'],
    coreEntities: ['paper_account', 'order', 'position', 'stock'],
    dataSources: ['paper-trading'],
    capabilities: ['模拟下单', '查看持仓', '撤单', '进入执行和风控复盘'],
    commonQuestions: ['怎么下模拟单', '当前仓位风险如何', '下一步复盘去哪'],
    relatedPageKeys: ['execution', 'risk', 'performance', 'portfolio'],
    aliases: ['模拟交易', '纸上交易', '下单', '交易页'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'portfolio',
    path: '/portfolio',
    module: 'trade',
    title: '组合管理',
    summary: '组合、持仓、收益、风险和配置管理。',
    primaryGoal: '把单笔判断放进组合层面管理。',
    coreEntities: ['portfolio', 'position', 'allocation'],
    dataSources: ['portfolio'],
    capabilities: ['查看组合', '调整配置', '进入风险或绩效'],
    commonQuestions: ['组合暴露如何', '仓位怎么调整'],
    relatedPageKeys: ['risk', 'performance', 'paper-trading'],
    aliases: ['组合', '持仓', '资产配置'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'risk',
    path: '/risk',
    module: 'trade',
    title: '风控中心',
    summary: 'VaR、压力测试、风险暴露和风险事件。',
    primaryGoal: '识别组合或交易动作的风险边界。',
    coreEntities: ['risk', 'var', 'stress_test', 'exposure'],
    dataSources: ['risk'],
    capabilities: ['查看风险指标', '压力测试', '进入绩效复盘'],
    commonQuestions: ['主要风险是什么', '仓位是否过高'],
    relatedPageKeys: ['portfolio', 'performance', 'alerts'],
    aliases: ['风控', '风险', '压力测试'],
  },
  {
    pageKey: 'execution',
    path: '/execution',
    module: 'trade',
    title: '执行中心',
    summary: '执行状态、回执、artifact 和后续风险/绩效复盘。',
    primaryGoal: '跟踪交易或策略执行链路是否完成并定位异常。',
    coreEntities: ['execution', 'artifact', 'receipt', 'order'],
    dataSources: ['execution'],
    capabilities: ['查看执行状态', '打开 artifact', '进入风险/绩效复盘'],
    commonQuestions: ['执行到哪一步了', '有什么失败回执'],
    relatedPageKeys: ['risk', 'performance', 'paper-trading'],
    aliases: ['执行', '执行中心', '回执'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'execution-artifact',
    path: '/execution/artifacts/[artifactId]',
    module: 'trade',
    title: '执行工件',
    summary: '查看单个执行 artifact 的内容和上下文。',
    primaryGoal: '定位执行输出、证据和异常细节。',
    requiredInputs: ['artifactId'],
    coreEntities: ['artifact', 'execution'],
    dataSources: ['execution/artifacts'],
    capabilities: ['查看 artifact', '返回执行中心'],
    commonQuestions: ['这个工件说明了什么', '执行失败原因是什么'],
    relatedPageKeys: ['execution', 'risk', 'performance'],
    aliases: ['执行工件', 'artifact', '工件详情'],
  },
  {
    pageKey: 'performance',
    path: '/performance',
    module: 'trade',
    title: '绩效分析',
    summary: '收益、归因、基准对比和复盘建议。',
    primaryGoal: '评价交易或组合结果，并决定下一轮优化。',
    coreEntities: ['performance', 'attribution', 'benchmark'],
    dataSources: ['performance'],
    capabilities: ['查看绩效', '收益归因', '进入风险或研究复盘'],
    commonQuestions: ['收益来自哪里', '哪里需要优化'],
    relatedPageKeys: ['risk', 'portfolio', 'research'],
    aliases: ['绩效', '归因', '复盘'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'alerts',
    path: '/alerts',
    module: 'trade',
    title: '告警管理',
    summary: '管理价格、风险、策略和系统告警。',
    primaryGoal: '把需要持续关注的条件变成提醒。',
    coreEntities: ['alert', 'stock', 'risk_event'],
    dataSources: ['alerts'],
    capabilities: ['查看告警', '创建或处理告警', '进入相关页面'],
    commonQuestions: ['有哪些活跃告警', '该处理哪个风险'],
    relatedPageKeys: ['watchlist', 'risk', 'notifications'],
    aliases: ['告警', '提醒', '预警'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'notifications',
    path: '/notifications',
    module: 'trade',
    title: '通知中心',
    summary: '查看系统通知、告警通知和任务通知。',
    primaryGoal: '集中处理需要用户关注的通知。',
    coreEntities: ['notification', 'alert'],
    dataSources: ['notifications'],
    capabilities: ['查看通知', '进入告警或任务来源'],
    commonQuestions: ['有哪些未读通知', '这些通知来自哪里'],
    relatedPageKeys: ['alerts', 'execution', 'workspace-templates'],
    aliases: ['通知', '消息'],
  },
  {
    pageKey: 'decision',
    path: '/decision',
    module: 'trade',
    title: '统一决策',
    summary: '统一决策结果、行动建议和证据汇总。',
    primaryGoal: '把多模块信号收敛成可执行的决策视图。',
    requiredInputs: ['stockCode?'],
    coreEntities: ['decision', 'stock', 'signal'],
    dataSources: ['assistant/unified-decision', 'decision'],
    capabilities: ['查看统一决策', '进入 AI 中心或交易验证'],
    commonQuestions: ['决策结论是什么', '证据是否充分'],
    relatedPageKeys: ['assistant', 'stock', 'paper-trading', 'risk'],
    aliases: ['统一决策', '决策'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'assistant',
    path: '/assistant',
    module: 'ai',
    title: 'AI 中心',
    summary: '运行统一决策、全方位体检、产业链穿透、盘后复盘等结构化 AI 任务。',
    primaryGoal: '先形成结构化 AI 结论，再决定展开详情、追问或跳转页面动作。',
    requiredInputs: ['stockCode?'],
    coreEntities: ['stock', 'assistant_task', 'result_contract', 'investment_style'],
    dataSources: ['assistant'],
    capabilities: ['运行 AI 任务', '加载统一决策详情', '注入 Copilot 追问'],
    commonQuestions: ['运行统一决策', '总结当前结果', '下一步怎么分析'],
    relatedPageKeys: ['stock', 'search', 'decision', 'paper-trading'],
    aliases: ['AI中心', 'AI 中心', '助手', '统一决策流水线'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'search',
    path: '/search',
    module: 'ai',
    title: '智能搜索',
    summary: '语义搜索、相似股票和 K 线结构搜索，用于生成候选标的。',
    primaryGoal: '从主题、相似公司或走势结构发现候选股票，再进入个股研究。',
    requiredInputs: ['query?', 'stockCode?'],
    coreEntities: ['stock', 'search_result', 'semantic_query'],
    dataSources: ['search/semantic', 'search/similar', 'search/vector-kline'],
    capabilities: ['运行搜索', '打开首选股票', '注入 Copilot 追问'],
    commonQuestions: ['总结当前搜索结果', '打开这支股票', '下一步怎么分析'],
    relatedPageKeys: ['stock', 'fundamental', 'technical', 'assistant', 'screener'],
    aliases: ['搜索', '智能搜索', '语义搜索', '相似股票', 'K线搜索'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'chat',
    path: '/chat',
    module: 'ai',
    title: 'AI 对话',
    summary: '通用 AI 对话页面。',
    primaryGoal: '进行不绑定特定页面的自由问答。',
    coreEntities: ['conversation'],
    dataSources: ['chat'],
    capabilities: ['自由问答', '配置或使用模型'],
    commonQuestions: ['帮我解释一个问题', '继续对话'],
    relatedPageKeys: ['assistant', 'settings'],
    aliases: ['AI对话', '聊天'],
  },
  {
    pageKey: 'skills',
    path: '/skills',
    module: 'ai',
    title: '技能中心',
    summary: '查看和触发投研技能、填充工作区上下文。',
    primaryGoal: '把技能能力和当前工作区上下文连接起来。',
    coreEntities: ['skill', 'workspace_context'],
    dataSources: ['skills'],
    capabilities: ['查看技能', '填充工作区上下文', '进入 AI 或研究页'],
    commonQuestions: ['有哪些技能', '当前工作区上下文是什么'],
    relatedPageKeys: ['assistant', 'workspace-templates', 'settings'],
    aliases: ['技能', '技能中心'],
  },
  {
    pageKey: 'analysis-deep-stock',
    path: '/analysis/deep-stock',
    module: 'ai',
    title: '个股深度分析',
    summary: '面向单只股票的深度分析工作流入口。',
    primaryGoal: '组织个股深度分析、证据和报告生成。',
    requiredInputs: ['stockCode'],
    coreEntities: ['stock', 'deep_analysis', 'report'],
    dataSources: ['analysis/deep-stock'],
    capabilities: ['运行深度分析', '查看报告线索'],
    commonQuestions: ['深度分析这只股票', '生成报告需要什么'],
    relatedPageKeys: ['stock', 'assistant', 'research'],
    aliases: ['深度分析', '个股深度分析'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'data',
    path: '/data',
    module: 'workspace',
    title: '数据中心',
    summary: '数据源、缓存、数据质量和基础数据入口。',
    primaryGoal: '查看数据链路状态和数据资源。',
    coreEntities: ['data_source', 'cache', 'quality'],
    dataSources: ['data'],
    capabilities: ['查看数据状态', '进入管理或研究页'],
    commonQuestions: ['数据是否可用', '数据质量如何'],
    relatedPageKeys: ['admin-cache', 'market', 'stock'],
    aliases: ['数据', '数据中心'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'events',
    path: '/events',
    module: 'workspace',
    title: '事件中心',
    summary: '市场事件、系统事件和投研事件管理。',
    primaryGoal: '追踪会影响标的、策略和执行的事件。',
    coreEntities: ['event', 'stock', 'strategy'],
    dataSources: ['events'],
    capabilities: ['查看事件', '进入研究或执行页'],
    commonQuestions: ['最近有什么事件', '这个事件影响哪些标的'],
    relatedPageKeys: ['research', 'execution', 'alerts'],
    aliases: ['事件', '事件中心'],
    stockAware: true,
    codeParam: 'code',
  },
  {
    pageKey: 'workspace-templates',
    path: '/workspace-templates',
    module: 'workspace',
    title: '工作区模板',
    summary: '工作区蓝图、任务模板和串行编排入口。',
    primaryGoal: '用模板快速创建投研工作区和任务链。',
    coreEntities: ['workspace', 'template', 'workflow', 'task'],
    dataSources: ['workspace templates'],
    capabilities: ['应用工作区模板', '预览任务模板', '回滚模板运行'],
    commonQuestions: ['如何创建研究工作区', '模板会生成哪些任务'],
    relatedPageKeys: ['home', 'assistant', 'skills'],
    aliases: ['工作区模板', '模板中心', '工作区'],
  },
  {
    pageKey: 'settings',
    path: '/settings',
    module: 'settings',
    title: '设置中心',
    summary: '账户、模型配置、偏好和系统设置。',
    primaryGoal: '配置用户账户、AI 模型和系统偏好。',
    coreEntities: ['user', 'llm_config', 'preference'],
    dataSources: ['settings', 'chat/config'],
    capabilities: ['配置模型', '查看账户设置', '进入安全设置'],
    commonQuestions: ['如何配置 LLM Key', '模型配置是否可用'],
    relatedPageKeys: ['settings-security', 'settings-audit-log', 'assistant'],
    aliases: ['设置', '模型配置', 'LLM配置'],
  },
  {
    pageKey: 'settings-security',
    path: '/settings/security',
    module: 'settings',
    title: '安全设置',
    summary: '账号安全、会话和安全配置。',
    primaryGoal: '管理账号安全和登录会话。',
    coreEntities: ['security', 'session', 'user'],
    dataSources: ['settings/security'],
    capabilities: ['查看安全状态', '管理会话'],
    commonQuestions: ['账号安全状态如何', '有哪些活跃会话'],
    relatedPageKeys: ['settings', 'settings-audit-log'],
    aliases: ['安全设置', '账号安全'],
  },
  {
    pageKey: 'settings-audit-log',
    path: '/settings/audit-log',
    module: 'settings',
    title: '审计日志',
    summary: '查看用户和系统审计日志。',
    primaryGoal: '追踪重要操作和安全事件。',
    coreEntities: ['audit_log', 'user', 'action'],
    dataSources: ['audit-log'],
    capabilities: ['筛选审计日志', '导出或定位操作'],
    commonQuestions: ['最近有哪些操作', '谁修改了配置'],
    relatedPageKeys: ['settings', 'admin'],
    aliases: ['审计', '审计日志'],
  },
  {
    pageKey: 'admin',
    path: '/admin',
    module: 'admin',
    title: '管理后台',
    summary: '系统管理后台入口。',
    primaryGoal: '进入管理员工具、用户、缓存和死信队列。',
    coreEntities: ['admin', 'system'],
    dataSources: ['admin'],
    capabilities: ['进入管理工具'],
    commonQuestions: ['管理后台有哪些工具'],
    relatedPageKeys: ['admin-tools', 'admin-cache', 'admin-users', 'admin-dead-letters'],
    aliases: ['管理后台', '后台'],
    adminOnly: true,
  },
  {
    pageKey: 'admin-tools',
    path: '/admin/tools',
    module: 'admin',
    title: 'MCP 工具',
    summary: '查看和管理 MCP 工具能力。',
    primaryGoal: '诊断工具注册和调用能力。',
    coreEntities: ['mcp_tool', 'admin'],
    dataSources: ['mcp'],
    capabilities: ['查看工具', '运行工具诊断'],
    commonQuestions: ['有哪些 MCP 工具', '工具是否可用'],
    relatedPageKeys: ['admin', 'skills'],
    aliases: ['MCP工具', '工具管理'],
    adminOnly: true,
  },
  {
    pageKey: 'admin-cache',
    path: '/admin/cache',
    module: 'admin',
    title: '缓存管理',
    summary: '查看和清理缓存状态。',
    primaryGoal: '管理服务端缓存和数据刷新。',
    coreEntities: ['cache', 'admin'],
    dataSources: ['cache'],
    capabilities: ['查看缓存', '清理缓存'],
    commonQuestions: ['缓存状态如何', '是否需要清理缓存'],
    relatedPageKeys: ['admin', 'data'],
    aliases: ['缓存', '缓存管理'],
    adminOnly: true,
  },
  {
    pageKey: 'admin-dead-letters',
    path: '/admin/dead-letters',
    module: 'admin',
    title: '死信队列',
    summary: '查看失败任务、死信消息和重试状态。',
    primaryGoal: '定位异步任务失败和重试问题。',
    coreEntities: ['dead_letter', 'job', 'error'],
    dataSources: ['dead-letters'],
    capabilities: ['查看死信', '重试或定位失败任务'],
    commonQuestions: ['有哪些失败任务', '失败原因是什么'],
    relatedPageKeys: ['admin', 'execution'],
    aliases: ['死信', '死信队列', '失败任务'],
    adminOnly: true,
  },
  {
    pageKey: 'admin-users',
    path: '/admin/users',
    module: 'admin',
    title: '用户管理',
    summary: '查看和管理用户、角色与权限。',
    primaryGoal: '管理用户账户和角色权限。',
    coreEntities: ['user', 'role', 'permission'],
    dataSources: ['users'],
    capabilities: ['查看用户', '管理角色'],
    commonQuestions: ['有哪些用户', '权限状态如何'],
    relatedPageKeys: ['admin', 'settings-audit-log'],
    aliases: ['用户管理', '用户', '权限'],
    adminOnly: true,
  },
  {
    pageKey: 'user',
    path: '/user',
    module: 'settings',
    title: '用户中心',
    summary: '用户资料、账户状态和个人入口。',
    primaryGoal: '查看和管理个人账户信息。',
    coreEntities: ['user', 'profile'],
    dataSources: ['user'],
    capabilities: ['查看用户资料', '进入设置'],
    commonQuestions: ['我的账户状态如何'],
    relatedPageKeys: ['settings', 'settings-security'],
    aliases: ['用户中心', '个人中心'],
  },
  {
    pageKey: 'login',
    path: '/login',
    module: 'system',
    title: '登录',
    summary: '公开登录页面，不进入 Copilot 业务理解。',
    primaryGoal: '登录系统。',
    public: true,
    aliases: ['登录'],
  },
  {
    pageKey: 'register',
    path: '/register',
    module: 'system',
    title: '注册',
    summary: '公开注册页面，不进入 Copilot 业务理解。',
    primaryGoal: '注册系统。',
    public: true,
    aliases: ['注册'],
  },
];

export const COPILOT_TASK_FLOWS: CopilotTaskFlow[] = [
  {
    id: 'stock-research-flow',
    title: '个股研究链路',
    summary: '从看盘锁定标的，到个股、研究、基本面、技术/资金流验证，再进入 AI 或模拟交易。',
    steps: [
      { pageKey: 'market', title: '看盘锁定标的', goal: '确认行情、K线和盘口状态。', requiredContext: ['stockCode'], nextPageKey: 'stock' },
      { pageKey: 'stock', title: '个股实时内容', goal: '汇总报价、K线、资金流、基本面、估值和资讯。', requiredContext: ['stockCode'], nextPageKey: 'research' },
      { pageKey: 'research', title: '研究信息验证', goal: '查看公告、研报、新闻和事件原因。', requiredContext: ['stockCode'], nextPageKey: 'fundamental' },
      { pageKey: 'fundamental', title: '基本面验证', goal: '验证财务质量和估值位置。', requiredContext: ['stockCode'], nextPageKey: 'technical' },
      { pageKey: 'technical', title: '交易结构确认', goal: '用技术指标和形态确认风险位置。', requiredContext: ['stockCode'], nextPageKey: 'paper-trading' },
      { pageKey: 'paper-trading', title: '模拟交易验证', goal: '把判断转为可控模拟动作。', requiredContext: ['stockCode'], nextPageKey: 'execution' },
    ],
  },
  {
    id: 'strategy-validation-flow',
    title: '策略验证链路',
    summary: '从策略超市筛选方法，到策略详情、回测、因子和模拟验证。',
    steps: [
      { pageKey: 'strategy-market', title: '筛选策略', goal: '找到符合目标的策略或个人策略。', nextPageKey: 'strategy-detail' },
      { pageKey: 'strategy-detail', title: '理解策略详情', goal: '查看参数、权限、风险和可写入动作。', requiredContext: ['strategyId'], nextPageKey: 'backtest' },
      { pageKey: 'backtest', title: '历史回测', goal: '用历史数据验证策略假设。', nextPageKey: 'factor-analysis' },
      { pageKey: 'factor-analysis', title: '因子验证', goal: '确认因子有效性和组合贡献。', nextPageKey: 'paper-trading' },
      { pageKey: 'paper-trading', title: '模拟执行', goal: '用模拟交易验证策略动作。', nextPageKey: 'performance' },
    ],
  },
  {
    id: 'trade-review-flow',
    title: '交易复盘链路',
    summary: '从模拟交易进入执行状态、组合、风险和绩效复盘。',
    steps: [
      { pageKey: 'paper-trading', title: '模拟交易动作', goal: '发起或检查模拟委托。', nextPageKey: 'execution' },
      { pageKey: 'execution', title: '执行跟踪', goal: '查看执行回执和 artifact。', nextPageKey: 'portfolio' },
      { pageKey: 'portfolio', title: '组合影响', goal: '观察持仓、配置和收益影响。', nextPageKey: 'risk' },
      { pageKey: 'risk', title: '风险复核', goal: '检查 VaR、压力测试和暴露。', nextPageKey: 'performance' },
      { pageKey: 'performance', title: '绩效归因', goal: '归因收益与亏损，形成下一轮优化。', nextPageKey: 'research' },
    ],
  },
];

export function getCopilotSurfaceByPageKey(pageKey: string | null | undefined) {
  if (!pageKey) return undefined;
  return COPILOT_SURFACE_ROUTES.find((route) => route.pageKey === pageKey);
}

export function getCopilotSurfaceByPath(pathname: string | null | undefined) {
  if (!pathname) return undefined;
  if (/^\/strategy-market\/[^/]+/.test(pathname)) return getCopilotSurfaceByPageKey('strategy-detail');
  if (/^\/execution\/artifacts\/[^/]+/.test(pathname)) return getCopilotSurfaceByPageKey('execution-artifact');
  const normalized = pathname === '/' ? '/' : pathname.replace(/\/$/, '');
  return COPILOT_SURFACE_ROUTES
    .filter((route) => !route.path.includes('['))
    .sort((left, right) => right.path.length - left.path.length)
    .find((route) => route.path === '/'
      ? normalized === '/'
      : normalized === route.path || normalized.startsWith(`${route.path}/`));
}

export function isCopilotRouteAllowedHref(href: string) {
  try {
    const url = new URL(href, 'http://aiask.local');
    return Boolean(getCopilotSurfaceByPath(url.pathname));
  } catch {
    return false;
  }
}

export function buildCopilotHref(route: CopilotSurfaceRoute, code?: string) {
  const path = route.path;
  if (path.includes('[')) return '';
  if (route.stockAware && code) {
    const url = new URL(path, 'http://aiask.local');
    url.searchParams.set(route.codeParam ?? 'code', code);
    return `${url.pathname}${url.search}`;
  }
  return path;
}
