"""Platform (analysis-layer) provider contracts (split from registry)."""

from __future__ import annotations

from typing import Any

from ._shared import *  # noqa: F401,F403 - shared builders/policies/models
from ._shared import _array_of, _contract, _schema  # explicit for clarity

def _platform_contracts() -> dict[str, dict[str, Any]]:
    code_props = {
        "code": {"type": ["string", "null"], "description": "6-digit security code."},
        "stock_code": {"type": ["string", "null"], "description": "Deprecated alias for code."},
        "symbol": {"type": ["string", "null"], "description": "Alias for code."},
        "ticker": {"type": ["string", "null"], "description": "Alias for code."},
    }
    specs: list[dict[str, Any]] = [
        {
            "name": "calculate_technical_indicators",
            "title": "Technical Indicators",
            "category": "technical",
            "standard_model": "TechnicalIndicators",
            "description": "Calculate technical indicators from existing DB-first kline data paths.",
            "required_params": ["code", "indicators"],
            "query_model": _schema(
                "TechnicalIndicatorsQuery",
                {
                    "code": {"type": "string"},
                    "indicators": {"type": "array", "items": {"type": "string"}},
                    "period": {"type": "string", "default": "daily"},
                    "limit": {"type": "integer", "minimum": 20, "maximum": 5000, "default": 250},
                },
                ["code", "indicators"],
            ),
            "freshness": _TECHNICAL_FRESHNESS,
            "source_policy": _TECHNICAL_SOURCE_POLICY,
            "examples": [{"description": "Calculate MA and RSI", "arguments": {"code": "600519", "indicators": ["MA", "RSI"], "limit": 250}}],
            "tags": ["provider-contract", "technical", "indicators"],
        },
        {
            "name": "check_candlestick_patterns",
            "title": "Candlestick Patterns",
            "category": "technical",
            "standard_model": "CandlestickPatterns",
            "description": "Detect candlestick patterns from the existing DB/kline fallback chain.",
            "required_params": ["code"],
            "query_model": _schema(
                "CandlestickPatternsQuery",
                {"code": {"type": "string"}, "period": {"type": "string", "default": "daily"}, "limit": {"type": "integer", "minimum": 20, "maximum": 1000, "default": 100}},
                ["code"],
            ),
            "freshness": _TECHNICAL_FRESHNESS,
            "source_policy": _TECHNICAL_SOURCE_POLICY,
            "examples": [{"description": "Check recent daily candlestick patterns", "arguments": {"code": "600519", "limit": 100}}],
            "tags": ["provider-contract", "technical", "patterns"],
        },
        {
            "name": "get_available_patterns",
            "title": "Available Patterns",
            "category": "technical",
            "standard_model": "PatternCatalog",
            "description": "List supported candlestick pattern identifiers.",
            "required_params": [],
            "query_model": _schema("PatternCatalogQuery"),
            "freshness": FreshnessPolicy(expectation="static_pattern_catalog"),
            "source_policy": SourcePolicy(priority=["pattern_recognition"]),
            "examples": [{"description": "List supported patterns", "arguments": {}}],
            "tags": ["provider-contract", "technical", "catalog"],
        },
        {
            "name": "run_simple_backtest",
            "title": "Simple Backtest",
            "category": "backtest",
            "standard_model": "SimpleBacktestResult",
            "description": "Run a read-only simple strategy backtest using historical kline inputs.",
            "required_params": ["code"],
            "query_model": _schema(
                "SimpleBacktestQuery",
                {**code_props, "strategy": {"type": "string"}, "initial_capital": {"type": "number"}, "start_date": {"type": "string"}, "end_date": {"type": "string"}},
                ["code"],
            ),
            "freshness": _BACKTEST_FRESHNESS,
            "source_policy": _BACKTEST_SOURCE_POLICY,
            "examples": [{"description": "Run a simple moving-average backtest", "arguments": {"code": "600519", "strategy": "ma_cross"}}],
            "tags": ["provider-contract", "backtest", "simulation"],
        },
        {
            "name": "run_batch_backtest",
            "title": "Batch Backtest",
            "category": "backtest",
            "standard_model": "BatchBacktestResult",
            "description": "Run read-only batch backtests across multiple securities.",
            "required_params": ["codes"],
            "query_model": _schema(
                "BatchBacktestQuery",
                {"codes": {"type": "array", "items": {"type": "string"}}, "strategy": {"type": "string"}, "initial_capital": {"type": "number"}, "start_date": {"type": "string"}, "end_date": {"type": "string"}},
                ["codes"],
            ),
            "freshness": _BACKTEST_FRESHNESS,
            "source_policy": _BACKTEST_SOURCE_POLICY,
            "examples": [{"description": "Run a batch backtest", "arguments": {"codes": ["600519", "000001"], "strategy": "ma_cross"}}],
            "tags": ["provider-contract", "backtest", "batch"],
        },
        {
            "name": "backtest_factor",
            "title": "Factor Backtest",
            "category": "backtest",
            "standard_model": "FactorBacktestResult",
            "description": "Backtest factor signals using existing quant data paths.",
            "required_params": ["factor_name"],
            "query_model": _schema(
                "FactorBacktestQuery",
                {"factor_name": {"type": "string"}, "codes": {"type": "array", "items": {"type": "string"}}, "start_date": {"type": "string"}, "end_date": {"type": "string"}},
                ["factor_name"],
            ),
            "freshness": _BACKTEST_FRESHNESS,
            "source_policy": _BACKTEST_SOURCE_POLICY,
            "examples": [{"description": "Backtest one factor", "arguments": {"factor_name": "momentum_20d", "codes": ["600519"]}}],
            "tags": ["provider-contract", "backtest", "factor"],
        },
        {
            "name": "run_factor_group_backtest",
            "title": "Factor Group Backtest",
            "category": "backtest",
            "standard_model": "FactorGroupBacktestResult",
            "description": "Run grouped factor backtests with PIT-compatible historical inputs.",
            "required_params": ["factor_name"],
            "query_model": _schema(
                "FactorGroupBacktestQuery",
                {"factor_name": {"type": "string"}, "codes": {"type": "array", "items": {"type": "string"}}, "groups": {"type": "integer"}, "start_date": {"type": "string"}, "end_date": {"type": "string"}},
                ["factor_name"],
            ),
            "freshness": _BACKTEST_FRESHNESS,
            "source_policy": _BACKTEST_SOURCE_POLICY,
            "examples": [{"description": "Run a five-group factor backtest", "arguments": {"factor_name": "momentum_20d", "groups": 5}}],
            "tags": ["provider-contract", "backtest", "factor", "grouped"],
        },
        {
            "name": "get_valuation_metrics",
            "title": "Valuation Metrics",
            "category": "valuation",
            "standard_model": "ValuationMetrics",
            "description": "Read PE/PB/market-cap valuation metrics from DB-first valuation sources.",
            "required_params": ["code"],
            "query_model": _schema("ValuationMetricsQuery", code_props, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Read valuation metrics", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "valuation", "fundamental"],
        },
        {
            "name": "dcf_valuation",
            "title": "DCF Valuation",
            "category": "valuation",
            "standard_model": "DCFValuation",
            "description": "Run DCF valuation using existing financial and market context fallbacks.",
            "required_params": ["code"],
            "query_model": _schema("DCFValuationQuery", {**code_props, "discount_rate": {"type": "number"}, "growth_rate": {"type": "number"}, "years": {"type": "integer", "minimum": 1, "maximum": 30}}, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Run DCF valuation", "arguments": {"code": "600519", "years": 5}}],
            "tags": ["provider-contract", "valuation", "dcf"],
        },
        {
            "name": "ddm_valuation",
            "title": "DDM Valuation",
            "category": "valuation",
            "standard_model": "DDMValuation",
            "description": "Run dividend discount valuation with existing financial fallbacks.",
            "required_params": ["code"],
            "query_model": _schema("DDMValuationQuery", {**code_props, "dividend": {"type": "number"}, "growth_rate": {"type": "number"}, "required_return": {"type": "number"}}, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Run DDM valuation", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "valuation", "ddm"],
        },
        {
            "name": "relative_valuation",
            "title": "Relative Valuation",
            "category": "valuation",
            "standard_model": "RelativeValuation",
            "description": "Run peer-relative valuation using existing valuation peer inputs.",
            "required_params": ["code"],
            "query_model": _schema("RelativeValuationQuery", {**code_props, "peer_codes": {"type": "array", "items": {"type": "string"}}, "metric": {"type": "string"}}, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Run relative valuation", "arguments": {"code": "600519", "metric": "pe"}}],
            "tags": ["provider-contract", "valuation", "relative"],
        },
        {
            "name": "get_historical_valuation",
            "title": "Historical Valuation",
            "category": "valuation",
            "standard_model": "HistoricalValuation",
            "description": "Read historical valuation series from existing valuation peer sources.",
            "required_params": ["code"],
            "query_model": _schema("HistoricalValuationQuery", {**code_props, "metric": {"type": "string"}, "limit": {"type": "integer", "minimum": 1, "maximum": 5000}}, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Read historical PE", "arguments": {"code": "600519", "metric": "pe", "limit": 240}}],
            "tags": ["provider-contract", "valuation", "history"],
        },
        {
            "name": "scenario_dcf_valuation",
            "title": "Scenario DCF Valuation",
            "category": "valuation",
            "standard_model": "ScenarioDCFValuation",
            "description": "Run scenario DCF valuation with existing financial context.",
            "required_params": ["code"],
            "query_model": _schema("ScenarioDCFValuationQuery", {**code_props, "scenarios": {"type": "array", "items": {"type": "object"}}, "years": {"type": "integer", "minimum": 1, "maximum": 30}}, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Run scenario DCF", "arguments": {"code": "600519", "years": 5}}],
            "tags": ["provider-contract", "valuation", "scenario"],
        },
        {
            "name": "optimize_portfolio",
            "title": "Optimize Portfolio",
            "category": "portfolio",
            "standard_model": "PortfolioOptimization",
            "description": "Run read-only portfolio optimization over input securities and recent returns.",
            "required_params": ["codes"],
            "query_model": _schema("PortfolioOptimizationQuery", {"codes": {"type": "array", "items": {"type": "string"}}, "method": {"type": "string"}, "risk_free_rate": {"type": "number"}}, ["codes"]),
            "freshness": _PORTFOLIO_FRESHNESS,
            "source_policy": _PORTFOLIO_SOURCE_POLICY,
            "examples": [{"description": "Optimize a two-stock portfolio", "arguments": {"codes": ["600519", "000001"]}}],
            "tags": ["provider-contract", "portfolio", "optimization"],
        },
        {
            "name": "analyze_portfolio_risk",
            "title": "Portfolio Risk",
            "category": "portfolio",
            "standard_model": "PortfolioRisk",
            "description": "Analyze portfolio VaR/exposure risk using existing holdings and kline data.",
            "required_params": ["codes", "weights"],
            "query_model": _schema("PortfolioRiskQuery", {"codes": {"type": "array", "items": {"type": "string"}}, "weights": {"type": "array", "items": {"type": "number"}}, "confidence": {"type": "number"}, "lookback_days": {"type": "integer"}}, ["codes", "weights"]),
            "freshness": _PORTFOLIO_FRESHNESS,
            "source_policy": _PORTFOLIO_SOURCE_POLICY,
            "examples": [{"description": "Analyze portfolio risk", "arguments": {"codes": ["600519", "000001"], "weights": [0.6, 0.4]}}],
            "tags": ["provider-contract", "portfolio", "risk"],
        },
        {
            "name": "stress_test_portfolio",
            "title": "Portfolio Stress Test",
            "category": "portfolio",
            "standard_model": "PortfolioStressTest",
            "description": "Run read-only portfolio stress scenarios.",
            "required_params": ["codes", "weights"],
            "query_model": _schema("PortfolioStressTestQuery", {"codes": {"type": "array", "items": {"type": "string"}}, "weights": {"type": "array", "items": {"type": "number"}}, "scenario": {"type": "string"}}, ["codes", "weights"]),
            "freshness": _PORTFOLIO_FRESHNESS,
            "source_policy": _PORTFOLIO_SOURCE_POLICY,
            "examples": [{"description": "Run market crash stress test", "arguments": {"codes": ["600519"], "weights": [1.0], "scenario": "market_crash"}}],
            "tags": ["provider-contract", "portfolio", "stress"],
        },
        {
            "name": "analyze_portfolio_risk_barra",
            "title": "Portfolio Barra Risk",
            "category": "portfolio",
            "standard_model": "PortfolioBarraRisk",
            "description": "Analyze portfolio factor exposure using the existing Barra-style risk path.",
            "required_params": ["codes", "weights"],
            "query_model": _schema("PortfolioBarraRiskQuery", {"codes": {"type": "array", "items": {"type": "string"}}, "weights": {"type": "array", "items": {"type": "number"}}}, ["codes", "weights"]),
            "freshness": _PORTFOLIO_FRESHNESS,
            "source_policy": _PORTFOLIO_SOURCE_POLICY,
            "examples": [{"description": "Analyze Barra-style risk", "arguments": {"codes": ["600519", "000001"], "weights": [0.5, 0.5]}}],
            "tags": ["provider-contract", "portfolio", "risk", "barra"],
        },
        {
            "name": "get_investment_analysis",
            "title": "Investment Analysis",
            "category": "decision",
            "standard_model": "InvestmentAnalysis",
            "description": "Read stock investment analysis with the existing decision context chain.",
            "required_params": ["code"],
            "query_model": _schema("InvestmentAnalysisQuery", {**code_props, "as_of": {"type": "string"}}, ["code"]),
            "freshness": _DECISION_FRESHNESS,
            "source_policy": _DECISION_SOURCE_POLICY,
            "examples": [{"description": "Read investment analysis", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "decision", "analysis"],
        },
        {
            "name": "get_unified_decision_summary",
            "title": "Unified Decision Summary",
            "category": "decision",
            "standard_model": "UnifiedDecisionSummary",
            "description": "Read a compact unified decision summary from existing decision services.",
            "required_params": ["code"],
            "query_model": _schema("UnifiedDecisionSummaryQuery", {**code_props, "as_of": {"type": "string"}}, ["code"]),
            "freshness": _DECISION_FRESHNESS,
            "source_policy": _DECISION_SOURCE_POLICY,
            "examples": [{"description": "Read decision summary", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "decision", "summary"],
        },
        {
            "name": "get_unified_decision_details",
            "title": "Unified Decision Details",
            "category": "decision",
            "standard_model": "UnifiedDecisionDetails",
            "description": "Read detailed unified decision evidence from existing decision services.",
            "required_params": ["code"],
            "query_model": _schema("UnifiedDecisionDetailsQuery", {**code_props, "as_of": {"type": "string"}}, ["code"]),
            "freshness": _DECISION_FRESHNESS,
            "source_policy": _DECISION_SOURCE_POLICY,
            "examples": [{"description": "Read decision details", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "decision", "details"],
        },
        {
            "name": "get_unified_decision",
            "title": "Unified Decision",
            "category": "decision",
            "standard_model": "UnifiedDecision",
            "description": "Read the full unified decision payload while preserving the existing result shape.",
            "required_params": ["code"],
            "query_model": _schema("UnifiedDecisionQuery", {**code_props, "as_of": {"type": "string"}}, ["code"]),
            "freshness": _DECISION_FRESHNESS,
            "source_policy": _DECISION_SOURCE_POLICY,
            "examples": [{"description": "Read full decision payload", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "decision", "full"],
        },
        {
            "name": "get_research_summary",
            "title": "Research Summary",
            "category": "research",
            "standard_model": "ResearchSummary",
            "description": "Summarize recent research records for one stock.",
            "required_params": ["code"],
            "query_model": _schema("ResearchSummaryQuery", {**code_props, "limit": {"type": "integer", "minimum": 1, "maximum": 100}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read recent research summary", "arguments": {"code": "600519", "limit": 10}}],
            "tags": ["provider-contract", "research", "summary"],
        },
        {
            "name": "search_research_db",
            "title": "Search Research DB",
            "category": "research",
            "standard_model": "ResearchSearch",
            "description": "Search local research records by keyword or stock code.",
            "required_params": [],
            "query_model": _schema("ResearchSearchQuery", {"keyword": {"type": "string"}, "stock_code": {"type": "string"}, "days": {"type": "integer", "minimum": 1, "maximum": 3650}}),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Search recent AI reports", "arguments": {"keyword": "人工智能", "days": 90}}],
            "tags": ["provider-contract", "research", "search"],
        },
        {
            "name": "get_stock_news",
            "title": "Stock News",
            "category": "news",
            "standard_model": "StockNews",
            "description": "Read stock news through existing news providers.",
            "required_params": ["code"],
            "query_model": _schema("StockNewsQuery", {**code_props, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read stock news", "arguments": {"code": "600519", "limit": 20}}],
            "tags": ["provider-contract", "news", "stock"],
        },
        {
            "name": "get_market_news",
            "title": "Market News",
            "category": "news",
            "standard_model": "MarketNews",
            "description": "Read latest market news through existing news providers.",
            "required_params": [],
            "query_model": _schema("MarketNewsQuery", {"limit": {"type": "integer", "minimum": 1, "maximum": 200}}),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read latest market news", "arguments": {"limit": 20}}],
            "tags": ["provider-contract", "news", "market"],
        },
        {
            "name": "get_stock_notices",
            "title": "Stock Notices",
            "category": "news",
            "standard_model": "StockNotices",
            "description": "Read stock notices and announcements from existing notice sources.",
            "required_params": ["code"],
            "query_model": _schema("StockNoticesQuery", {**code_props, "start_date": {"type": "string"}, "end_date": {"type": "string"}, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read stock notices", "arguments": {"code": "600519", "limit": 20}}],
            "tags": ["provider-contract", "news", "notices"],
        },
        {
            "name": "get_stock_research",
            "title": "Stock Research",
            "category": "research",
            "standard_model": "StockResearch",
            "description": "Read analyst research reports for one stock.",
            "required_params": ["code"],
            "query_model": _schema("StockResearchQuery", {**code_props, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read stock research", "arguments": {"code": "600519", "limit": 10}}],
            "tags": ["provider-contract", "research", "analyst"],
        },
        {
            "name": "get_research_reports",
            "title": "Research Reports",
            "category": "research",
            "standard_model": "ResearchReports",
            "description": "Read research report list by keyword, stock, or time window.",
            "required_params": [],
            "query_model": _schema("ResearchReportsQuery", {"keyword": {"type": "string"}, "stock_code": {"type": "string"}, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read research reports", "arguments": {"keyword": "新能源", "limit": 20}}],
            "tags": ["provider-contract", "research", "reports"],
        },
        {
            "name": "get_profit_forecast",
            "title": "Profit Forecast",
            "category": "research",
            "standard_model": "ProfitForecast",
            "description": "Read analyst profit forecasts from existing research sources.",
            "required_params": ["code"],
            "query_model": _schema("ProfitForecastQuery", {**code_props, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read profit forecast", "arguments": {"code": "600519", "limit": 20}}],
            "tags": ["provider-contract", "research", "forecast"],
        },
        {
            "name": "get_analyst_ranking",
            "title": "Analyst Ranking",
            "category": "research",
            "standard_model": "AnalystRanking",
            "description": "Read analyst ranking data from existing research providers.",
            "required_params": [],
            "query_model": _schema("AnalystRankingQuery", {"year": {"type": "string"}}),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read analyst ranking", "arguments": {"year": "2025"}}],
            "tags": ["provider-contract", "research", "analyst", "ranking"],
        },
        {
            "name": "analyze_stock_sentiment",
            "title": "Stock Sentiment",
            "category": "sentiment",
            "standard_model": "StockSentiment",
            "description": "Analyze stock sentiment from news, flows, and text signal sources.",
            "required_params": ["code"],
            "query_model": _schema("StockSentimentQuery", {**code_props, "days": {"type": "integer", "minimum": 1, "maximum": 365}, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _SENTIMENT_SOURCE_POLICY,
            "examples": [{"description": "Analyze stock sentiment", "arguments": {"code": "600519", "days": 30}}],
            "tags": ["provider-contract", "sentiment", "stock"],
        },
        {
            "name": "calculate_fear_greed_index",
            "title": "Fear Greed Index",
            "category": "sentiment",
            "standard_model": "FearGreedIndex",
            "description": "Calculate market fear-greed context from existing sentiment indicators.",
            "required_params": [],
            "query_model": _schema("FearGreedIndexQuery"),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _SENTIMENT_SOURCE_POLICY,
            "examples": [{"description": "Calculate fear-greed index", "arguments": {}}],
            "tags": ["provider-contract", "sentiment", "market"],
        },
        {
            "name": "get_market_sentiment_context",
            "title": "Market Sentiment Context",
            "category": "sentiment",
            "standard_model": "MarketSentimentContext",
            "description": "Read market sentiment context from northbound, margin, news, and market state inputs.",
            "required_params": [],
            "query_model": _schema("MarketSentimentContextQuery", {"days": {"type": "integer", "minimum": 1, "maximum": 365}}),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _SENTIMENT_SOURCE_POLICY,
            "examples": [{"description": "Read sentiment context", "arguments": {"days": 30}}],
            "tags": ["provider-contract", "sentiment", "context"],
        },
        {
            "name": "get_stock_text_signals",
            "title": "Stock Text Signals",
            "category": "sentiment",
            "standard_model": "StockTextSignals",
            "description": "Extract text signals for one stock from existing news/research text inputs.",
            "required_params": ["code"],
            "query_model": _schema("StockTextSignalsQuery", {**code_props, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _SENTIMENT_SOURCE_POLICY,
            "examples": [{"description": "Read stock text signals", "arguments": {"code": "600519", "limit": 20}}],
            "tags": ["provider-contract", "sentiment", "text"],
        },
        {
            "name": "check_all_alerts",
            "title": "Check Alerts",
            "category": "alerts",
            "standard_model": "AlertEvaluation",
            "description": "Evaluate configured alerts in read-only report mode using current market data.",
            "required_params": [],
            "query_model": _schema("CheckAlertsQuery"),
            "freshness": _ALERT_FRESHNESS,
            "source_policy": _ALERT_SOURCE_POLICY,
            "examples": [{"description": "Check all active alerts", "arguments": {}}],
            "tags": ["provider-contract", "alerts", "read-only"],
        },
        {
            "name": "get_ipo_info",
            "title": "IPO Info",
            "category": "basic_data",
            "standard_model": "IPOInfo",
            "description": "Read new-stock and convertible-bond subscription info through TDX/Tushare/AKShare paths.",
            "required_params": [],
            "query_model": _schema("IPOInfoQuery", {"ipo_type": {"type": "integer", "minimum": 0, "maximum": 2}, "include_future": {"type": "boolean"}}),
            "freshness": _TDX_EXT_FRESHNESS,
            "source_policy": _TDX_EXT_SOURCE_POLICY,
            "examples": [{"description": "Read upcoming IPO and CB subscription info", "arguments": {"ipo_type": 2, "include_future": True}}],
            "tags": ["provider-contract", "basic-data", "ipo", "tdx"],
        },
        {
            "name": "get_cb_info",
            "title": "Convertible Bond Info",
            "category": "basic_data",
            "standard_model": "ConvertibleBondInfo",
            "description": "Read convertible bond metadata through existing TDX/Tushare/AKShare paths.",
            "required_params": ["code"],
            "query_model": _schema("ConvertibleBondInfoQuery", {**code_props}, ["code"]),
            "freshness": _TDX_EXT_FRESHNESS,
            "source_policy": _TDX_EXT_SOURCE_POLICY,
            "examples": [{"description": "Read convertible bond info", "arguments": {"code": "123039"}}],
            "tags": ["provider-contract", "basic-data", "convertible-bond", "tdx"],
        },
        {
            "name": "get_stock_capital",
            "title": "Stock Capital",
            "category": "basic_data",
            "standard_model": "StockCapital",
            "description": "Read share-capital data through existing TDX/Tushare/AKShare/CNInfo fallback paths.",
            "required_params": ["code"],
            "query_model": _schema("StockCapitalQuery", {**code_props, "dates": {"type": "array", "items": {"type": "string"}}}, ["code"]),
            "freshness": _TDX_EXT_FRESHNESS,
            "source_policy": _TDX_EXT_SOURCE_POLICY,
            "examples": [{"description": "Read latest share-capital data", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "basic-data", "capital", "tdx"],
        },
        {
            "name": "get_tdx_extended_data",
            "title": "TDX Extended Data",
            "category": "basic_data",
            "standard_model": "TDXExtendedData",
            "description": "Document read-only TDX extended GP/BK/SC/FN field access used by AIASK internal adapters.",
            "required_params": ["scope", "fields"],
            "query_model": _schema(
                "TDXExtendedDataQuery",
                {
                    "scope": {"type": "string", "enum": ["gp", "bk", "sc", "fn", "dividend"]},
                    "codes": {"type": "array", "items": {"type": "string"}},
                    "blocks": {"type": "array", "items": {"type": "string"}},
                    "fields": {"type": "array", "items": {"type": "string"}},
                    "start_time": {"type": "string"},
                    "end_time": {"type": "string"},
                },
                ["scope", "fields"],
            ),
            "freshness": _TDX_EXT_FRESHNESS,
            "source_policy": SourcePolicy(
                priority=[
                    "tqcenter.get_divid_factors",
                    "tqcenter.get_gp_one_data",
                    "tqcenter.get_gpjy_value",
                    "tqcenter.get_bkjy_value",
                    "tqcenter.get_scjy_value",
                    "tqcenter.get_financial_data",
                ],
                local_only_env="TDX_LOCAL_ONLY",
                online_fallback="no new fallback path; this is contract metadata for existing adapters",
                notes=[_TDX_PRIORITY_NOTE],
            ),
            "examples": [{"description": "Describe a TDX GP field query", "arguments": {"scope": "gp", "codes": ["600519"], "fields": ["GP01"]}}],
            "tags": ["provider-contract", "tdx", "extended-fields", "metadata-only"],
        },
    ]
    return {
        spec["name"]: _contract(
            name=spec["name"],
            title=spec["title"],
            category=spec["category"],
            description=spec["description"],
            required_params=spec["required_params"],
            query_model=spec["query_model"],
            data_model=spec.get("data_model") or _schema(spec["standard_model"], {"records": _GENERIC_RECORD_LIST}),
            freshness=spec["freshness"],
            source_policy=spec["source_policy"],
            examples=spec["examples"],
            tags=spec["tags"],
            standard_model=spec["standard_model"],
        )
        for spec in specs
    }
