"""Explicit provider-backed tool contracts."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

from .base import FreshnessPolicy, SourcePolicy, json_schema
from .builder import build_contract
from .models import (
    BlockStocks,
    BlockStocksQuery,
    BlockTrades,
    BlockTradesQuery,
    ConceptFundFlow,
    ConceptFundFlowQuery,
    DragonTiger,
    DragonTigerQuery,
    EquityHistorical,
    EquityHistoricalQuery,
    EquityQuote,
    EquityQuoteQuery,
    FinancialMetrics,
    FinancialMetricsQuery,
    MacroIndicator,
    MacroIndicatorQuery,
    MarginData,
    MarginDataQuery,
    MarginRanking,
    MarginRankingQuery,
    MarketBlocks,
    MarketBlocksQuery,
    NorthFundFlow,
    NorthFundFlowQuery,
    NorthFundHolding,
    NorthFundHoldingQuery,
    NorthFundTop,
    NorthFundTopQuery,
    OptionChain,
    OptionChainQuery,
    SectorFundFlow,
    SectorFundFlowQuery,
    StockInfo,
    StockInfoQuery,
    StockFundFlow,
    StockFundFlowQuery,
    TradingCalendar,
    TradingCalendarQuery,
)


def _contract(
    *,
    name: str,
    title: str,
    category: str,
    description: str,
    required_params: list[str],
    query_model: type,
    data_model: type | dict[str, Any],
    freshness: FreshnessPolicy,
    source_policy: SourcePolicy,
    examples: list[dict[str, Any]],
    tags: list[str],
    standard_model: str | None = None,
) -> dict[str, Any]:
    return build_contract(
        name=name,
        title=title,
        category=category,
        description=description,
        required_params=required_params,
        query_model=query_model,
        data_model=data_model,
        freshness=freshness,
        source_policy=source_policy,
        examples=examples,
        tags=tags,
        standard_model=standard_model,
    )


_QUOTE_FRESHNESS = FreshnessPolicy(
    expectation="intraday_or_latest_quote_snapshot",
    max_stale_seconds=900,
    data_timestamp_field="data_timestamp",
)
_KLINE_FRESHNESS = FreshnessPolicy(
    expectation="daily_kline_t0_to_t1_or_requested_period_snapshot",
    data_timestamp_field="latest_bar.date",
)
_INFO_FRESHNESS = FreshnessPolicy(
    expectation="latest_reference_or_profile_snapshot",
    data_timestamp_field="listDate",
)
_CALENDAR_FRESHNESS = FreshnessPolicy(
    expectation="static_calendar_snapshot_with_period_filter",
    data_timestamp_field="dates[-1]",
)
_FINANCIAL_FRESHNESS = FreshnessPolicy(
    expectation="latest_report_period_financial_metrics",
    data_timestamp_field="reportDate",
)
_FUND_FLOW_FRESHNESS = FreshnessPolicy(
    expectation="intraday_or_latest_trading_day_fund_flow_snapshot",
    max_stale_seconds=86400,
    data_timestamp_field="tradeDate",
)
_NORTH_FUND_FRESHNESS = FreshnessPolicy(
    expectation="latest_northbound_flow_or_holding_snapshot",
    max_stale_seconds=86400,
    data_timestamp_field="date",
)
_SECTOR_FRESHNESS = FreshnessPolicy(
    expectation="intraday_or_latest_sector_snapshot",
    max_stale_seconds=1800,
)
_MACRO_FRESHNESS = FreshnessPolicy(
    expectation="latest_published_macro_indicator_snapshot",
    data_timestamp_field="records[0].publishDate",
)
_OPTIONS_FRESHNESS = FreshnessPolicy(
    expectation="near_real_time_option_chain_snapshot",
    max_stale_seconds=60,
    data_timestamp_field="underlying.time",
)

_TDX_PRIORITY_NOTE = "TDX_LOCAL_ONLY=1 keeps the chain on local/TDX sources and does not force online fallback."

_FINANCIAL_SOURCE_POLICY = SourcePolicy(
    priority=["db.get_financials", "tqcenter", "tushare_pro", "akshare_financials", "baostock_financials"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="kept within the existing get_financials implementation",
    notes=[
        _TDX_PRIORITY_NOTE,
        "This contract records the current AIASK source chain; it does not introduce a new provider path.",
    ],
)
_STOCK_INFO_SOURCE_POLICY = SourcePolicy(
    priority=["tushare_pro.stock_basic", "tushare_pro.daily_basic", "akshare.stock_individual_info_em", "akshare.stock_profile_cninfo"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="kept within the existing get_stock_info implementation",
    notes=["This contract documents the current tool behavior and does not add a new provider path."],
)
_STOCK_FUND_FLOW_SOURCE_POLICY = SourcePolicy(
    priority=["db.stock_fund_flow", "tqcenter.more_info", "tushare.moneyflow", "eastmoney.push2.fflow"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="disabled for TDX local paths; existing Tushare/Eastmoney fallback remains unchanged",
    notes=[_TDX_PRIORITY_NOTE],
)
_NORTH_FUND_SOURCE_POLICY = SourcePolicy(
    priority=["north_fund_flow", "tushare.moneyflow_hsgt", "hkex.daily_stat", "eastmoney.datacenter"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="existing function may use online Tushare/HKEX/Eastmoney unless local-only runtime disables upstream access",
    notes=["Validity gates reject empty, stale, implausible, or no-flow northbound records before fallback selection."],
)
_SECTOR_FUND_FLOW_SOURCE_POLICY = SourcePolicy(
    priority=["memory_cache", "cache.sector_fund_flow", "db.market_blocks", "eastmoney.push2", "tushare_pro.moneyflow_ind"],
    online_fallback="existing sector flow fallback chain is preserved",
    notes=["DB market_blocks fallback is marked degraded because it uses sector heat proxies when true flow is unavailable."],
)
_CONCEPT_FUND_FLOW_SOURCE_POLICY = SourcePolicy(
    priority=["eastmoney.push2.concept"],
    online_fallback="existing Eastmoney direct API path is preserved",
)
_DRAGON_TIGER_SOURCE_POLICY = SourcePolicy(
    priority=["sina.stock_lhb_detail_daily", "eastmoney.stock_lhb_detail"],
    online_fallback="fallback to Eastmoney and recent trading-date backtracking remains unchanged",
)
_MARGIN_SOURCE_POLICY = SourcePolicy(
    priority=["db.margin_detail", "db.margin_market_flow", "eastmoney.datacenter", "akshare.margin_account", "akshare.stock_margin_sse"],
    online_fallback="existing Eastmoney/AkShare fallback chain is preserved",
)
_BLOCK_TRADES_SOURCE_POLICY = SourcePolicy(
    priority=["eastmoney.block_trades", "eastmoney.block_trades.backtrack", "tushare_pro.stock_basic"],
    online_fallback="existing Eastmoney backtracking and Tushare metadata enrichment are preserved",
)
_MARKET_BLOCK_SOURCE_POLICY = SourcePolicy(
    priority=["db.market_blocks", "akshare.stock_sector_spot", "akshare.ths_board_names", "akshare.eastmoney_board", "akshare.area_summary"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="existing DB-first then AKShare fallback chain is preserved",
    notes=[_TDX_PRIORITY_NOTE],
)
_BLOCK_STOCK_SOURCE_POLICY = SourcePolicy(
    priority=["tqcenter.get_stock_list_in_sector", "db.block_stocks", "akshare.eastmoney_cons", "akshare.sina_sector_detail", "akshare.ths_detail", "tushare_pro.concept_detail"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="existing block constituent fallback chain is preserved",
    notes=[_TDX_PRIORITY_NOTE],
)
_MACRO_SOURCE_POLICY = SourcePolicy(
    priority=["tushare_pro.macro", "akshare.macro", "curl.mofcom"],
    online_fallback="existing Tushare/AkShare/curl fallback chain is preserved",
)
_OPTIONS_SOURCE_POLICY = SourcePolicy(
    priority=["akshare.option_sse_list_sina", "akshare.option_sse_codes_sina", "akshare.option_sse_spot_price_sina", "akshare.option_sse_underlying_spot_price_sina"],
    online_fallback="no additional provider path; degraded empty-chain responses are preserved when Sina upstream is partial",
)


def _array_of(model: type) -> dict[str, Any]:
    return {"type": "array", "items": json_schema(model)}


def _schema(title: str, properties: dict[str, Any] | None = None, required: list[str] | None = None) -> dict[str, Any]:
    return {
        "type": "object",
        "title": title,
        "properties": properties or {},
        "required": required or [],
        "additionalProperties": True,
    }


_GENERIC_RECORD_LIST = {"type": "array", "items": _schema("Record")}

_TECHNICAL_FRESHNESS = FreshnessPolicy(
    expectation="latest_kline_derived_technical_snapshot",
    data_timestamp_field="latest_bar.date",
)
_BACKTEST_FRESHNESS = FreshnessPolicy(
    expectation="deterministic_result_from_requested_historical_window",
    data_timestamp_field="end_date",
)
_VALUATION_FRESHNESS = FreshnessPolicy(
    expectation="latest_financial_and_market_context_snapshot",
    data_timestamp_field="valuation_date",
)
_PORTFOLIO_FRESHNESS = FreshnessPolicy(
    expectation="latest_holdings_and_recent_return_snapshot",
    data_timestamp_field="as_of",
)
_DECISION_FRESHNESS = FreshnessPolicy(
    expectation="current_or_as_of_decision_context_snapshot",
    data_timestamp_field="as_of",
)
_RESEARCH_FRESHNESS = FreshnessPolicy(
    expectation="latest_research_news_or_sentiment_snapshot",
    max_stale_seconds=86400,
    data_timestamp_field="publish_time",
)
_ALERT_FRESHNESS = FreshnessPolicy(
    expectation="latest_read_only_alert_evaluation_snapshot",
    max_stale_seconds=900,
    data_timestamp_field="checked_at",
)
_TDX_EXT_FRESHNESS = FreshnessPolicy(
    expectation="latest_tdx_or_reference_data_snapshot",
    data_timestamp_field="asof_time",
)

_TECHNICAL_SOURCE_POLICY = SourcePolicy(
    priority=["db.get_klines", "market.get_kline", "technical_analysis", "pattern_recognition"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="existing market.get_kline fallback is preserved",
    notes=[_TDX_PRIORITY_NOTE],
)
_BACKTEST_SOURCE_POLICY = SourcePolicy(
    priority=["db.get_klines", "market.get_kline", "quant_engine", "strategy_factory"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="existing kline fallback chain is preserved",
    notes=["Backtest tools remain read-only simulations and do not route to live trading."],
)
_VALUATION_SOURCE_POLICY = SourcePolicy(
    priority=["db.stocks", "db.get_stock_info", "db.get_financials", "finance.get_financials", "valuation_peer"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="existing valuation fallback chain is preserved",
    notes=[_TDX_PRIORITY_NOTE],
)
_PORTFOLIO_SOURCE_POLICY = SourcePolicy(
    priority=["input_holdings", "db.get_klines", "market.get_kline", "portfolio_engine", "risk_engine"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="existing portfolio data fallback chain is preserved",
)
_DECISION_SOURCE_POLICY = SourcePolicy(
    priority=["decision_context", "db", "market", "fund_flow", "valuation", "news_sentiment"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="existing decision context fallback chain is preserved",
)
_RESEARCH_SOURCE_POLICY = SourcePolicy(
    priority=["db.research", "tushare_pro", "akshare", "eastmoney", "sina"],
    online_fallback="existing research/news fallback chain is preserved",
)
_SENTIMENT_SOURCE_POLICY = SourcePolicy(
    priority=["db.news", "db.northbound", "db.margin", "market_news", "text_signal"],
    online_fallback="existing sentiment context fallback chain is preserved",
)
_ALERT_SOURCE_POLICY = SourcePolicy(
    priority=["db.alerts", "market.quote", "market.kline", "indicator_engine"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="existing alert evaluation market fallback chain is preserved",
)
_TDX_EXT_SOURCE_POLICY = SourcePolicy(
    priority=["tqcenter", "tdx_local", "tushare_pro", "akshare", "eastmoney"],
    local_only_env="TDX_LOCAL_ONLY",
    online_fallback="disabled for local-only TDX paths; existing fallback remains unchanged",
    notes=[_TDX_PRIORITY_NOTE],
)


def _platform_contracts() -> dict[str, dict[str, Any]]:
    code_props = {
        "code": {"type": ["string", "null"], "description": "6-digit security code."},
        "stock_code": {"type": ["string", "null"], "description": "Deprecated alias for code."},
        "symbol": {"type": ["string", "null"], "description": "Alias for code."},
        "ticker": {"type": ["string", "null"], "description": "Alias for code."},
    }
    specs: list[dict[str, Any]] = [
        {
            "name": "calculate_technical_indicators",
            "title": "Technical Indicators",
            "category": "technical",
            "standard_model": "TechnicalIndicators",
            "description": "Calculate technical indicators from existing DB-first kline data paths.",
            "required_params": ["code", "indicators"],
            "query_model": _schema(
                "TechnicalIndicatorsQuery",
                {
                    "code": {"type": "string"},
                    "indicators": {"type": "array", "items": {"type": "string"}},
                    "period": {"type": "string", "default": "daily"},
                    "limit": {"type": "integer", "minimum": 20, "maximum": 5000, "default": 250},
                },
                ["code", "indicators"],
            ),
            "freshness": _TECHNICAL_FRESHNESS,
            "source_policy": _TECHNICAL_SOURCE_POLICY,
            "examples": [{"description": "Calculate MA and RSI", "arguments": {"code": "600519", "indicators": ["MA", "RSI"], "limit": 250}}],
            "tags": ["provider-contract", "technical", "indicators"],
        },
        {
            "name": "check_candlestick_patterns",
            "title": "Candlestick Patterns",
            "category": "technical",
            "standard_model": "CandlestickPatterns",
            "description": "Detect candlestick patterns from the existing DB/kline fallback chain.",
            "required_params": ["code"],
            "query_model": _schema(
                "CandlestickPatternsQuery",
                {"code": {"type": "string"}, "period": {"type": "string", "default": "daily"}, "limit": {"type": "integer", "minimum": 20, "maximum": 1000, "default": 100}},
                ["code"],
            ),
            "freshness": _TECHNICAL_FRESHNESS,
            "source_policy": _TECHNICAL_SOURCE_POLICY,
            "examples": [{"description": "Check recent daily candlestick patterns", "arguments": {"code": "600519", "limit": 100}}],
            "tags": ["provider-contract", "technical", "patterns"],
        },
        {
            "name": "get_available_patterns",
            "title": "Available Patterns",
            "category": "technical",
            "standard_model": "PatternCatalog",
            "description": "List supported candlestick pattern identifiers.",
            "required_params": [],
            "query_model": _schema("PatternCatalogQuery"),
            "freshness": FreshnessPolicy(expectation="static_pattern_catalog"),
            "source_policy": SourcePolicy(priority=["pattern_recognition"]),
            "examples": [{"description": "List supported patterns", "arguments": {}}],
            "tags": ["provider-contract", "technical", "catalog"],
        },
        {
            "name": "run_simple_backtest",
            "title": "Simple Backtest",
            "category": "backtest",
            "standard_model": "SimpleBacktestResult",
            "description": "Run a read-only simple strategy backtest using historical kline inputs.",
            "required_params": ["code"],
            "query_model": _schema(
                "SimpleBacktestQuery",
                {**code_props, "strategy": {"type": "string"}, "initial_capital": {"type": "number"}, "start_date": {"type": "string"}, "end_date": {"type": "string"}},
                ["code"],
            ),
            "freshness": _BACKTEST_FRESHNESS,
            "source_policy": _BACKTEST_SOURCE_POLICY,
            "examples": [{"description": "Run a simple moving-average backtest", "arguments": {"code": "600519", "strategy": "ma_cross"}}],
            "tags": ["provider-contract", "backtest", "simulation"],
        },
        {
            "name": "run_batch_backtest",
            "title": "Batch Backtest",
            "category": "backtest",
            "standard_model": "BatchBacktestResult",
            "description": "Run read-only batch backtests across multiple securities.",
            "required_params": ["codes"],
            "query_model": _schema(
                "BatchBacktestQuery",
                {"codes": {"type": "array", "items": {"type": "string"}}, "strategy": {"type": "string"}, "initial_capital": {"type": "number"}, "start_date": {"type": "string"}, "end_date": {"type": "string"}},
                ["codes"],
            ),
            "freshness": _BACKTEST_FRESHNESS,
            "source_policy": _BACKTEST_SOURCE_POLICY,
            "examples": [{"description": "Run a batch backtest", "arguments": {"codes": ["600519", "000001"], "strategy": "ma_cross"}}],
            "tags": ["provider-contract", "backtest", "batch"],
        },
        {
            "name": "backtest_factor",
            "title": "Factor Backtest",
            "category": "backtest",
            "standard_model": "FactorBacktestResult",
            "description": "Backtest factor signals using existing quant data paths.",
            "required_params": ["factor_name"],
            "query_model": _schema(
                "FactorBacktestQuery",
                {"factor_name": {"type": "string"}, "codes": {"type": "array", "items": {"type": "string"}}, "start_date": {"type": "string"}, "end_date": {"type": "string"}},
                ["factor_name"],
            ),
            "freshness": _BACKTEST_FRESHNESS,
            "source_policy": _BACKTEST_SOURCE_POLICY,
            "examples": [{"description": "Backtest one factor", "arguments": {"factor_name": "momentum_20d", "codes": ["600519"]}}],
            "tags": ["provider-contract", "backtest", "factor"],
        },
        {
            "name": "run_factor_group_backtest",
            "title": "Factor Group Backtest",
            "category": "backtest",
            "standard_model": "FactorGroupBacktestResult",
            "description": "Run grouped factor backtests with PIT-compatible historical inputs.",
            "required_params": ["factor_name"],
            "query_model": _schema(
                "FactorGroupBacktestQuery",
                {"factor_name": {"type": "string"}, "codes": {"type": "array", "items": {"type": "string"}}, "groups": {"type": "integer"}, "start_date": {"type": "string"}, "end_date": {"type": "string"}},
                ["factor_name"],
            ),
            "freshness": _BACKTEST_FRESHNESS,
            "source_policy": _BACKTEST_SOURCE_POLICY,
            "examples": [{"description": "Run a five-group factor backtest", "arguments": {"factor_name": "momentum_20d", "groups": 5}}],
            "tags": ["provider-contract", "backtest", "factor", "grouped"],
        },
        {
            "name": "get_valuation_metrics",
            "title": "Valuation Metrics",
            "category": "valuation",
            "standard_model": "ValuationMetrics",
            "description": "Read PE/PB/market-cap valuation metrics from DB-first valuation sources.",
            "required_params": ["code"],
            "query_model": _schema("ValuationMetricsQuery", code_props, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Read valuation metrics", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "valuation", "fundamental"],
        },
        {
            "name": "dcf_valuation",
            "title": "DCF Valuation",
            "category": "valuation",
            "standard_model": "DCFValuation",
            "description": "Run DCF valuation using existing financial and market context fallbacks.",
            "required_params": ["code"],
            "query_model": _schema("DCFValuationQuery", {**code_props, "discount_rate": {"type": "number"}, "growth_rate": {"type": "number"}, "years": {"type": "integer", "minimum": 1, "maximum": 30}}, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Run DCF valuation", "arguments": {"code": "600519", "years": 5}}],
            "tags": ["provider-contract", "valuation", "dcf"],
        },
        {
            "name": "ddm_valuation",
            "title": "DDM Valuation",
            "category": "valuation",
            "standard_model": "DDMValuation",
            "description": "Run dividend discount valuation with existing financial fallbacks.",
            "required_params": ["code"],
            "query_model": _schema("DDMValuationQuery", {**code_props, "dividend": {"type": "number"}, "growth_rate": {"type": "number"}, "required_return": {"type": "number"}}, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Run DDM valuation", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "valuation", "ddm"],
        },
        {
            "name": "relative_valuation",
            "title": "Relative Valuation",
            "category": "valuation",
            "standard_model": "RelativeValuation",
            "description": "Run peer-relative valuation using existing valuation peer inputs.",
            "required_params": ["code"],
            "query_model": _schema("RelativeValuationQuery", {**code_props, "peer_codes": {"type": "array", "items": {"type": "string"}}, "metric": {"type": "string"}}, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Run relative valuation", "arguments": {"code": "600519", "metric": "pe"}}],
            "tags": ["provider-contract", "valuation", "relative"],
        },
        {
            "name": "get_historical_valuation",
            "title": "Historical Valuation",
            "category": "valuation",
            "standard_model": "HistoricalValuation",
            "description": "Read historical valuation series from existing valuation peer sources.",
            "required_params": ["code"],
            "query_model": _schema("HistoricalValuationQuery", {**code_props, "metric": {"type": "string"}, "limit": {"type": "integer", "minimum": 1, "maximum": 5000}}, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Read historical PE", "arguments": {"code": "600519", "metric": "pe", "limit": 240}}],
            "tags": ["provider-contract", "valuation", "history"],
        },
        {
            "name": "scenario_dcf_valuation",
            "title": "Scenario DCF Valuation",
            "category": "valuation",
            "standard_model": "ScenarioDCFValuation",
            "description": "Run scenario DCF valuation with existing financial context.",
            "required_params": ["code"],
            "query_model": _schema("ScenarioDCFValuationQuery", {**code_props, "scenarios": {"type": "array", "items": {"type": "object"}}, "years": {"type": "integer", "minimum": 1, "maximum": 30}}, ["code"]),
            "freshness": _VALUATION_FRESHNESS,
            "source_policy": _VALUATION_SOURCE_POLICY,
            "examples": [{"description": "Run scenario DCF", "arguments": {"code": "600519", "years": 5}}],
            "tags": ["provider-contract", "valuation", "scenario"],
        },
        {
            "name": "optimize_portfolio",
            "title": "Optimize Portfolio",
            "category": "portfolio",
            "standard_model": "PortfolioOptimization",
            "description": "Run read-only portfolio optimization over input securities and recent returns.",
            "required_params": ["codes"],
            "query_model": _schema("PortfolioOptimizationQuery", {"codes": {"type": "array", "items": {"type": "string"}}, "method": {"type": "string"}, "risk_free_rate": {"type": "number"}}, ["codes"]),
            "freshness": _PORTFOLIO_FRESHNESS,
            "source_policy": _PORTFOLIO_SOURCE_POLICY,
            "examples": [{"description": "Optimize a two-stock portfolio", "arguments": {"codes": ["600519", "000001"]}}],
            "tags": ["provider-contract", "portfolio", "optimization"],
        },
        {
            "name": "analyze_portfolio_risk",
            "title": "Portfolio Risk",
            "category": "portfolio",
            "standard_model": "PortfolioRisk",
            "description": "Analyze portfolio VaR/exposure risk using existing holdings and kline data.",
            "required_params": ["codes", "weights"],
            "query_model": _schema("PortfolioRiskQuery", {"codes": {"type": "array", "items": {"type": "string"}}, "weights": {"type": "array", "items": {"type": "number"}}, "confidence": {"type": "number"}, "lookback_days": {"type": "integer"}}, ["codes", "weights"]),
            "freshness": _PORTFOLIO_FRESHNESS,
            "source_policy": _PORTFOLIO_SOURCE_POLICY,
            "examples": [{"description": "Analyze portfolio risk", "arguments": {"codes": ["600519", "000001"], "weights": [0.6, 0.4]}}],
            "tags": ["provider-contract", "portfolio", "risk"],
        },
        {
            "name": "stress_test_portfolio",
            "title": "Portfolio Stress Test",
            "category": "portfolio",
            "standard_model": "PortfolioStressTest",
            "description": "Run read-only portfolio stress scenarios.",
            "required_params": ["codes", "weights"],
            "query_model": _schema("PortfolioStressTestQuery", {"codes": {"type": "array", "items": {"type": "string"}}, "weights": {"type": "array", "items": {"type": "number"}}, "scenario": {"type": "string"}}, ["codes", "weights"]),
            "freshness": _PORTFOLIO_FRESHNESS,
            "source_policy": _PORTFOLIO_SOURCE_POLICY,
            "examples": [{"description": "Run market crash stress test", "arguments": {"codes": ["600519"], "weights": [1.0], "scenario": "market_crash"}}],
            "tags": ["provider-contract", "portfolio", "stress"],
        },
        {
            "name": "analyze_portfolio_risk_barra",
            "title": "Portfolio Barra Risk",
            "category": "portfolio",
            "standard_model": "PortfolioBarraRisk",
            "description": "Analyze portfolio factor exposure using the existing Barra-style risk path.",
            "required_params": ["codes", "weights"],
            "query_model": _schema("PortfolioBarraRiskQuery", {"codes": {"type": "array", "items": {"type": "string"}}, "weights": {"type": "array", "items": {"type": "number"}}}, ["codes", "weights"]),
            "freshness": _PORTFOLIO_FRESHNESS,
            "source_policy": _PORTFOLIO_SOURCE_POLICY,
            "examples": [{"description": "Analyze Barra-style risk", "arguments": {"codes": ["600519", "000001"], "weights": [0.5, 0.5]}}],
            "tags": ["provider-contract", "portfolio", "risk", "barra"],
        },
        {
            "name": "get_investment_analysis",
            "title": "Investment Analysis",
            "category": "decision",
            "standard_model": "InvestmentAnalysis",
            "description": "Read stock investment analysis with the existing decision context chain.",
            "required_params": ["code"],
            "query_model": _schema("InvestmentAnalysisQuery", {**code_props, "as_of": {"type": "string"}}, ["code"]),
            "freshness": _DECISION_FRESHNESS,
            "source_policy": _DECISION_SOURCE_POLICY,
            "examples": [{"description": "Read investment analysis", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "decision", "analysis"],
        },
        {
            "name": "get_unified_decision_summary",
            "title": "Unified Decision Summary",
            "category": "decision",
            "standard_model": "UnifiedDecisionSummary",
            "description": "Read a compact unified decision summary from existing decision services.",
            "required_params": ["code"],
            "query_model": _schema("UnifiedDecisionSummaryQuery", {**code_props, "as_of": {"type": "string"}}, ["code"]),
            "freshness": _DECISION_FRESHNESS,
            "source_policy": _DECISION_SOURCE_POLICY,
            "examples": [{"description": "Read decision summary", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "decision", "summary"],
        },
        {
            "name": "get_unified_decision_details",
            "title": "Unified Decision Details",
            "category": "decision",
            "standard_model": "UnifiedDecisionDetails",
            "description": "Read detailed unified decision evidence from existing decision services.",
            "required_params": ["code"],
            "query_model": _schema("UnifiedDecisionDetailsQuery", {**code_props, "as_of": {"type": "string"}}, ["code"]),
            "freshness": _DECISION_FRESHNESS,
            "source_policy": _DECISION_SOURCE_POLICY,
            "examples": [{"description": "Read decision details", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "decision", "details"],
        },
        {
            "name": "get_unified_decision",
            "title": "Unified Decision",
            "category": "decision",
            "standard_model": "UnifiedDecision",
            "description": "Read the full unified decision payload while preserving the existing result shape.",
            "required_params": ["code"],
            "query_model": _schema("UnifiedDecisionQuery", {**code_props, "as_of": {"type": "string"}}, ["code"]),
            "freshness": _DECISION_FRESHNESS,
            "source_policy": _DECISION_SOURCE_POLICY,
            "examples": [{"description": "Read full decision payload", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "decision", "full"],
        },
        {
            "name": "get_research_summary",
            "title": "Research Summary",
            "category": "research",
            "standard_model": "ResearchSummary",
            "description": "Summarize recent research records for one stock.",
            "required_params": ["code"],
            "query_model": _schema("ResearchSummaryQuery", {**code_props, "limit": {"type": "integer", "minimum": 1, "maximum": 100}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read recent research summary", "arguments": {"code": "600519", "limit": 10}}],
            "tags": ["provider-contract", "research", "summary"],
        },
        {
            "name": "search_research_db",
            "title": "Search Research DB",
            "category": "research",
            "standard_model": "ResearchSearch",
            "description": "Search local research records by keyword or stock code.",
            "required_params": [],
            "query_model": _schema("ResearchSearchQuery", {"keyword": {"type": "string"}, "stock_code": {"type": "string"}, "days": {"type": "integer", "minimum": 1, "maximum": 3650}}),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Search recent AI reports", "arguments": {"keyword": "人工智能", "days": 90}}],
            "tags": ["provider-contract", "research", "search"],
        },
        {
            "name": "get_stock_news",
            "title": "Stock News",
            "category": "news",
            "standard_model": "StockNews",
            "description": "Read stock news through existing news providers.",
            "required_params": ["code"],
            "query_model": _schema("StockNewsQuery", {**code_props, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read stock news", "arguments": {"code": "600519", "limit": 20}}],
            "tags": ["provider-contract", "news", "stock"],
        },
        {
            "name": "get_market_news",
            "title": "Market News",
            "category": "news",
            "standard_model": "MarketNews",
            "description": "Read latest market news through existing news providers.",
            "required_params": [],
            "query_model": _schema("MarketNewsQuery", {"limit": {"type": "integer", "minimum": 1, "maximum": 200}}),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read latest market news", "arguments": {"limit": 20}}],
            "tags": ["provider-contract", "news", "market"],
        },
        {
            "name": "get_stock_notices",
            "title": "Stock Notices",
            "category": "news",
            "standard_model": "StockNotices",
            "description": "Read stock notices and announcements from existing notice sources.",
            "required_params": ["code"],
            "query_model": _schema("StockNoticesQuery", {**code_props, "start_date": {"type": "string"}, "end_date": {"type": "string"}, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read stock notices", "arguments": {"code": "600519", "limit": 20}}],
            "tags": ["provider-contract", "news", "notices"],
        },
        {
            "name": "get_stock_research",
            "title": "Stock Research",
            "category": "research",
            "standard_model": "StockResearch",
            "description": "Read analyst research reports for one stock.",
            "required_params": ["code"],
            "query_model": _schema("StockResearchQuery", {**code_props, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read stock research", "arguments": {"code": "600519", "limit": 10}}],
            "tags": ["provider-contract", "research", "analyst"],
        },
        {
            "name": "get_research_reports",
            "title": "Research Reports",
            "category": "research",
            "standard_model": "ResearchReports",
            "description": "Read research report list by keyword, stock, or time window.",
            "required_params": [],
            "query_model": _schema("ResearchReportsQuery", {"keyword": {"type": "string"}, "stock_code": {"type": "string"}, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read research reports", "arguments": {"keyword": "新能源", "limit": 20}}],
            "tags": ["provider-contract", "research", "reports"],
        },
        {
            "name": "get_profit_forecast",
            "title": "Profit Forecast",
            "category": "research",
            "standard_model": "ProfitForecast",
            "description": "Read analyst profit forecasts from existing research sources.",
            "required_params": ["code"],
            "query_model": _schema("ProfitForecastQuery", {**code_props, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read profit forecast", "arguments": {"code": "600519", "limit": 20}}],
            "tags": ["provider-contract", "research", "forecast"],
        },
        {
            "name": "get_analyst_ranking",
            "title": "Analyst Ranking",
            "category": "research",
            "standard_model": "AnalystRanking",
            "description": "Read analyst ranking data from existing research providers.",
            "required_params": [],
            "query_model": _schema("AnalystRankingQuery", {"year": {"type": "string"}}),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _RESEARCH_SOURCE_POLICY,
            "examples": [{"description": "Read analyst ranking", "arguments": {"year": "2025"}}],
            "tags": ["provider-contract", "research", "analyst", "ranking"],
        },
        {
            "name": "analyze_stock_sentiment",
            "title": "Stock Sentiment",
            "category": "sentiment",
            "standard_model": "StockSentiment",
            "description": "Analyze stock sentiment from news, flows, and text signal sources.",
            "required_params": ["code"],
            "query_model": _schema("StockSentimentQuery", {**code_props, "days": {"type": "integer", "minimum": 1, "maximum": 365}, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _SENTIMENT_SOURCE_POLICY,
            "examples": [{"description": "Analyze stock sentiment", "arguments": {"code": "600519", "days": 30}}],
            "tags": ["provider-contract", "sentiment", "stock"],
        },
        {
            "name": "calculate_fear_greed_index",
            "title": "Fear Greed Index",
            "category": "sentiment",
            "standard_model": "FearGreedIndex",
            "description": "Calculate market fear-greed context from existing sentiment indicators.",
            "required_params": [],
            "query_model": _schema("FearGreedIndexQuery"),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _SENTIMENT_SOURCE_POLICY,
            "examples": [{"description": "Calculate fear-greed index", "arguments": {}}],
            "tags": ["provider-contract", "sentiment", "market"],
        },
        {
            "name": "get_market_sentiment_context",
            "title": "Market Sentiment Context",
            "category": "sentiment",
            "standard_model": "MarketSentimentContext",
            "description": "Read market sentiment context from northbound, margin, news, and market state inputs.",
            "required_params": [],
            "query_model": _schema("MarketSentimentContextQuery", {"days": {"type": "integer", "minimum": 1, "maximum": 365}}),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _SENTIMENT_SOURCE_POLICY,
            "examples": [{"description": "Read sentiment context", "arguments": {"days": 30}}],
            "tags": ["provider-contract", "sentiment", "context"],
        },
        {
            "name": "get_stock_text_signals",
            "title": "Stock Text Signals",
            "category": "sentiment",
            "standard_model": "StockTextSignals",
            "description": "Extract text signals for one stock from existing news/research text inputs.",
            "required_params": ["code"],
            "query_model": _schema("StockTextSignalsQuery", {**code_props, "limit": {"type": "integer", "minimum": 1, "maximum": 200}}, ["code"]),
            "freshness": _RESEARCH_FRESHNESS,
            "source_policy": _SENTIMENT_SOURCE_POLICY,
            "examples": [{"description": "Read stock text signals", "arguments": {"code": "600519", "limit": 20}}],
            "tags": ["provider-contract", "sentiment", "text"],
        },
        {
            "name": "check_all_alerts",
            "title": "Check Alerts",
            "category": "alerts",
            "standard_model": "AlertEvaluation",
            "description": "Evaluate configured alerts in read-only report mode using current market data.",
            "required_params": [],
            "query_model": _schema("CheckAlertsQuery"),
            "freshness": _ALERT_FRESHNESS,
            "source_policy": _ALERT_SOURCE_POLICY,
            "examples": [{"description": "Check all active alerts", "arguments": {}}],
            "tags": ["provider-contract", "alerts", "read-only"],
        },
        {
            "name": "get_ipo_info",
            "title": "IPO Info",
            "category": "basic_data",
            "standard_model": "IPOInfo",
            "description": "Read new-stock and convertible-bond subscription info through TDX/Tushare/AKShare paths.",
            "required_params": [],
            "query_model": _schema("IPOInfoQuery", {"ipo_type": {"type": "integer", "minimum": 0, "maximum": 2}, "include_future": {"type": "boolean"}}),
            "freshness": _TDX_EXT_FRESHNESS,
            "source_policy": _TDX_EXT_SOURCE_POLICY,
            "examples": [{"description": "Read upcoming IPO and CB subscription info", "arguments": {"ipo_type": 2, "include_future": True}}],
            "tags": ["provider-contract", "basic-data", "ipo", "tdx"],
        },
        {
            "name": "get_cb_info",
            "title": "Convertible Bond Info",
            "category": "basic_data",
            "standard_model": "ConvertibleBondInfo",
            "description": "Read convertible bond metadata through existing TDX/Tushare/AKShare paths.",
            "required_params": ["code"],
            "query_model": _schema("ConvertibleBondInfoQuery", {**code_props}, ["code"]),
            "freshness": _TDX_EXT_FRESHNESS,
            "source_policy": _TDX_EXT_SOURCE_POLICY,
            "examples": [{"description": "Read convertible bond info", "arguments": {"code": "123039"}}],
            "tags": ["provider-contract", "basic-data", "convertible-bond", "tdx"],
        },
        {
            "name": "get_stock_capital",
            "title": "Stock Capital",
            "category": "basic_data",
            "standard_model": "StockCapital",
            "description": "Read share-capital data through existing TDX/Tushare/AKShare/CNInfo fallback paths.",
            "required_params": ["code"],
            "query_model": _schema("StockCapitalQuery", {**code_props, "dates": {"type": "array", "items": {"type": "string"}}}, ["code"]),
            "freshness": _TDX_EXT_FRESHNESS,
            "source_policy": _TDX_EXT_SOURCE_POLICY,
            "examples": [{"description": "Read latest share-capital data", "arguments": {"code": "600519"}}],
            "tags": ["provider-contract", "basic-data", "capital", "tdx"],
        },
        {
            "name": "get_tdx_extended_data",
            "title": "TDX Extended Data",
            "category": "basic_data",
            "standard_model": "TDXExtendedData",
            "description": "Document read-only TDX extended GP/BK/SC/FN field access used by AIASK internal adapters.",
            "required_params": ["scope", "fields"],
            "query_model": _schema(
                "TDXExtendedDataQuery",
                {
                    "scope": {"type": "string", "enum": ["gp", "bk", "sc", "fn", "dividend"]},
                    "codes": {"type": "array", "items": {"type": "string"}},
                    "blocks": {"type": "array", "items": {"type": "string"}},
                    "fields": {"type": "array", "items": {"type": "string"}},
                    "start_time": {"type": "string"},
                    "end_time": {"type": "string"},
                },
                ["scope", "fields"],
            ),
            "freshness": _TDX_EXT_FRESHNESS,
            "source_policy": SourcePolicy(
                priority=[
                    "tqcenter.get_divid_factors",
                    "tqcenter.get_gp_one_data",
                    "tqcenter.get_gpjy_value",
                    "tqcenter.get_bkjy_value",
                    "tqcenter.get_scjy_value",
                    "tqcenter.get_financial_data",
                ],
                local_only_env="TDX_LOCAL_ONLY",
                online_fallback="no new fallback path; this is contract metadata for existing adapters",
                notes=[_TDX_PRIORITY_NOTE],
            ),
            "examples": [{"description": "Describe a TDX GP field query", "arguments": {"scope": "gp", "codes": ["600519"], "fields": ["GP01"]}}],
            "tags": ["provider-contract", "tdx", "extended-fields", "metadata-only"],
        },
    ]
    return {
        spec["name"]: _contract(
            name=spec["name"],
            title=spec["title"],
            category=spec["category"],
            description=spec["description"],
            required_params=spec["required_params"],
            query_model=spec["query_model"],
            data_model=spec.get("data_model") or _schema(spec["standard_model"], {"records": _GENERIC_RECORD_LIST}),
            freshness=spec["freshness"],
            source_policy=spec["source_policy"],
            examples=spec["examples"],
            tags=spec["tags"],
            standard_model=spec["standard_model"],
        )
        for spec in specs
    }

_CONTRACTS: dict[str, dict[str, Any]] = {
    "get_realtime_quote": _contract(
        name="get_realtime_quote",
        title="Equity Quote",
        category="market",
        description="Read a normalized A-share quote while preserving the existing quote data shape.",
        required_params=["code"],
        query_model=EquityQuoteQuery,
        data_model=EquityQuote,
        freshness=_QUOTE_FRESHNESS,
        source_policy=SourcePolicy(
            priority=["db.stock_quotes", "data_source", "tdx_local", "akshare", "sina", "tencent"],
            local_only_env="TDX_LOCAL_ONLY",
            online_fallback="disabled when TDX_LOCAL_ONLY=1",
            notes=[_TDX_PRIORITY_NOTE],
        ),
        examples=[{"description": "Read latest quote", "arguments": {"code": "600519"}}],
        tags=["provider-contract", "equity", "quote", "market"],
    ),
    "get_kline": _contract(
        name="get_kline",
        title="Equity Historical",
        category="market",
        description="Read normalized OHLCV history through the existing kline source priority chain.",
        required_params=["code"],
        query_model=EquityHistoricalQuery,
        data_model=EquityHistorical,
        freshness=_KLINE_FRESHNESS,
        source_policy=SourcePolicy(
            priority=["db.get_klines", "data_source.get_kline", "baostock", "akshare", "tencent"],
            local_only_env="TDX_LOCAL_ONLY",
            online_fallback="disabled by data_source when TDX_LOCAL_ONLY=1",
            notes=[_TDX_PRIORITY_NOTE],
        ),
        examples=[{"description": "Read recent daily bars", "arguments": {"code": "600519", "period": "daily", "limit": 60}}],
        tags=["provider-contract", "equity", "historical", "ohlcv"],
    ),
    "get_kline_data": _contract(
        name="get_kline_data",
        title="Equity Historical Data",
        category="market",
        description="Read OHLCV history with optional date range while keeping the existing data response shape.",
        required_params=["code"],
        query_model=EquityHistoricalQuery,
        data_model=EquityHistorical,
        freshness=_KLINE_FRESHNESS,
        source_policy=SourcePolicy(
            priority=["db.get_klines", "data_source.get_kline", "akshare.stock_zh_a_hist"],
            local_only_env="TDX_LOCAL_ONLY",
            online_fallback="disabled by data_source when TDX_LOCAL_ONLY=1",
            notes=[_TDX_PRIORITY_NOTE],
        ),
        examples=[
            {
                "description": "Read bars for a date range",
                "arguments": {"code": "600519", "start_date": "2026-01-01", "end_date": "2026-03-31"},
            }
        ],
        tags=["provider-contract", "equity", "historical", "date-range"],
    ),
    "get_financials": _contract(
        name="get_financials",
        title="Financial Metrics",
        category="finance",
        description="Read latest normalized financial metrics through AIASK's DB/TDX/Tushare/AkShare/Baostock chain.",
        required_params=["code"],
        query_model=FinancialMetricsQuery,
        data_model=FinancialMetrics,
        freshness=_FINANCIAL_FRESHNESS,
        source_policy=_FINANCIAL_SOURCE_POLICY,
        examples=[{"description": "Read latest financial metrics", "arguments": {"code": "600519"}}],
        tags=["provider-contract", "finance", "financials", "fundamental"],
    ),
    "get_stock_info": _contract(
        name="get_stock_info",
        title="Stock Info",
        category="finance",
        description="Read normalized stock profile fields from the existing stock info tool chain.",
        required_params=["code"],
        query_model=StockInfoQuery,
        data_model=StockInfo,
        freshness=_INFO_FRESHNESS,
        source_policy=_STOCK_INFO_SOURCE_POLICY,
        examples=[{"description": "Read stock profile", "arguments": {"code": "600519"}}],
        tags=["provider-contract", "stock-info", "profile"],
    ),
    "get_stock_fund_flow": _contract(
        name="get_stock_fund_flow",
        title="Stock Fund Flow",
        category="fund_flow",
        description="Read individual stock fund-flow fields while preserving the existing flow response shape.",
        required_params=["code"],
        query_model=StockFundFlowQuery,
        data_model=StockFundFlow,
        freshness=_FUND_FLOW_FRESHNESS,
        source_policy=_STOCK_FUND_FLOW_SOURCE_POLICY,
        examples=[{"description": "Read individual stock fund flow", "arguments": {"code": "600519"}}],
        tags=["provider-contract", "fund-flow", "stock", "moneyflow"],
    ),
    "get_north_fund": _contract(
        name="get_north_fund",
        title="North Fund Flow",
        category="fund_flow",
        description="Read northbound fund-flow history with existing validity and fallback gates.",
        required_params=[],
        query_model=NorthFundFlowQuery,
        data_model=NorthFundFlow,
        freshness=_NORTH_FUND_FRESHNESS,
        source_policy=_NORTH_FUND_SOURCE_POLICY,
        examples=[{"description": "Read recent northbound flow", "arguments": {"days": 30}}],
        tags=["provider-contract", "fund-flow", "northbound"],
    ),
    "get_north_fund_holding": _contract(
        name="get_north_fund_holding",
        title="North Fund Holding",
        category="fund_flow",
        description="Read northbound holding snapshot for one stock from TDX/Eastmoney paths.",
        required_params=["stock_code"],
        query_model=NorthFundHoldingQuery,
        data_model=NorthFundHolding,
        freshness=_NORTH_FUND_FRESHNESS,
        source_policy=_NORTH_FUND_SOURCE_POLICY,
        examples=[{"description": "Read northbound holding for one stock", "arguments": {"stock_code": "600519"}}],
        tags=["provider-contract", "fund-flow", "northbound", "holding"],
    ),
    "get_north_fund_top": _contract(
        name="get_north_fund_top",
        title="North Fund Top Holdings",
        category="fund_flow",
        description="Read northbound top holding ranking from the existing Eastmoney datacenter path.",
        required_params=[],
        query_model=NorthFundTopQuery,
        data_model=_array_of(NorthFundTop),
        freshness=_NORTH_FUND_FRESHNESS,
        source_policy=_NORTH_FUND_SOURCE_POLICY,
        examples=[{"description": "Read top northbound holdings", "arguments": {"top_n": 20}}],
        tags=["provider-contract", "fund-flow", "northbound", "ranking"],
        standard_model="NorthFundTop",
    ),
    "get_sector_fund_flow": _contract(
        name="get_sector_fund_flow",
        title="Sector Fund Flow",
        category="fund_flow",
        description="Read industry sector fund-flow ranking with DB/cache/Eastmoney/Tushare fallback metadata.",
        required_params=[],
        query_model=SectorFundFlowQuery,
        data_model=_array_of(SectorFundFlow),
        freshness=_SECTOR_FRESHNESS,
        source_policy=_SECTOR_FUND_FLOW_SOURCE_POLICY,
        examples=[{"description": "Read top industry fund flows", "arguments": {"top_n": 20}}],
        tags=["provider-contract", "fund-flow", "sector", "industry"],
        standard_model="SectorFundFlow",
    ),
    "get_concept_fund_flow": _contract(
        name="get_concept_fund_flow",
        title="Concept Fund Flow",
        category="fund_flow",
        description="Read concept board fund-flow ranking through the existing Eastmoney direct API path.",
        required_params=[],
        query_model=ConceptFundFlowQuery,
        data_model=_array_of(ConceptFundFlow),
        freshness=_SECTOR_FRESHNESS,
        source_policy=_CONCEPT_FUND_FLOW_SOURCE_POLICY,
        examples=[{"description": "Read top concept fund flows", "arguments": {"top_n": 20}}],
        tags=["provider-contract", "fund-flow", "concept"],
        standard_model="ConceptFundFlow",
    ),
    "get_dragon_tiger": _contract(
        name="get_dragon_tiger",
        title="Dragon Tiger",
        category="fund_flow",
        description="Read dragon-tiger list data with Sina/Eastmoney fallback and resolved-date quality metadata.",
        required_params=[],
        query_model=DragonTigerQuery,
        data_model=_array_of(DragonTiger),
        freshness=_FUND_FLOW_FRESHNESS,
        source_policy=_DRAGON_TIGER_SOURCE_POLICY,
        examples=[{"description": "Read latest dragon-tiger records", "arguments": {"date": "2026-05-20"}}],
        tags=["provider-contract", "fund-flow", "dragon-tiger"],
        standard_model="DragonTiger",
    ),
    "get_margin_data": _contract(
        name="get_margin_data",
        title="Margin Data",
        category="fund_flow",
        description="Read margin financing/securities-lending detail or market summary via DB/Eastmoney/AkShare paths.",
        required_params=[],
        query_model=MarginDataQuery,
        data_model=_array_of(MarginData),
        freshness=_FUND_FLOW_FRESHNESS,
        source_policy=_MARGIN_SOURCE_POLICY,
        examples=[{"description": "Read recent margin data for a stock", "arguments": {"stock_code": "600519", "days": 30}}],
        tags=["provider-contract", "fund-flow", "margin", "risk"],
        standard_model="MarginData",
    ),
    "get_margin_ranking": _contract(
        name="get_margin_ranking",
        title="Margin Ranking",
        category="fund_flow",
        description="Read margin ranking from DB or Eastmoney datacenter while preserving the existing list shape.",
        required_params=[],
        query_model=MarginRankingQuery,
        data_model=_array_of(MarginRanking),
        freshness=_FUND_FLOW_FRESHNESS,
        source_policy=_MARGIN_SOURCE_POLICY,
        examples=[{"description": "Read margin balance ranking", "arguments": {"top_n": 20, "sort_by": "balance"}}],
        tags=["provider-contract", "fund-flow", "margin", "ranking"],
        standard_model="MarginRanking",
    ),
    "get_block_trades": _contract(
        name="get_block_trades",
        title="Block Trades",
        category="fund_flow",
        description="Read block trade records with Eastmoney backtracking and security metadata enrichment.",
        required_params=[],
        query_model=BlockTradesQuery,
        data_model=_array_of(BlockTrades),
        freshness=_FUND_FLOW_FRESHNESS,
        source_policy=_BLOCK_TRADES_SOURCE_POLICY,
        examples=[{"description": "Read latest block trades for one stock", "arguments": {"stock_code": "600519", "limit": 100}}],
        tags=["provider-contract", "fund-flow", "block-trades"],
        standard_model="BlockTrades",
    ),
    "get_market_blocks": _contract(
        name="get_market_blocks",
        title="Market Blocks",
        category="sector",
        description="Read industry/concept/region blocks with DB-first and AKShare fallback metadata.",
        required_params=[],
        query_model=MarketBlocksQuery,
        data_model=MarketBlocks,
        freshness=_SECTOR_FRESHNESS,
        source_policy=_MARKET_BLOCK_SOURCE_POLICY,
        examples=[{"description": "Read industry blocks", "arguments": {"block_type": "industry", "limit": 50}}],
        tags=["provider-contract", "sector", "blocks", "industry", "concept"],
    ),
    "get_block_stocks": _contract(
        name="get_block_stocks",
        title="Block Stocks",
        category="sector",
        description="Read constituents for a block with TDX/DB/AKShare/Tushare fallback metadata.",
        required_params=["block_code"],
        query_model=BlockStocksQuery,
        data_model=BlockStocks,
        freshness=_SECTOR_FRESHNESS,
        source_policy=_BLOCK_STOCK_SOURCE_POLICY,
        examples=[{"description": "Read constituents for one block", "arguments": {"block_code": "880001"}}],
        tags=["provider-contract", "sector", "blocks", "constituents"],
    ),
    "get_macro_indicator": _contract(
        name="get_macro_indicator",
        title="Macro Indicator",
        category="macro",
        description="Read normalized macro indicator records through existing Tushare/AkShare/curl fallback paths.",
        required_params=["indicator"],
        query_model=MacroIndicatorQuery,
        data_model=MacroIndicator,
        freshness=_MACRO_FRESHNESS,
        source_policy=_MACRO_SOURCE_POLICY,
        examples=[{"description": "Read CPI series", "arguments": {"indicator": "cpi", "limit": 120}}],
        tags=["provider-contract", "macro", "indicator"],
    ),
    "get_option_chain": _contract(
        name="get_option_chain",
        title="Option Chain",
        category="options",
        description="Read SSE ETF option-chain snapshot through the existing Sina/AkShare option path.",
        required_params=["underlying"],
        query_model=OptionChainQuery,
        data_model=OptionChain,
        freshness=_OPTIONS_FRESHNESS,
        source_policy=_OPTIONS_SOURCE_POLICY,
        examples=[{"description": "Read 50ETF option chain", "arguments": {"underlying": "510050", "limit": 200}}],
        tags=["provider-contract", "options", "option-chain", "sse"],
    ),
    "get_trading_dates": _contract(
        name="get_trading_dates",
        title="Trading Calendar",
        category="basic_data",
        description="Read A-share trading dates through the existing TDX-first calendar chain.",
        required_params=[],
        query_model=TradingCalendarQuery,
        data_model=TradingCalendar,
        freshness=_CALENDAR_FRESHNESS,
        source_policy=SourcePolicy(
            priority=["tqcenter.get_trading_dates", "tdx_local.get_trading_dates", "tushare_pro.trade_cal", "akshare.tool_trade_date_hist_sina"],
            local_only_env="TDX_LOCAL_ONLY",
            online_fallback="disabled when TDX_LOCAL_ONLY=1",
            notes=[_TDX_PRIORITY_NOTE],
        ),
        examples=[{"description": "Read the latest trading dates", "arguments": {"market": "SH", "count": 10}}],
        tags=["provider-contract", "calendar", "trading-dates"],
    ),
}

_CONTRACTS.update(_platform_contracts())


def get_provider_tool_contract(name: str) -> dict[str, Any] | None:
    item = _CONTRACTS.get(str(name or "").strip())
    return deepcopy(item) if item else None


def provider_tool_contracts() -> dict[str, dict[str, Any]]:
    return {name: deepcopy(contract) for name, contract in _CONTRACTS.items()}
