"""Provider tool contract registry (market-data contracts + platform merge)."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

from ._shared import *  # noqa: F401,F403 - shared builders/policies/models
from ._shared import _contract
from ._platform_contracts import _platform_contracts

_CONTRACTS: dict[str, dict[str, Any]] = {
    "get_realtime_quote": _contract(
        name="get_realtime_quote",
        title="Equity Quote",
        category="market",
        description="Read a normalized A-share quote while preserving the existing quote data shape.",
        required_params=["code"],
        query_model=EquityQuoteQuery,
        data_model=EquityQuote,
        freshness=_QUOTE_FRESHNESS,
        source_policy=SourcePolicy(
            priority=["db.stock_quotes", "data_source", "tdx_local", "akshare", "sina", "tencent"],
            local_only_env="TDX_LOCAL_ONLY",
            online_fallback="disabled when TDX_LOCAL_ONLY=1",
            notes=[_TDX_PRIORITY_NOTE],
        ),
        examples=[{"description": "Read latest quote", "arguments": {"code": "600519"}}],
        tags=["provider-contract", "equity", "quote", "market"],
    ),
    "get_kline": _contract(
        name="get_kline",
        title="Equity Historical",
        category="market",
        description="Read normalized OHLCV history through the existing kline source priority chain.",
        required_params=["code"],
        query_model=EquityHistoricalQuery,
        data_model=EquityHistorical,
        freshness=_KLINE_FRESHNESS,
        source_policy=SourcePolicy(
            priority=["db.get_klines", "data_source.get_kline", "baostock", "akshare", "tencent"],
            local_only_env="TDX_LOCAL_ONLY",
            online_fallback="disabled by data_source when TDX_LOCAL_ONLY=1",
            notes=[_TDX_PRIORITY_NOTE],
        ),
        examples=[{"description": "Read recent daily bars", "arguments": {"code": "600519", "period": "daily", "limit": 60}}],
        tags=["provider-contract", "equity", "historical", "ohlcv"],
    ),
    "get_kline_data": _contract(
        name="get_kline_data",
        title="Equity Historical Data",
        category="market",
        description="Read OHLCV history with optional date range while keeping the existing data response shape.",
        required_params=["code"],
        query_model=EquityHistoricalQuery,
        data_model=EquityHistorical,
        freshness=_KLINE_FRESHNESS,
        source_policy=SourcePolicy(
            priority=["db.get_klines", "data_source.get_kline", "akshare.stock_zh_a_hist"],
            local_only_env="TDX_LOCAL_ONLY",
            online_fallback="disabled by data_source when TDX_LOCAL_ONLY=1",
            notes=[_TDX_PRIORITY_NOTE],
        ),
        examples=[
            {
                "description": "Read bars for a date range",
                "arguments": {"code": "600519", "start_date": "2026-01-01", "end_date": "2026-03-31"},
            }
        ],
        tags=["provider-contract", "equity", "historical", "date-range"],
    ),
    "get_financials": _contract(
        name="get_financials",
        title="Financial Metrics",
        category="finance",
        description="Read latest normalized financial metrics through AIASK's DB/TDX/Tushare/AkShare/Baostock chain.",
        required_params=["code"],
        query_model=FinancialMetricsQuery,
        data_model=FinancialMetrics,
        freshness=_FINANCIAL_FRESHNESS,
        source_policy=_FINANCIAL_SOURCE_POLICY,
        examples=[{"description": "Read latest financial metrics", "arguments": {"code": "600519"}}],
        tags=["provider-contract", "finance", "financials", "fundamental"],
    ),
    "get_stock_info": _contract(
        name="get_stock_info",
        title="Stock Info",
        category="finance",
        description="Read normalized stock profile fields from the existing stock info tool chain.",
        required_params=["code"],
        query_model=StockInfoQuery,
        data_model=StockInfo,
        freshness=_INFO_FRESHNESS,
        source_policy=_STOCK_INFO_SOURCE_POLICY,
        examples=[{"description": "Read stock profile", "arguments": {"code": "600519"}}],
        tags=["provider-contract", "stock-info", "profile"],
    ),
    "get_stock_fund_flow": _contract(
        name="get_stock_fund_flow",
        title="Stock Fund Flow",
        category="fund_flow",
        description="Read individual stock fund-flow fields while preserving the existing flow response shape.",
        required_params=["code"],
        query_model=StockFundFlowQuery,
        data_model=StockFundFlow,
        freshness=_FUND_FLOW_FRESHNESS,
        source_policy=_STOCK_FUND_FLOW_SOURCE_POLICY,
        examples=[{"description": "Read individual stock fund flow", "arguments": {"code": "600519"}}],
        tags=["provider-contract", "fund-flow", "stock", "moneyflow"],
    ),
    "get_north_fund": _contract(
        name="get_north_fund",
        title="North Fund Flow",
        category="fund_flow",
        description="Read northbound fund-flow history with existing validity and fallback gates.",
        required_params=[],
        query_model=NorthFundFlowQuery,
        data_model=NorthFundFlow,
        freshness=_NORTH_FUND_FRESHNESS,
        source_policy=_NORTH_FUND_SOURCE_POLICY,
        examples=[{"description": "Read recent northbound flow", "arguments": {"days": 30}}],
        tags=["provider-contract", "fund-flow", "northbound"],
    ),
    "get_north_fund_holding": _contract(
        name="get_north_fund_holding",
        title="North Fund Holding",
        category="fund_flow",
        description="Read northbound holding snapshot for one stock from TDX/Eastmoney paths.",
        required_params=["stock_code"],
        query_model=NorthFundHoldingQuery,
        data_model=NorthFundHolding,
        freshness=_NORTH_FUND_FRESHNESS,
        source_policy=_NORTH_FUND_SOURCE_POLICY,
        examples=[{"description": "Read northbound holding for one stock", "arguments": {"stock_code": "600519"}}],
        tags=["provider-contract", "fund-flow", "northbound", "holding"],
    ),
    "get_north_fund_top": _contract(
        name="get_north_fund_top",
        title="North Fund Top Holdings",
        category="fund_flow",
        description="Read northbound top holding ranking from the existing Eastmoney datacenter path.",
        required_params=[],
        query_model=NorthFundTopQuery,
        data_model=_array_of(NorthFundTop),
        freshness=_NORTH_FUND_FRESHNESS,
        source_policy=_NORTH_FUND_SOURCE_POLICY,
        examples=[{"description": "Read top northbound holdings", "arguments": {"top_n": 20}}],
        tags=["provider-contract", "fund-flow", "northbound", "ranking"],
        standard_model="NorthFundTop",
    ),
    "get_sector_fund_flow": _contract(
        name="get_sector_fund_flow",
        title="Sector Fund Flow",
        category="fund_flow",
        description="Read industry sector fund-flow ranking with DB/cache/Eastmoney/Tushare fallback metadata.",
        required_params=[],
        query_model=SectorFundFlowQuery,
        data_model=_array_of(SectorFundFlow),
        freshness=_SECTOR_FRESHNESS,
        source_policy=_SECTOR_FUND_FLOW_SOURCE_POLICY,
        examples=[{"description": "Read top industry fund flows", "arguments": {"top_n": 20}}],
        tags=["provider-contract", "fund-flow", "sector", "industry"],
        standard_model="SectorFundFlow",
    ),
    "get_concept_fund_flow": _contract(
        name="get_concept_fund_flow",
        title="Concept Fund Flow",
        category="fund_flow",
        description="Read concept board fund-flow ranking through the existing Eastmoney direct API path.",
        required_params=[],
        query_model=ConceptFundFlowQuery,
        data_model=_array_of(ConceptFundFlow),
        freshness=_SECTOR_FRESHNESS,
        source_policy=_CONCEPT_FUND_FLOW_SOURCE_POLICY,
        examples=[{"description": "Read top concept fund flows", "arguments": {"top_n": 20}}],
        tags=["provider-contract", "fund-flow", "concept"],
        standard_model="ConceptFundFlow",
    ),
    "get_dragon_tiger": _contract(
        name="get_dragon_tiger",
        title="Dragon Tiger",
        category="fund_flow",
        description="Read dragon-tiger list data with Sina/Eastmoney fallback and resolved-date quality metadata.",
        required_params=[],
        query_model=DragonTigerQuery,
        data_model=_array_of(DragonTiger),
        freshness=_FUND_FLOW_FRESHNESS,
        source_policy=_DRAGON_TIGER_SOURCE_POLICY,
        examples=[{"description": "Read latest dragon-tiger records", "arguments": {"date": "2026-05-20"}}],
        tags=["provider-contract", "fund-flow", "dragon-tiger"],
        standard_model="DragonTiger",
    ),
    "get_margin_data": _contract(
        name="get_margin_data",
        title="Margin Data",
        category="fund_flow",
        description="Read margin financing/securities-lending detail or market summary via DB/Eastmoney/AkShare paths.",
        required_params=[],
        query_model=MarginDataQuery,
        data_model=_array_of(MarginData),
        freshness=_FUND_FLOW_FRESHNESS,
        source_policy=_MARGIN_SOURCE_POLICY,
        examples=[{"description": "Read recent margin data for a stock", "arguments": {"stock_code": "600519", "days": 30}}],
        tags=["provider-contract", "fund-flow", "margin", "risk"],
        standard_model="MarginData",
    ),
    "get_margin_ranking": _contract(
        name="get_margin_ranking",
        title="Margin Ranking",
        category="fund_flow",
        description="Read margin ranking from DB or Eastmoney datacenter while preserving the existing list shape.",
        required_params=[],
        query_model=MarginRankingQuery,
        data_model=_array_of(MarginRanking),
        freshness=_FUND_FLOW_FRESHNESS,
        source_policy=_MARGIN_SOURCE_POLICY,
        examples=[{"description": "Read margin balance ranking", "arguments": {"top_n": 20, "sort_by": "balance"}}],
        tags=["provider-contract", "fund-flow", "margin", "ranking"],
        standard_model="MarginRanking",
    ),
    "get_block_trades": _contract(
        name="get_block_trades",
        title="Block Trades",
        category="fund_flow",
        description="Read block trade records with Eastmoney backtracking and security metadata enrichment.",
        required_params=[],
        query_model=BlockTradesQuery,
        data_model=_array_of(BlockTrades),
        freshness=_FUND_FLOW_FRESHNESS,
        source_policy=_BLOCK_TRADES_SOURCE_POLICY,
        examples=[{"description": "Read latest block trades for one stock", "arguments": {"stock_code": "600519", "limit": 100}}],
        tags=["provider-contract", "fund-flow", "block-trades"],
        standard_model="BlockTrades",
    ),
    "get_market_blocks": _contract(
        name="get_market_blocks",
        title="Market Blocks",
        category="sector",
        description="Read industry/concept/region blocks with DB-first and AKShare fallback metadata.",
        required_params=[],
        query_model=MarketBlocksQuery,
        data_model=MarketBlocks,
        freshness=_SECTOR_FRESHNESS,
        source_policy=_MARKET_BLOCK_SOURCE_POLICY,
        examples=[{"description": "Read industry blocks", "arguments": {"block_type": "industry", "limit": 50}}],
        tags=["provider-contract", "sector", "blocks", "industry", "concept"],
    ),
    "get_block_stocks": _contract(
        name="get_block_stocks",
        title="Block Stocks",
        category="sector",
        description="Read constituents for a block with TDX/DB/AKShare/Tushare fallback metadata.",
        required_params=["block_code"],
        query_model=BlockStocksQuery,
        data_model=BlockStocks,
        freshness=_SECTOR_FRESHNESS,
        source_policy=_BLOCK_STOCK_SOURCE_POLICY,
        examples=[{"description": "Read constituents for one block", "arguments": {"block_code": "880001"}}],
        tags=["provider-contract", "sector", "blocks", "constituents"],
    ),
    "get_macro_indicator": _contract(
        name="get_macro_indicator",
        title="Macro Indicator",
        category="macro",
        description="Read normalized macro indicator records through existing Tushare/AkShare/curl fallback paths.",
        required_params=["indicator"],
        query_model=MacroIndicatorQuery,
        data_model=MacroIndicator,
        freshness=_MACRO_FRESHNESS,
        source_policy=_MACRO_SOURCE_POLICY,
        examples=[{"description": "Read CPI series", "arguments": {"indicator": "cpi", "limit": 120}}],
        tags=["provider-contract", "macro", "indicator"],
    ),
    "get_option_chain": _contract(
        name="get_option_chain",
        title="Option Chain",
        category="options",
        description="Read SSE ETF option-chain snapshot through the existing Sina/AkShare option path.",
        required_params=["underlying"],
        query_model=OptionChainQuery,
        data_model=OptionChain,
        freshness=_OPTIONS_FRESHNESS,
        source_policy=_OPTIONS_SOURCE_POLICY,
        examples=[{"description": "Read 50ETF option chain", "arguments": {"underlying": "510050", "limit": 200}}],
        tags=["provider-contract", "options", "option-chain", "sse"],
    ),
    "get_trading_dates": _contract(
        name="get_trading_dates",
        title="Trading Calendar",
        category="basic_data",
        description="Read A-share trading dates through the existing TDX-first calendar chain.",
        required_params=[],
        query_model=TradingCalendarQuery,
        data_model=TradingCalendar,
        freshness=_CALENDAR_FRESHNESS,
        source_policy=SourcePolicy(
            priority=["tqcenter.get_trading_dates", "tdx_local.get_trading_dates", "tushare_pro.trade_cal", "akshare.tool_trade_date_hist_sina"],
            local_only_env="TDX_LOCAL_ONLY",
            online_fallback="disabled when TDX_LOCAL_ONLY=1",
            notes=[_TDX_PRIORITY_NOTE],
        ),
        examples=[{"description": "Read the latest trading dates", "arguments": {"market": "SH", "count": 10}}],
        tags=["provider-contract", "calendar", "trading-dates"],
    ),
}

_CONTRACTS.update(_platform_contracts())


def get_provider_tool_contract(name: str) -> dict[str, Any] | None:
    item = _CONTRACTS.get(str(name or "").strip())
    return deepcopy(item) if item else None


def provider_tool_contracts() -> dict[str, dict[str, Any]]:
    return {name: deepcopy(contract) for name, contract in _CONTRACTS.items()}
