import type {
  FactoryAutonomyTaskBrief,
  FactoryFeedbackGeneratorModeControl,
  FactoryQualityBaseline,
  FactoryRecentRunDiagnostics,
  FactorySignalQualityRegistry,
  FactoryValidationFamilyQualityPanelItem,
} from './core';

export type FactoryRunSummary = {
    trace_id?: string;
    prediction_trace_id?: string;
    lifecycle_feedback_input_contract_version?: string;
    lifecycle_feedback_input_available?: boolean;
    budget_feedback_available?: boolean;
    budget_feedback_family_count?: number;
    budget_feedback_strategy_count?: number;
    budget_feedback_target_pool_scope_count?: number;
    budget_feedback_generator_mode_scope_count?: number;
    budget_feedback_runtime_alert_count?: number;
    budget_feedback_runtime_risk_event_count?: number;
    budget_feedback_promotion_review_count?: number;
    budget_feedback_promotion_review_status_counts?: Record<string, number>;
    blocked_feedback_task_count?: number;
    planned_feedback_cooldown_task_count?: number;
    planned_feedback_control_mode_counts?: Record<string, number>;
    planned_feedback_target_pool_control_mode_counts?: Record<string, number>;
    planned_feedback_generator_mode_control_mode_counts?: Record<string, number>;
    selected_feedback_control_mode_counts?: Record<string, number>;
    selected_feedback_target_pool_control_mode_counts?: Record<string, number>;
    selected_feedback_generator_mode_control_mode_counts?: Record<string, number>;
    feedback_control_mode_counts?: Record<string, number>;
    feedback_target_pool_control_mode_counts?: Record<string, number>;
    feedback_generator_mode_control_mode_counts?: Record<string, number>;
    suppressed_families?: string[];
    suppressed_target_pools?: string[];
    suppressed_generator_modes?: string[];
    external_llm_provider_control_mode?: string;
    external_llm_provider_control_reasons?: string[];
    external_llm_provider_suppressed?: boolean;
    external_llm_provider_cooldown?: boolean;
    generator_mode_controls?: Record<string, FactoryFeedbackGeneratorModeControl>;
    stage_status_counts?: Record<string, number>;
    failed_stage_count?: number;
    partial_stage_count?: number;
    skipped_stage_count?: number;
    hard_failure_count?: number;
    degraded_stage_count?: number;
    failed_stages?: string[];
    partial_stages?: string[];
    skipped_stages?: string[];
    skip_reason?: string;
    skip_reasons?: string[];
    persistence_failure_count?: number;
    persistence_failures?: Array<{
        operation?: string;
        stage?: string | null;
        error_type?: string;
        error?: string;
    }>;
    candidates_spawned?: number;
    candidates_passed_backtest?: number;
    candidates_after_dedup?: number;
    passed_quality_gate?: number;
    autonomy_generated?: number;
    autonomy_task_count?: number;
    event_task_count?: number;
    snapshot_task_count?: number;
    snapshot_degraded?: boolean;
    snapshot_completion_ratio?: number;
    snapshot_failure_reason_count?: number;
    task_source_counts?: Record<string, number>;
    scanner_task_types?: Record<string, number>;
    event_snapshot_mixed?: boolean;
    autonomy_task_briefs?: FactoryAutonomyTaskBrief[];
    submitted?: number;
    submit_stage_entered?: boolean;
    submit_stage_status?: string | null;
    eliminated?: number;
    elapsed_seconds?: number;
    constraint_violation_count?: number;
    target_symbol_intersection_ratio_avg?: number;
    universe_expansion_count?: number;
    preference_mismatch_warning_count?: number;
    attempt_adjusted_gate_failed?: number;
    attempt_adjusted_score_avg?: number;
    event_window_contamination_warning_count?: number;
    cost_audit_missing_count?: number;
    deflated_sharpe_proxy_avg?: number;
    deflated_sharpe_ratio_avg?: number;
    high_pbo_proxy_count?: number;
    high_pbo_count?: number;
    formal_multiple_testing_count?: number;
    weak_white_reality_check_count?: number;
    weak_hansen_spa_count?: number;
    refresh_metrics_only_count?: number;
    spawn_revision_from_existing_count?: number;
    validation_grade_distribution?: Record<string, number>;
    raw_validation_grade_distribution?: Record<string, number>;
    effective_validation_grade_distribution?: Record<string, number>;
    raw_validation_total_score_mean?: number;
    raw_validation_total_score_p50?: number;
    raw_validation_total_score_p90?: number;
    raw_validation_a_rate?: number;
    raw_validation_b_rate?: number;
    raw_validation_c_rate?: number;
    raw_validation_d_rate?: number;
    strict_incubation_ready_count?: number;
    strict_incubation_ready_rate?: number;
    live_candidate_ready_count?: number;
    live_candidate_ready_rate?: number;
    raw_b_or_above_count?: number;
    raw_b_or_above_rate?: number;
    strict_ready_given_raw_b_count?: number;
    strict_ready_given_raw_b_rate?: number;
    live_ready_given_raw_b_count?: number;
    live_ready_given_raw_b_rate?: number;
    strict_live_alignment_gap_count?: number;
    strict_live_alignment_gap_rate?: number;
    strict_live_alignment_status_counts?: Record<string, number>;
    validation_family_quality_panel?: FactoryValidationFamilyQualityPanelItem[];
    prediction_quality_distribution?: Record<string, number>;
    execution_quality_distribution?: Record<string, number>;
    evidence_alignment_distribution?: Record<string, number>;
    confidence_contract_ready_rate?: number;
};

export type FactoryStatusResponse = {
    running?: boolean;
    run_time?: string;
    last_run?: string | null;
    last_summary?: FactoryRunSummary;
    last_validation_grade_distribution?: Record<string, number>;
    last_raw_validation_grade_distribution?: Record<string, number>;
    last_effective_validation_grade_distribution?: Record<string, number>;
    last_raw_validation_total_score_mean?: number;
    last_raw_validation_total_score_p50?: number;
    last_raw_validation_total_score_p90?: number;
    last_raw_validation_a_rate?: number;
    last_raw_validation_b_rate?: number;
    last_raw_validation_c_rate?: number;
    last_raw_validation_d_rate?: number;
    last_strict_incubation_ready_count?: number;
    last_strict_incubation_ready_rate?: number;
    last_live_candidate_ready_count?: number;
    last_live_candidate_ready_rate?: number;
    last_raw_b_or_above_count?: number;
    last_raw_b_or_above_rate?: number;
    last_strict_ready_given_raw_b_count?: number;
    last_strict_ready_given_raw_b_rate?: number;
    last_live_ready_given_raw_b_count?: number;
    last_live_ready_given_raw_b_rate?: number;
    recent_run_diagnostics?: FactoryRecentRunDiagnostics;
    last_validation_family_quality_panel?: FactoryValidationFamilyQualityPanelItem[];
    quality_baseline?: FactoryQualityBaseline;
    high_confidence_enabled?: boolean;
    evidence_contract_enabled?: boolean;
    confidence_diagnostics_enabled?: boolean;
    execution_audit_enabled?: boolean;
    quality_ui_v2_enabled?: boolean;
    research_protocol_v2_enabled?: boolean;
    gate_model_v2_enabled?: boolean;
    trace_ledger_v2_enabled?: boolean;
    feedback_v2_enabled?: boolean;
    trace_ledger_v2_implemented?: boolean;
    governance_gate_report_v2_implemented?: boolean;
    execution_audit_entity_chain_available?: boolean;
    spec_completeness_mode?: 'warn' | 'revise' | 'reject' | string;
    signal_quality_registry?: FactorySignalQualityRegistry;
    feature_flags?: {
        high_confidence_enabled?: boolean;
        evidence_contract_enabled?: boolean;
        confidence_diagnostics_enabled?: boolean;
        execution_audit_enabled?: boolean;
        quality_ui_v2_enabled?: boolean;
        research_protocol_v2_enabled?: boolean;
        gate_model_v2_enabled?: boolean;
        trace_ledger_v2_enabled?: boolean;
        feedback_v2_enabled?: boolean;
        spec_completeness_mode?: 'warn' | 'revise' | 'reject' | string;
    };
    last_result?: {
        status?: string;
        error?: string;
    };
};

export type CapabilityResponse = {
    daily_snapshot?: boolean;
    paper_incubation?: boolean;
    incubation_pipeline?: boolean;
    runtime_risk?: boolean;
    risk_snapshots?: boolean;
    risk_recovery?: boolean;
    execution_risk?: boolean;
    runtime_controls?: boolean;
    promotion_pipeline?: boolean;
    projection_snapshots?: boolean;
    event_replay?: boolean;
    vector_platform?: boolean;
    vector_governance?: boolean;
    persistent_vector_index?: boolean;
    ann_vector_search?: boolean;
    ai_generation?: boolean;
    multi_agent_review?: boolean;
    quality_governance?: boolean;
    domain_events?: boolean;
    domain_projection?: boolean;
    runtime_cycle?: boolean;
    high_confidence_enabled?: boolean;
    evidence_contract_enabled?: boolean;
    confidence_diagnostics_enabled?: boolean;
    execution_audit_enabled?: boolean;
    quality_ui_v2_enabled?: boolean;
    research_protocol_v2_enabled?: boolean;
    gate_model_v2_enabled?: boolean;
    trace_ledger_v2_enabled?: boolean;
    feedback_v2_enabled?: boolean;
    trace_ledger_v2_implemented?: boolean;
    governance_gate_report_v2_implemented?: boolean;
    execution_audit_entity_chain_available?: boolean;
    spec_completeness_mode?: 'warn' | 'revise' | 'reject' | string;
    signal_quality_registry?: FactorySignalQualityRegistry;
    high_confidence_feature_flags?: {
        high_confidence_enabled?: boolean;
        evidence_contract_enabled?: boolean;
        confidence_diagnostics_enabled?: boolean;
        execution_audit_enabled?: boolean;
        quality_ui_v2_enabled?: boolean;
        research_protocol_v2_enabled?: boolean;
        gate_model_v2_enabled?: boolean;
        trace_ledger_v2_enabled?: boolean;
        feedback_v2_enabled?: boolean;
        spec_completeness_mode?: 'warn' | 'revise' | 'reject' | string;
    };
    system_capabilities?: Record<string, unknown>;
    actor_permissions?: {
        can_run_factory?: boolean;
        can_ai_generate?: boolean;
        can_create_personal_strategy?: boolean;
        can_edit_own_strategy?: boolean;
        can_create_paper_session?: boolean;
        can_view_operator_panels?: boolean;
    };
};

export type DailySnapshotResponse = {
    snapshot_date?: string;
    fear_greed_index?: number;
    degraded?: boolean;
    failure_reasons?: string[];
    missing_fields?: string[];
    hot_sectors?: string[];
    cold_sectors?: string[];
    summary?: {
        listed_count?: number;
    };
    completeness?: {
        completion_ratio?: number;
    };
};

export type FactoryRunListItem = {
    run_id?: string;
    trace_id?: string | null;
    prediction_trace_id?: string | null;
    status?: string;
    started_at?: string;
    completed_at?: string | null;
    elapsed_seconds?: number;
    submit_stage_entered?: boolean;
    submit_stage_status?: string | null;
    error?: string | null;
    summary?: FactoryRunSummary;
    stages?: Record<string, Record<string, string | number | boolean | null | undefined>>;
    pipeline?: {
        trace_id?: string | null;
        failed_stage?: string | null;
        partial_stage?: string | null;
        skipped_stage?: string | null;
        stage_order?: string[];
        total_stage_count?: number;
        completed_stage_count?: number;
        partial_stage_count?: number;
        skipped_stage_count?: number;
        failed_stage_count?: number;
        stage_status_counts?: Record<string, number>;
    };
};

export type FactoryRunsResponse = {
    dto_version?: string;
    latest?: FactoryRunListItem | null;
    items?: FactoryRunListItem[];
    count?: number;
};
