// Auto-generated from packages/akshare-mcp Python contract surface.
// Do not edit manually.

export const STRATEGY_MANAGER_CONTRACT_VERSION = 'strategy_manager.contract.v1' as const;

export const STRATEGY_MANAGER_ACTIONS = [
  'help',
  'create',
  'publish',
  'archive',
  'list',
  'detail',
  'review_report',
  'events',
  'update_metrics',
  'review',
  'subscribe',
  'unsubscribe',
  'my_subscriptions',
  'my_strategies',
  'fork_strategy',
  'update_strategy',
  'delete_personal_strategy',
  'paper_session_get',
  'paper_session_get_or_create',
  'rank',
  'capabilities',
  'daily_snapshot',
  'daily_snapshots',
  'get_signals',
  'get_forward_returns',
  'get_signal_stats',
  'review_report_recheck',
  'submission_replay',
  'submit',
  'lifecycle_scan',
  'incubation_overview',
  'closure_review',
  'factory_status',
  'factory_run_once',
  'factory_dispatch_run',
  'factory_dispatch_status',
  'factory_runs',
  'factory_run_detail',
  'factory_topn_latest',
  'factory_run_topn',
  'execution_audit_verification',
  'execution_audit_acceptance',
  'incubation_accounts',
  'incubation_metrics',
  'paper_account',
  'paper_orders',
  'paper_nav',
  'incubation_sync_run',
  'incubation_pipeline',
  'incubation_pipeline_run',
  'risk_events',
  'risk_snapshots',
  'risk_scan_run',
  'risk_recovery',
  'resolve_risk_event',
  'runtime_alerts',
  'runtime_alert_dispatch_run',
  'runtime_alert_ack',
  'runtime_control',
  'runtime_control_set',
  'promotion_reviews',
  'promotion_review_run',
  'runtime_cycle_status',
  'runtime_cycle_run',
  'domain_events',
  'domain_projection',
  'domain_projection_snapshot',
  'domain_projection_rebuild',
  'vector_profiles',
  'vector_indexes',
  'vector_index_snapshots',
  'vector_ann_search',
  'vector_reconcile',
  'vector_rebuild',
  'vector_health',
  'vector_cleanup',
  'ai_generate',
  'ai_optimize_personal_strategy',
  'ai_experiments',
  'task_runs',
] as const;

export type StrategyManagerAction = typeof STRATEGY_MANAGER_ACTIONS[number];
