

def _rule_template_contract(strategy_type: str) -> dict[str, Any]:
    contracts: dict[str, dict[str, Any]] = {
        'momentum': {
            'template_generation_profile': 'conservative_momentum',
            'holding_horizon': {'min_days': 14, 'max_days': 42},
            'trade_plan': {'entry_bias': 'trend_persistence_confirmation', 'exit_bias': 'false_breakout_or_momentum_decay'},
            'risk_rules': {'stop_loss_pct': 0.07, 'take_profit_pct': 0.2, 'max_holding_days': 42, 'max_position_pct': 0.16},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'periodic_rebalance', 'frequency_days': 14},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'trend_score_tilt',
                'max_position_pct': 0.16,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 5,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
            },
            'validation_profile': {
                'profile': 'trade_rule_validation',
                'validation_focus': 'target_plus_representative',
                'primary_validation_layer': 'target',
            },
            'family_specialization': {
                'trend_persistence_regime': 'trend_expansion_with_relative_strength_persistence',
                'false_breakout_filter': 'prefer_volume_confirmed_breakout_and_positive_trend_slope',
                'peer_selection_mode': 'target_plus_dynamic_family_peer',
            },
            'targeting_policy': {
                'target_symbol_policy': 'dynamic_signal_universe',
                'universe_scope': 'trend_leaders_liquid',
                'universe_expansion_policy': 'trend_leaders_only',
            },
            'rule_template_contract': {
                'template_generation_profile': 'conservative_momentum',
                'applicable_universe': {'market_cap': 'mid_large', 'liquidity': 'high', 'style_bias': 'trend_expansion'},
                'target_layer': 'target',
                'default_risk_constraints': {'stop_loss_pct': 0.07, 'take_profit_pct': 0.2, 'max_holding_days': 36, 'max_position_pct': 0.16},
                'portfolio_weight_method': 'trend_score_tilt',
            },
        },
        'ma_cross': {
            'template_generation_profile': 'conservative_ma_cross',
            'holding_horizon': {'min_days': 14, 'max_days': 48},
            'trade_plan': {'entry_bias': 'adaptive_cross_with_volume_confirmation', 'exit_bias': 'range_reentry_or_cross_failure'},
            'risk_rules': {'stop_loss_pct': 0.07, 'take_profit_pct': 0.18, 'max_holding_days': 48, 'max_position_pct': 0.14},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'periodic_rebalance', 'frequency_days': 12},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'cross_strength_tilt',
                'max_position_pct': 0.14,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 5,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
            },
            'validation_profile': {
                'profile': 'trade_rule_validation',
                'validation_focus': 'target_plus_representative',
                'primary_validation_layer': 'target',
            },
            'family_specialization': {
                'adaptive_span_logic': 'fast_slow_span_scaled_by_regime_and_noise_level',
                'range_filter': 'avoid_crosses_when_long_ma_is_flat_and_price_is_range_bound',
                'volume_confirmation': 'prefer_crosses_with_volume_ratio_confirmation',
            },
            'targeting_policy': {
                'target_symbol_policy': 'dynamic_signal_universe',
                'universe_scope': 'trend_followers_liquid',
                'universe_expansion_policy': 'trend_leaders_only',
            },
            'rule_template_contract': {
                'template_generation_profile': 'conservative_ma_cross',
                'applicable_universe': {'market_cap': 'mid_large', 'liquidity': 'high', 'style_bias': 'trend_following'},
                'target_layer': 'target',
                'default_risk_constraints': {'stop_loss_pct': 0.07, 'take_profit_pct': 0.18, 'max_holding_days': 48, 'max_position_pct': 0.14},
                'portfolio_weight_method': 'cross_strength_tilt',
            },
        },
        'quality_factor': {
            'template_generation_profile': 'conservative_quality',
            'holding_horizon': {'min_days': 30, 'max_days': 84},
            'trade_plan': {'entry_bias': 'quality_stability_with_trend_confirmation', 'exit_bias': 'quality_drift_or_rank_decay'},
            'risk_rules': {'stop_loss_pct': 0.08, 'take_profit_pct': 0.18, 'max_holding_days': 84, 'max_position_pct': 0.12},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'periodic_rebalance', 'frequency_days': 28},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'quality_rank_weight',
                'max_position_pct': 0.12,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 5,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
            },
            'validation_profile': {
                'profile': 'trade_rule_validation',
                'validation_focus': 'candidate_target_only',
                'primary_validation_layer': 'target',
            },
            'family_specialization': {
                'rebalance_bias': 'low_frequency_quality_refresh',
                'quality_trend_resonance': 'require_fundamental_stability_and_price_trend_alignment',
                'quality_drift_detection': 'monitor_rank_margin_cashflow_stability_deterioration',
                'peer_selection_mode': 'target_plus_dynamic_family_peer',
                'compounding_window': 'prefer_slow_compounding_validation_window',
            },
            'targeting_policy': {
                'target_symbol_policy': 'quality_leaders_focus',
                'universe_scope': 'liquid_quality_bluechips',
                'universe_expansion_policy': 'quality_peers_only',
            },
            'rule_template_contract': {
                'template_generation_profile': 'conservative_quality',
                'applicable_universe': {'market_cap': 'mid_large', 'liquidity': 'high', 'style_bias': 'quality_compounders'},
                'target_layer': 'target',
                'default_risk_constraints': {'stop_loss_pct': 0.08, 'take_profit_pct': 0.18, 'max_holding_days': 84, 'max_position_pct': 0.14},
                'portfolio_weight_method': 'quality_rank_weight',
            },
        },
        'volatility_breakout': {
            'template_generation_profile': 'conservative_breakout',
            'holding_horizon': {'min_days': 3, 'max_days': 15},
            'trade_plan': {'entry_bias': 'breakout_confirmation', 'exit_bias': 'trailing_stop_or_time_stop'},
            'risk_rules': {'stop_loss_pct': 0.07, 'take_profit_pct': 0.16, 'max_holding_days': 15, 'max_position_pct': 0.18},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'signal_rebalance', 'frequency_days': 3},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'volatility_budget',
                'max_position_pct': 0.18,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 6,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
            },
            'validation_profile': {
                'profile': 'trade_rule_validation',
                'validation_focus': 'target_plus_representative',
                'primary_validation_layer': 'target',
            },
            'targeting_policy': {
                'target_symbol_policy': 'dynamic_signal_universe',
                'universe_scope': 'liquid_large_mid',
                'universe_expansion_policy': 'trend_leaders_only',
            },
            'rule_template_contract': {
                'template_generation_profile': 'conservative_breakout',
                'applicable_universe': {'market_cap': 'mid_large', 'liquidity': 'high', 'style_bias': 'trend_expansion'},
                'target_layer': 'target',
                'default_risk_constraints': {'stop_loss_pct': 0.07, 'take_profit_pct': 0.16, 'max_holding_days': 15, 'max_position_pct': 0.18},
                'portfolio_weight_method': 'volatility_budget',
            },
        },
        'rsi': {
            'template_generation_profile': 'high_precision_mean_reversion',
            'holding_horizon': {'min_days': 2, 'max_days': 8, 'expected_turnover_band': 'low'},
            'trade_plan': {'entry_bias': 'oversold_repair_with_mean_reversion_confirmation', 'exit_bias': 'mean_reversion_completion_or_rsi_reset'},
            'risk_rules': {'stop_loss_pct': 0.04, 'take_profit_pct': 0.1, 'max_holding_days': 8, 'max_position_pct': 0.12},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'signal_rebalance', 'frequency_days': 3},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'high_precision_repair_weight',
                'max_position_pct': 0.12,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 4,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
                'market_impact_bps': 1.0,
                'capacity_bucket': 'small',
            },
            'validation_profile': {
                'profile': 'trade_rule_validation',
                'validation_focus': 'target_plus_representative',
                'primary_validation_layer': 'target',
                'objective_profile': 'high_precision',
                'trade_density_preference': 'low',
                'regime_required': True,
                'cost_robust_required': True,
                'entry_selectivity': 'strict',
                'preferred_regime': 'oversold_repair_with_stabilizing_liquidity',
                'avoid_regime': 'downtrend_acceleration_or_noise_chop',
            },
            'family_specialization': {
                'mean_reversion_confirmation': 'require_oversold_and_price_dislocation_with_stabilization',
                'repair_confirmation': 'require_rebound_from_recent_low_and_rsi_reclaim_before_entry',
                'entry_regime_filter': 'bear_calm_or_bear_volatile_only',
                'entry_selectivity': 'strict_repair_only',
                'noise_filter': 'path_noise_ratio_ceiling_6',
                'exit_discipline': 'mean_reversion_exit_after_4_bars_or_time_stop_6_bars',
                'adverse_regime_exit': 'exit_when_range_volatile_noise_spikes_after_entry',
                'event_semantics': 'stateful_entry_exit_masks',
                'failure_mode_focus': 'catching_falling_knife_or_overtrading',
                'holding_bias': 'repair_window_hold_2_to_8_days',
                'rebalance_bias': 'signal_rebalance_every_3_days',
            },
            'targeting_policy': {
                'target_symbol_policy': 'dynamic_signal_universe',
                'universe_scope': 'liquid_repair_candidates',
                'universe_expansion_policy': 'oversold_repair_only',
            },
            'holding_rationale': '只在熊市超跌后的修复阶段参与，优先等待止跌且噪声可控的窗口，达到均值回归或时间止损即退出，避免在中性噪声阶段频繁抄底。',
            'position_model': 'equal_weight',
            'capacity_assumption': {'max_position_pct': 0.12, 'capacity_bucket': 'small', 'symbol_count': 4},
            'market_regime_assumption': {
                'summary': '超跌后的熊市修复阶段更有效，需要避免下跌加速和高噪声横盘。',
                'preferred_regime': 'oversold_repair_with_stabilizing_liquidity',
                'avoid_regime': 'downtrend_acceleration_or_noise_chop',
            },
            'failure_mode': {
                'primary_failure_mode': 'downtrend_acceleration',
                'secondary_failure_mode': 'range_bound_overtrading',
                'invalidators': ['no_stabilization_after_entry', 'cost_drag_exceeds_repair_edge'],
            },
            'rule_template_contract': {
                'template_generation_profile': 'high_precision_mean_reversion',
                'applicable_universe': {'market_cap': 'all_liquid', 'liquidity': 'high', 'style_bias': 'oversold_repair'},
                'target_layer': 'target',
                'default_risk_constraints': {'stop_loss_pct': 0.04, 'take_profit_pct': 0.1, 'max_holding_days': 8, 'max_position_pct': 0.12},
                'portfolio_weight_method': 'high_precision_repair_weight',
            },
        },
        'gap_fill': {
            'template_generation_profile': 'conservative_mean_reversion',
            'holding_horizon': {'min_days': 1, 'max_days': 8},
            'trade_plan': {'entry_bias': 'gap_repair_confirmation', 'exit_bias': 'mean_reversion_completion'},
            'risk_rules': {'stop_loss_pct': 0.05, 'take_profit_pct': 0.12, 'max_holding_days': 8, 'max_position_pct': 0.14},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'signal_rebalance', 'frequency_days': 2},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'repair_equal_weight',
                'max_position_pct': 0.14,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 5,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
            },
            'validation_profile': {
                'profile': 'trade_rule_validation',
                'validation_focus': 'target_plus_representative',
                'primary_validation_layer': 'target',
            },
            'targeting_policy': {
                'target_symbol_policy': 'dynamic_signal_universe',
                'universe_scope': 'liquid_repair_candidates',
                'universe_expansion_policy': 'oversold_repair_only',
            },
            'rule_template_contract': {
                'template_generation_profile': 'conservative_mean_reversion',
                'applicable_universe': {'market_cap': 'all_liquid', 'liquidity': 'medium_high', 'style_bias': 'oversold_repair'},
                'target_layer': 'target',
                'default_risk_constraints': {'stop_loss_pct': 0.05, 'take_profit_pct': 0.12, 'max_holding_days': 8, 'max_position_pct': 0.14},
                'portfolio_weight_method': 'repair_equal_weight',
            },
        },
        'mean_reversion_short': {
            'template_generation_profile': 'conservative_mean_reversion',
            'holding_horizon': {'min_days': 1, 'max_days': 7},
            'trade_plan': {'entry_bias': 'short_horizon_reversal', 'exit_bias': 'time_stop_or_signal_reset'},
            'risk_rules': {'stop_loss_pct': 0.05, 'take_profit_pct': 0.1, 'max_holding_days': 7, 'max_position_pct': 0.12},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'signal_rebalance', 'frequency_days': 2},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'short_horizon_equal_weight',
                'max_position_pct': 0.12,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 5,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
            },
            'validation_profile': {
                'profile': 'trade_rule_validation',
                'validation_focus': 'target_plus_representative',
                'primary_validation_layer': 'target',
            },
            'targeting_policy': {
                'target_symbol_policy': 'dynamic_signal_universe',
                'universe_scope': 'liquid_defensive_reversion',
                'universe_expansion_policy': 'short_horizon_only',
            },
            'rule_template_contract': {
                'template_generation_profile': 'conservative_mean_reversion',
                'applicable_universe': {'market_cap': 'all_liquid', 'liquidity': 'high', 'style_bias': 'defensive_mean_reversion'},
                'target_layer': 'target',
                'default_risk_constraints': {'stop_loss_pct': 0.05, 'take_profit_pct': 0.1, 'max_holding_days': 7, 'max_position_pct': 0.12},
                'portfolio_weight_method': 'short_horizon_equal_weight',
            },
        },
        'macro_timing': {
            'template_generation_profile': 'high_precision_regime_timing',
            'holding_horizon': {'min_days': 6, 'max_days': 24, 'expected_turnover_band': 'low'},
            'trade_plan': {'entry_bias': 'panic_repair_after_regime_confirmation', 'exit_bias': 'greed_extreme_or_regime_break'},
            'risk_rules': {'stop_loss_pct': 0.06, 'take_profit_pct': 0.16, 'max_holding_days': 24, 'max_position_pct': 0.14},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'regime_rebalance', 'frequency_days': 7},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'regime_conviction_tilt',
                'max_position_pct': 0.14,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 4,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
                'market_impact_bps': 1.0,
                'capacity_bucket': 'mid',
            },
            'validation_profile': {
                'profile': 'macro_regime_validation',
                'validation_focus': 'target_plus_representative',
                'primary_validation_layer': 'target',
                'objective_profile': 'high_precision',
                'trade_density_preference': 'low',
                'regime_required': True,
                'cost_robust_required': True,
                'entry_selectivity': 'strict',
                'preferred_regime': 'panic_repair_with_volatility_stabilization',
                'avoid_regime': 'mid_regime_whipsaw',
            },
            'family_specialization': {
                'regime_confirmation': 'require_fear_recovery_and_volatility_stabilization_before_entry',
                'whipsaw_filter': 'avoid_mid_regime_flip_flops_and_reenter_only_after_cooldown',
                'holding_bias': 'regime_hold_6_to_24_days',
                'rebalance_bias': 'regime_rebalance_every_7_days',
            },
            'targeting_policy': {
                'target_symbol_policy': 'dynamic_signal_universe',
                'universe_scope': 'liquid_defensive_core',
                'universe_expansion_policy': 'macro_regime_only',
            },
            'holding_rationale': '只在恐慌充分释放后等待风险偏好和波动结构同步修复再入场，中性区间不频繁切换，避免宏观噪声抽打。',
            'position_model': 'equal_weight',
            'capacity_assumption': {'max_position_pct': 0.14, 'capacity_bucket': 'mid', 'symbol_count': 4},
            'market_regime_assumption': {
                'summary': '极端恐慌后波动回落、风险偏好修复的阶段更有效，需要避免中性区间的来回抽打。',
                'preferred_regime': 'panic_repair_with_volatility_stabilization',
                'avoid_regime': 'mid_regime_whipsaw',
            },
            'failure_mode': {
                'primary_failure_mode': 'regime_whipsaw',
                'secondary_failure_mode': 'late_entry_after_fear_release',
                'invalidators': ['fear_signal_not_confirmed_by_stabilization', 'cost_drag_exceeds_regime_edge'],
            },
            'rule_template_contract': {
                'template_generation_profile': 'high_precision_regime_timing',
                'applicable_universe': {'market_cap': 'mid_large', 'liquidity': 'high', 'style_bias': 'panic_repair_regime'},
                'target_layer': 'target',
                'default_risk_constraints': {'stop_loss_pct': 0.06, 'take_profit_pct': 0.16, 'max_holding_days': 24, 'max_position_pct': 0.14},
                'portfolio_weight_method': 'regime_conviction_tilt',
            },
        },
        'sector_rotation': {
            'template_generation_profile': 'conservative_rotation',
            'holding_horizon': {'min_days': 5, 'max_days': 20},
            'trade_plan': {'entry_bias': 'relative_strength_rotation', 'exit_bias': 'leadership_decay_or_time_stop'},
            'risk_rules': {'stop_loss_pct': 0.08, 'take_profit_pct': 0.18, 'max_holding_days': 20, 'max_position_pct': 0.15},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'periodic_rebalance', 'frequency_days': 5},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'sector_score_tilt',
                'max_position_pct': 0.15,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 6,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
            },
            'validation_profile': {
                'profile': 'trade_rule_validation',
                'validation_focus': 'target_plus_representative',
                'primary_validation_layer': 'combined',
            },
            'targeting_policy': {
                'target_symbol_policy': 'sector_leader_rotation',
                'universe_scope': 'liquid_sector_leaders',
                'universe_expansion_policy': 'sector_relative_strength',
            },
            'rule_template_contract': {
                'template_generation_profile': 'conservative_rotation',
                'applicable_universe': {'market_cap': 'mid_large', 'liquidity': 'high', 'style_bias': 'sector_leadership'},
                'target_layer': 'combined',
                'default_risk_constraints': {'stop_loss_pct': 0.08, 'take_profit_pct': 0.18, 'max_holding_days': 20, 'max_position_pct': 0.15},
                'portfolio_weight_method': 'sector_score_tilt',
            },
        },
        'north_capital_track': {
            'template_generation_profile': 'conservative_flow',
            'holding_horizon': {'min_days': 4, 'max_days': 12},
            'trade_plan': {'entry_bias': 'capital_flow_confirmation', 'exit_bias': 'flow_reversal_or_time_stop'},
            'risk_rules': {'stop_loss_pct': 0.07, 'take_profit_pct': 0.16, 'max_holding_days': 12, 'max_position_pct': 0.16},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'periodic_rebalance', 'frequency_days': 3},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'flow_score_tilt',
                'max_position_pct': 0.16,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 6,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
            },
            'validation_profile': {
                'profile': 'trade_rule_validation',
                'validation_focus': 'target_plus_representative',
                'primary_validation_layer': 'combined',
            },
            'targeting_policy': {
                'target_symbol_policy': 'northbound_eligible_focus',
                'universe_scope': 'northbound_liquid_core',
                'universe_expansion_policy': 'flow_leaders_only',
            },
            'rule_template_contract': {
                'template_generation_profile': 'conservative_flow',
                'applicable_universe': {'northbound_eligible': True, 'liquidity': 'high', 'style_bias': 'capital_flow_leaders'},
                'target_layer': 'combined',
                'default_risk_constraints': {'stop_loss_pct': 0.07, 'take_profit_pct': 0.16, 'max_holding_days': 12, 'max_position_pct': 0.16},
                'portfolio_weight_method': 'flow_score_tilt',
            },
        },
        'event_structure_breakout': {
            'template_generation_profile': 'high_precision_event_structure',
            'holding_horizon': {'min_days': 3, 'max_days': 12, 'expected_turnover_band': 'low'},
            'trade_plan': {
                'entry_bias': 'event_structure_breakout_confirmation',
                'exit_bias': 'breakout_failure_or_time_stop',
            },
            'risk_rules': {'stop_loss_pct': 0.06, 'take_profit_pct': 0.16, 'max_holding_days': 12, 'max_position_pct': 0.14},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'signal_rebalance', 'frequency_days': 4},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'event_structure_breakout_weight',
                'max_position_pct': 0.14,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 5,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
                'market_impact_bps': 1.0,
                'capacity_bucket': 'mid',
            },
            'validation_profile': {
                'profile': 'event_trade_validation',
                'validation_focus': 'candidate_target_only',
                'primary_validation_layer': 'target',
                'objective_profile': 'high_precision',
                'trade_density_preference': 'low',
                'regime_required': True,
                'cost_robust_required': True,
                'entry_selectivity': 'strict_event_breakout',
                'preferred_regime': 'event_follow_through_with_structure_confirmation',
                'avoid_regime': 'false_breakout_or_post_event_mean_reversion',
                'event_prefilter_required': True,
                'event_prefilter_profile': 'announcement_flow_sector_v1',
                'event_prefilter_min_confirmations': 1,
            },
            'family_specialization': {
                'event_prefilter': 'require_announcement_fund_flow_or_sector_catalyst_before_breakout_confirmation',
                'event_impulse_confirmation': 'require_recent_impulse_before_breakout_attempt',
                'breakout_confirmation': 'require_close_above_prior_high_with_buffer',
                'liquidity_confirmation': 'require_volume_reexpansion_at_breakout',
                'structure_confirmation': 'require_high_close_location_and_positive_body',
                'adverse_breakout_exit': 'exit_on_breakout_failure_or_volume_fade',
                'holding_bias': 'event_follow_through_hold_3_to_12_days',
                'rebalance_bias': 'signal_rebalance_every_4_days',
            },
            'targeting_policy': {
                'target_symbol_policy': 'strict_intersection',
                'universe_scope': 'liquid_event_breakout_leaders',
                'universe_expansion_policy': 'forbid',
            },
            'holding_rationale': '只在催化后先走出短窗口强势，再经历缩量整理并放量突破的结构延续段参与，避免在普通噪声突破里频繁追价。',
            'position_model': 'equal_weight',
            'capacity_assumption': {'max_position_pct': 0.14, 'capacity_bucket': 'mid', 'symbol_count': 4},
            'event_prefilter': {
                'required': True,
                'profile': 'announcement_flow_sector_v1',
                'allowed_sources': ['announcement', 'fund_flow', 'sector_catalyst'],
                'observed_sources': [],
                'observed_confirmation_count': 0,
                'confirmation_count': 0,
                'min_confirmations': 1,
                'passed': False,
                'status': 'missing',
                'focus_industries': [],
                'event_anchor': {},
                'anchor_strength': None,
            },
            'market_regime_assumption': {
                'summary': '事件催化后的短窗口延续、缩量整理和放量突破共振阶段更有效，需要避免普通假突破与事件后均值回归。',
                'preferred_regime': 'event_follow_through_with_structure_confirmation',
                'avoid_regime': 'false_breakout_or_post_event_mean_reversion',
            },
            'failure_mode': {
                'primary_failure_mode': 'false_breakout_after_event_impulse',
                'secondary_failure_mode': 'cost_drag_after_chasing_extension',
                'invalidators': ['breakout_volume_not_confirmed', 'close_falls_back_into_range'],
            },
            'rule_template_contract': {
                'template_generation_profile': 'high_precision_event_structure',
                'applicable_universe': {'market_cap': 'mid_large', 'liquidity': 'high', 'style_bias': 'event_structure_follow_through'},
                'target_layer': 'target',
                'default_risk_constraints': {'stop_loss_pct': 0.06, 'take_profit_pct': 0.16, 'max_holding_days': 12, 'max_position_pct': 0.14},
                'portfolio_weight_method': 'event_structure_breakout_weight',
            },
        },
        'margin_divergence': {
            'template_generation_profile': 'high_precision_flow_repair',
            'holding_horizon': {'min_days': 3, 'max_days': 10, 'expected_turnover_band': 'low'},
            'trade_plan': {
                'entry_bias': 'liquidity_divergence_repair_confirmation',
                'exit_bias': 'liquidity_break_or_time_stop',
            },
            'risk_rules': {'stop_loss_pct': 0.05, 'take_profit_pct': 0.12, 'max_holding_days': 10, 'max_position_pct': 0.12},
            'position_sizing': {'mode': 'equal_weight', 'position_assumption': 'equal_weight_proxy'},
            'rebalance_rule': {'mode': 'signal_rebalance', 'frequency_days': 3},
            'portfolio_spec': {
                'position_assumption': 'equal_weight_proxy',
                'target_weight_scheme': 'equal_weight',
                'weight_method': 'liquidity_divergence_weight',
                'max_position_pct': 0.12,
            },
            'execution_assumptions': {
                'commission_rate': 0.00025,
                'slippage_bps': 4,
                'tradability_filter': True,
                'slippage_model': 'fixed',
                'market_ruleset': 'cn_equity',
                'market_impact_bps': 1.0,
                'capacity_bucket': 'small',
            },
            'validation_profile': {
                'profile': 'trade_rule_validation',
                'validation_focus': 'candidate_target_only',
                'primary_validation_layer': 'target',
                'objective_profile': 'high_precision',
                'trade_density_preference': 'low',
                'regime_required': True,
                'cost_robust_required': True,
                'entry_selectivity': 'strict',
                'preferred_regime': 'liquidity_repair_with_volume_reexpansion',
                'avoid_regime': 'volume_vacuum_or_failed_rebound',
            },
            'family_specialization': {
                'repair_confirmation': 'require_medium_window_drawdown_plus_short_window_rebound',
                'liquidity_confirmation': 'require_pre_entry_volume_dryup_and_entry_volume_reexpansion',
                'structure_confirmation': 'require_high_close_location_and_positive_body',
                'adverse_regime_exit': 'exit_on_volume_break_or_failed_rebound',
                'holding_bias': 'repair_window_hold_3_to_10_days',
                'rebalance_bias': 'signal_rebalance_every_3_days',
            },
            'targeting_policy': {
                'target_symbol_policy': 'margin_activity_focus',
                'universe_scope': 'liquidity_repair_candidates',
                'universe_expansion_policy': 'divergence_repair_only',
            },
            'holding_rationale': '只在中期下跌后出现缩量止跌、放量修复和结构转强共振时参与，优先低频高把握，不在普通反抽里频繁交易。',
            'position_model': 'equal_weight',
            'capacity_assumption': {'max_position_pct': 0.12, 'capacity_bucket': 'small', 'symbol_count': 4},
            'market_regime_assumption': {
                'summary': '流动性收缩后出现放量修复且结构转强的阶段更有效，需要避免缩量阴跌与假修复。',
                'preferred_regime': 'liquidity_repair_with_volume_reexpansion',
                'avoid_regime': 'volume_vacuum_or_failed_rebound',
            },
            'failure_mode': {
                'primary_failure_mode': 'failed_rebound_after_liquidity_dryup',
                'secondary_failure_mode': 'cost_fragility_after_false_reexpansion',
                'invalidators': ['entry_volume_not_confirmed', 'structure_break_after_entry'],
            },
            'rule_template_contract': {
                'template_generation_profile': 'high_precision_flow_repair',
                'applicable_universe': {'margin_active': True, 'liquidity': 'high', 'style_bias': 'liquidity_divergence_repair'},
                'target_layer': 'target',
                'default_risk_constraints': {'stop_loss_pct': 0.05, 'take_profit_pct': 0.12, 'max_holding_days': 10, 'max_position_pct': 0.12},
                'portfolio_weight_method': 'liquidity_divergence_weight',
            },
        },
    }
    strategy_key = str(strategy_type or '').strip().lower()
    return _enrich_rule_template_contract(
        strategy_key,
        deepcopy(contracts.get(strategy_key) or {}),
    )
