import { z } from 'zod';

export const managerSchema = z.object({
    action: z.string().default('help').describe('操作类型'),
    type: z.string().optional().describe('子类型'),
    // 股票相关
    code: z.string().optional().describe('股票代码'),
    codes: z.array(z.string()).optional().describe('股票代码列表'),
    name: z.string().optional().describe('名称'),
    // 持仓相关
    quantity: z.number().optional().describe('数量'),
    costPrice: z.number().optional().describe('成本价'),
    price: z.number().optional().describe('价格'),
    weight: z.number().optional().describe('权重'),
    positionId: z.number().optional().describe('持仓ID'),
    // 时间相关
    startDate: z.string().optional().describe('开始日期 YYYY-MM-DD'),
    endDate: z.string().optional().describe('结束日期 YYYY-MM-DD'),
    date: z.string().optional().describe('日期'),
    period: z.string().optional().describe('周期'),
    // 回测相关
    strategy: z.string().optional().describe('策略类型'),
    initialCapital: z.number().optional().describe('初始资金'),
    shortPeriod: z.number().optional().describe('短周期'),
    longPeriod: z.number().optional().describe('长周期'),
    lookback: z.number().optional().describe('回看周期'),
    threshold: z.number().optional().describe('阈值'),
    commission: z.number().optional().describe('佣金率'),
    slippage: z.number().optional().describe('滑点'),
    backtestId: z.string().optional().describe('回测ID'),
    // 告警相关
    condition: z.string().optional().describe('条件'),
    value: z.number().optional().describe('数值'),
    alertId: z.string().optional().describe('告警ID'),
    alertName: z.string().optional().describe('告警名称'),
    conditions: z.any().optional().describe('条件组'),
    includeTriggered: z.boolean().optional().describe('是否包含已触发'),
    // 自选股相关
    groupId: z.string().optional().describe('分组ID'),
    notes: z.string().optional().describe('备注'),
    // 模拟交易相关
    accountId: z.string().optional().describe('账户ID'),
    accountName: z.string().optional().describe('账户名称'),
    side: z.string().optional().describe('买卖方向'),
    // 筛选相关
    preset: z.string().optional().describe('预设策略'),
    query: z.string().optional().describe('查询条件'),
    peMax: z.number().optional().describe('PE上限'),
    pbMax: z.number().optional().describe('PB上限'),
    roeMin: z.number().optional().describe('ROE下限'),
    marketCapMin: z.number().optional().describe('市值下限'),
    marketCapMax: z.number().optional().describe('市值上限'),
    // 通用
    limit: z.number().optional().describe('返回数量限制'),
    offset: z.number().optional().describe('偏移量'),
    indicator: z.string().optional().describe('指标'),
    indicators: z.array(z.string()).optional().describe('指标列表'),
    // 组合优化
    method: z.string().optional().describe('优化方法'),
    targetVolatility: z.number().optional().describe('目标波动率'),
    riskBudgets: z.array(z.number()).optional().describe('风险预算'),
    benchmark: z.string().optional().describe('基准指数'),
    holdings: z.array(z.any()).optional().describe('持仓列表'),
    stocks: z.array(z.string()).optional().describe('股票池'),
    weights: z.array(z.number()).optional().describe('权重列表'),
    // 用户相关
    userId: z.string().optional().describe('用户ID'),
    preferences: z.any().optional().describe('偏好设置'),
    key: z.string().optional().describe('键'),
    // 执行算法
    totalQuantity: z.number().optional().describe('总数量'),
    algorithm: z.string().optional().describe('算法类型'),
    duration: z.number().optional().describe('执行时长'),
    // 合规
    maxSinglePosition: z.number().optional().describe('单只最大仓位'),
    maxSectorWeight: z.number().optional().describe('行业最大权重'),
    // 事件
    eventTypes: z.array(z.string()).optional().describe('事件类型'),
});
