#!/usr/bin/env python3
"""一致性检查脚本。

用途：
1) 校验 requirements.txt 是否与 pyproject.toml 的 [project.dependencies] 一致；
2) 校验 src/akshare_mcp/__init__.py 的 __version__ 与 pyproject.toml 版本一致；
3) 校验仓库根 README.md 的 Python 最低版本声明与 pyproject requires-python 一致；
4) 校验 requirements.lock.txt 存在且包含 uv 生成标记。

返回码：
- 0: 全部一致
- 1: 存在不一致/读取失败
"""

from __future__ import annotations

from pathlib import Path
import re

try:
    import tomllib  # py>=3.11
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore


PKG_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PKG_ROOT.parents[1]
PYPROJECT = PKG_ROOT / "pyproject.toml"
REQUIREMENTS = PKG_ROOT / "requirements.txt"
REQUIREMENTS_LOCK = PKG_ROOT / "requirements.lock.txt"
PKG_INIT = PKG_ROOT / "src" / "akshare_mcp" / "__init__.py"
ROOT_README = REPO_ROOT / "README.md"


def _normalize(lines: list[str]) -> list[str]:
    normalized: list[str] = []
    for line in lines:
        item = line.strip()
        if not item or item.startswith("#"):
            continue
        normalized.append(item)
    return normalized


def load_pyproject() -> dict:
    with PYPROJECT.open("rb") as f:
        return tomllib.load(f)


def load_pyproject_deps(pyproject: dict) -> list[str]:
    deps = pyproject.get("project", {}).get("dependencies", [])
    if not isinstance(deps, list):
        raise ValueError("pyproject.toml: [project.dependencies] 不是数组")
    return _normalize([str(d) for d in deps])


def load_requirements_deps() -> list[str]:
    lines = REQUIREMENTS.read_text(encoding="utf-8").splitlines()
    return _normalize(lines)


def extract_pkg_version() -> str | None:
    text = PKG_INIT.read_text(encoding="utf-8")
    m = re.search(r'__version__\s*=\s*"([^"]+)"', text)
    return m.group(1) if m else None


def extract_root_readme_python_min() -> str | None:
    text = ROOT_README.read_text(encoding="utf-8")
    m = re.search(r"Python\s*>=\s*([0-9]+\.[0-9]+)", text, flags=re.IGNORECASE)
    return m.group(1) if m else None


def lock_file_ok() -> bool:
    if not REQUIREMENTS_LOCK.exists():
        return False
    head = REQUIREMENTS_LOCK.read_text(encoding="utf-8").splitlines()[:5]
    joined = "\n".join(head)
    return "autogenerated by uv" in joined and "uv export" in joined


def main() -> int:
    try:
        pyproject = load_pyproject()
        pyproject_deps = load_pyproject_deps(pyproject)
        requirements_deps = load_requirements_deps()
    except Exception as exc:
        print(f"[ERROR] 读取依赖失败: {exc}")
        return 1

    failures: list[str] = []

    # 1) 依赖一致性
    pset = set(pyproject_deps)
    rset = set(requirements_deps)
    missing_in_requirements = sorted(pset - rset)
    extra_in_requirements = sorted(rset - pset)
    if missing_in_requirements or extra_in_requirements:
        failures.append("requirements.txt 与 pyproject.toml 依赖不一致")
        if missing_in_requirements:
            print("- requirements.txt 缺失依赖:")
            for dep in missing_in_requirements:
                print(f"  - {dep}")
        if extra_in_requirements:
            print("- requirements.txt 存在额外依赖:")
            for dep in extra_in_requirements:
                print(f"  - {dep}")

    # 2) 包版本一致性
    pyproject_version = str(pyproject.get("project", {}).get("version", "")).strip()
    pkg_version = (extract_pkg_version() or "").strip()
    if not pyproject_version or not pkg_version or pyproject_version != pkg_version:
        failures.append(
            f"版本不一致: pyproject={pyproject_version or 'N/A'} vs __init__={pkg_version or 'N/A'}"
        )

    # 3) README Python 版本门槛一致性
    requires_python = str(pyproject.get("project", {}).get("requires-python", "")).strip()
    readme_python_min = (extract_root_readme_python_min() or "").strip()
    expected_min = requires_python.removeprefix(">=").strip() if requires_python.startswith(">=") else requires_python
    if not expected_min or not readme_python_min or expected_min != readme_python_min:
        failures.append(
            f"Python 版本声明不一致: pyproject={requires_python or 'N/A'} vs README={readme_python_min or 'N/A'}"
        )

    # 4) lock 文件存在性与来源标记
    if not lock_file_ok():
        failures.append("requirements.lock.txt 缺失或不含 uv 生成标记")

    if failures:
        print("[FAIL] 一致性校验失败")
        for item in failures:
            print(f"- {item}")
        return 1

    print("[OK] 依赖/版本/README/lock 一致性校验通过")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

